//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Enterprise Library Data Access Application Block 的本地化字符串。
        /// </summary>
        internal static string BlockName {
            get {
                return ResourceManager.GetString("BlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commands Executed/sec is the rate at which database commands were executed. 的本地化字符串。
        /// </summary>
        internal static string CommandExecutedCounterHelpResource {
            get {
                return ResourceManager.GetString("CommandExecutedCounterHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commands Failed/sec is tha rate at which database commands failed to execute. 的本地化字符串。
        /// </summary>
        internal static string CommandFailedCounterHelpResource {
            get {
                return ResourceManager.GetString("CommandFailedCounterHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A configuration failure occurred while creating database ‘{0}’. 的本地化字符串。
        /// </summary>
        internal static string ConfigurationFailureCreatingDatabase {
            get {
                return ResourceManager.GetString("ConfigurationFailureCreatingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connections Failed/sec is the rate at which database connections failed to open. 的本地化字符串。
        /// </summary>
        internal static string ConnectionFailedCounterHelpResource {
            get {
                return ResourceManager.GetString("ConnectionFailedCounterHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connections Opened/sec is the rate at which database connections were opened. 的本地化字符串。
        /// </summary>
        internal static string ConnectionOpenedCounterHelpResource {
            get {
                return ResourceManager.GetString("ConnectionOpenedCounterHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enterprise Library Data Performance Counter Instances 的本地化字符串。
        /// </summary>
        internal static string CounterCategoryHelpResourceName {
            get {
                return ResourceManager.GetString("CounterCategoryHelpResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The connection string used was &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string ErrorConnectionFailedExtraInformation {
            get {
                return ResourceManager.GetString("ErrorConnectionFailedExtraInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The error occurred using the &quot;{0}&quot; database instance while attempting to open the database connection. 的本地化字符串。
        /// </summary>
        internal static string ErrorConnectionFailedMessage {
            get {
                return ResourceManager.GetString("ErrorConnectionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The command must be a SqlCommand. 的本地化字符串。
        /// </summary>
        internal static string ExceptionCommandNotSqlCommand {
            get {
                return ResourceManager.GetString("ExceptionCommandNotSqlCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The database type {0} for the name {1} does not have the required [DatabaseAssembler] attribute required to build the database object. 的本地化字符串。
        /// </summary>
        internal static string ExceptionDatabaseTypeDoesNotHaveAssemblerAttribute {
            get {
                return ResourceManager.GetString("ExceptionDatabaseTypeDoesNotHaveAssemblerAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The database type {0} does not have the required ConfigurationElementType attribute. 的本地化字符串。
        /// </summary>
        internal static string ExceptionDatabaseTypeDoesNotHaveRequiredConfigurationTypeAttribute {
            get {
                return ResourceManager.GetString("ExceptionDatabaseTypeDoesNotHaveRequiredConfigurationTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of parameters does not match number of values for stored procedure. 的本地化字符串。
        /// </summary>
        internal static string ExceptionMessageParameterMatchFailure {
            get {
                return ResourceManager.GetString("ExceptionMessageParameterMatchFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At least one command must be initialized 的本地化字符串。
        /// </summary>
        internal static string ExceptionMessageUpdateDataSetArgumentFailure {
            get {
                return ResourceManager.GetString("ExceptionMessageUpdateDataSetArgumentFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to update row  的本地化字符串。
        /// </summary>
        internal static string ExceptionMessageUpdateDataSetRowFailure {
            get {
                return ResourceManager.GetString("ExceptionMessageUpdateDataSetRowFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The requested database {0} is not defined in configuration. 的本地化字符串。
        /// </summary>
        internal static string ExceptionNoDatabaseDefined {
            get {
                return ResourceManager.GetString("ExceptionNoDatabaseDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The requested database {0} does not have provider name set in the connection string. 的本地化字符串。
        /// </summary>
        internal static string ExceptionNoProviderDefinedForConnectionString {
            get {
                return ResourceManager.GetString("ExceptionNoProviderDefinedForConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value can not be null or an empty string. 的本地化字符串。
        /// </summary>
        internal static string ExceptionNullOrEmptyString {
            get {
                return ResourceManager.GetString("ExceptionNullOrEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter discovery is not supported for connections using GenericDatabase. You must specify the parameters explicitly, or configure the connection to use a type deriving from Database that supports parameter discovery. 的本地化字符串。
        /// </summary>
        internal static string ExceptionParameterDiscoveryNotSupportedOnGenericDatabase {
            get {
                return ResourceManager.GetString("ExceptionParameterDiscoveryNotSupportedOnGenericDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The table name array used to map results to user-specified table names cannot be empty. 的本地化字符串。
        /// </summary>
        internal static string ExceptionTableNameArrayEmpty {
            get {
                return ResourceManager.GetString("ExceptionTableNameArrayEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type {0} is not an implementation of IDatabaseAssembler for DatabaseAssemblerAttribute. 的本地化字符串。
        /// </summary>
        internal static string ExceptionTypeNotDatabaseAssembler {
            get {
                return ResourceManager.GetString("ExceptionTypeNotDatabaseAssembler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 password=,pwd= 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Commands Executed is the total number which database commands were executed. 的本地化字符串。
        /// </summary>
        internal static string TotalCommandsExecutedHelpResource {
            get {
                return ResourceManager.GetString("TotalCommandsExecutedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Commands Failed is the total number which database commands failed to execute. 的本地化字符串。
        /// </summary>
        internal static string TotalCommandsFailedHelpResource {
            get {
                return ResourceManager.GetString("TotalCommandsFailedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Connections Failed is the total number which database connections failed to open. 的本地化字符串。
        /// </summary>
        internal static string TotalConnectionFailedHelpResource {
            get {
                return ResourceManager.GetString("TotalConnectionFailedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Connections Opened is the total number which database connections were opened. 的本地化字符串。
        /// </summary>
        internal static string TotalConnectionOpenedHelpResource {
            get {
                return ResourceManager.GetString("TotalConnectionOpenedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 user id=,uid= 的本地化字符串。
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
