//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3082
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheng.SailingEase.Components.NavigationComponent.Localisation {
    
    
    public interface ILanguage {
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        global::System.Resources.ResourceManager ResourceManager {
            get;
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        global::System.Globalization.CultureInfo Culture {
            get;
        }
        
        /// <summary>
        ///   查找类似 工具栏项暂不支持多级。 的本地化字符串。
        /// </summary>
        string Explorer_Commands_AddToolStripItemCommand_NotSupportSubItem {
            get;
        }
        
        /// <summary>
        ///   查找类似 菜单 的本地化字符串。
        /// </summary>
        string Explorer_ExplorerTreeView_Tab_Menu {
            get;
        }
        
        /// <summary>
        ///   查找类似 工具栏 的本地化字符串。
        /// </summary>
        string Explorer_ExplorerTreeView_Tab_ToolStrip {
            get;
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        string Explorer_ExplorerTreeView_TabText {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string Explorer_GridColumns_MenuColumns_Code {
            get;
        }
        
        /// <summary>
        ///   查找类似 菜单名 的本地化字符串。
        /// </summary>
        string Explorer_GridColumns_MenuColumns_Name {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string Explorer_GridColumns_ToolStripColumns_Code {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string Explorer_GridColumns_ToolStripColumns_Name {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        string Explorer_GridMenuToolStripGroup_Add {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        string Explorer_GridMenuToolStripGroup_Delete {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        string Explorer_GridMenuToolStripGroup_Edit {
            get;
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        string Explorer_GridMenuToolStripGroup_MoveAfter {
            get;
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        string Explorer_GridMenuToolStripGroup_MoveBefore {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        string Explorer_GridMenuToolStripItem_Add {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        string Explorer_GridMenuToolStripItem_Delete {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        string Explorer_GridMenuToolStripItem_Edit {
            get;
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        string Explorer_GridMenuToolStripItem_MoveAfter {
            get;
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        string Explorer_GridMenuToolStripItem_MoveBefore {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        string Explorer_GridMenuToolStripPage_Add {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        string Explorer_GridMenuToolStripPage_Delete {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        string Explorer_GridMenuToolStripPage_Edit {
            get;
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        string Explorer_GridMenuToolStripPage_MoveAfter {
            get;
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        string Explorer_GridMenuToolStripPage_MoveBefore {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        string Explorer_GridViewMenuMenuEntity_Add {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        string Explorer_GridViewMenuMenuEntity_Delete {
            get;
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        string Explorer_GridViewMenuMenuEntity_Down {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        string Explorer_GridViewMenuMenuEntity_Edit {
            get;
        }
        
        /// <summary>
        ///   查找类似 预览 的本地化字符串。
        /// </summary>
        string Explorer_GridViewMenuMenuEntity_Preview {
            get;
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        string Explorer_GridViewMenuMenuEntity_Up {
            get;
        }
        
        /// <summary>
        ///   查找类似 返回上级 的本地化字符串。
        /// </summary>
        string Explorer_GridViewMenuMenuEntity_UpLayer {
            get;
        }
        
        /// <summary>
        ///   查找类似 主菜单 的本地化字符串。
        /// </summary>
        string Explorer_MenuEntityFolder {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定代码的项已存在。 的本地化字符串。
        /// </summary>
        string Explorer_PropertyView_MessageCodeExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        string Explorer_PropertyView_TabText {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        string Explorer_ToolStripGeneral_Add {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        string Explorer_ToolStripGeneral_Delete {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        string Explorer_ToolStripGeneral_Edit {
            get;
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        string Explorer_ToolStripGeneral_MoveAfter {
            get;
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        string Explorer_ToolStripGeneral_MoveBefore {
            get;
        }
        
        /// <summary>
        ///   查找类似 工具栏项目 的本地化字符串。
        /// </summary>
        string Explorer_ToolStripItemFolder {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuMenuEntity_Add {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuMenuEntity_Delete {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuMenuEntity_Edit {
            get;
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuMenuEntity_MoveAfter {
            get;
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuMenuEntity_MoveBefore {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuMenuEntityFolder_Add {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加项 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuToolStripGroup_Add {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuToolStripGroup_Delete {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuToolStripGroup_Edit {
            get;
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuToolStripGroup_MoveAfter {
            get;
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuToolStripGroup_MoveBefore {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuToolStripItem_Add {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuToolStripItem_Delete {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuToolStripItem_Edit {
            get;
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuToolStripItem_MoveAfter {
            get;
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuToolStripItem_MoveBefore {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加页 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuToolStripItemFolder_Add {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加分组 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuToolStripPage_Add {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuToolStripPage_Delete {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuToolStripPage_Edit {
            get;
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuToolStripPage_MoveAfter {
            get;
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        string Explorer_TreeMenuToolStripPage_MoveBefore {
            get;
        }
        
        /// <summary>
        ///   查找类似 导航 的本地化字符串。
        /// </summary>
        string ExplorerView_TabText {
            get;
        }
        
        /// <summary>
        ///   查找类似 不可用 的本地化字符串。
        /// </summary>
        string FormFormElementAdd_LabelDisable {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定代码的主工具栏项已存在 的本地化字符串。
        /// </summary>
        string FormFormElementAdd_MessageElementCodeExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的代码无效,系统保留字. 的本地化字符串。
        /// </summary>
        string FormFormElementAdd_MessageUseKeywords {
            get;
        }
        
        /// <summary>
        ///   查找类似 主菜单 的本地化字符串。
        /// </summary>
        string MenuEditView {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string MenuEditView_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string MenuEditView_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string MenuEditView_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 主菜单名 的本地化字符串。
        /// </summary>
        string MenuEditView_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 文本 的本地化字符串。
        /// </summary>
        string MenuEditView_LabelText {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定代码的主菜单项已存在 的本地化字符串。
        /// </summary>
        string MenuEditView_MessageMainMenuCodeExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的代码无效,系统保留字. 的本地化字符串。
        /// </summary>
        string MenuEditView_MessageUseKeywords {
            get;
        }
        
        /// <summary>
        ///   查找类似 事件 的本地化字符串。
        /// </summary>
        string MenuEditView_TabPageEvent {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string MenuEditView_TabPageGeneral {
            get;
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        string MenuEditView_TabPageRemark {
            get;
        }
        
        /// <summary>
        ///   查找类似 主菜单 的本地化字符串。
        /// </summary>
        string MenuStripExplorerView {
            get;
        }
        
        /// <summary>
        ///   查找类似 主菜单 的本地化字符串。
        /// </summary>
        string Navigation_Menu_MainMenu {
            get;
        }
        
        /// <summary>
        ///   查找类似 主菜单 的本地化字符串。
        /// </summary>
        string Navigation_ToolStrip_MainMenu {
            get;
        }
        
        /// <summary>
        ///   查找类似 分组 的本地化字符串。
        /// </summary>
        string ToolStripGroupEditView {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string ToolStripGroupEditView_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string ToolStripGroupEditView_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string ToolStripGroupEditView_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string ToolStripGroupEditView_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定代码的主工具栏分组已存在 的本地化字符串。
        /// </summary>
        string ToolStripGroupEditView_MessageElementCodeExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的代码无效,系统保留字. 的本地化字符串。
        /// </summary>
        string ToolStripGroupEditView_MessageUseKeywords {
            get;
        }
        
        /// <summary>
        ///   查找类似 工具栏项目 的本地化字符串。
        /// </summary>
        string ToolStripItemEditView {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string ToolStripItemEditView_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string ToolStripItemEditView_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string ToolStripItemEditView_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        string ToolStripItemEditView_LabelControlType {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string ToolStripItemEditView_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 细节 的本地化字符串。
        /// </summary>
        string ToolStripItemEditView_TabPageDetail {
            get;
        }
        
        /// <summary>
        ///   查找类似 事件 的本地化字符串。
        /// </summary>
        string ToolStripItemEditView_TabPageEvent {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string ToolStripItemEditView_TabPageGeneral {
            get;
        }
        
        /// <summary>
        ///   查找类似 页 的本地化字符串。
        /// </summary>
        string ToolStripPageEditView {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string ToolStripPageEditView_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string ToolStripPageEditView_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string ToolStripPageEditView_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string ToolStripPageEditView_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定代码的主工具栏页已存在 的本地化字符串。
        /// </summary>
        string ToolStripPageEditView_MessageElementCodeExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的代码无效,系统保留字. 的本地化字符串。
        /// </summary>
        string ToolStripPageEditView_MessageUseKeywords {
            get;
        }
        
        /// <summary>
        ///  Returns true if the current language is the default language.
        /// </summary>
        bool IsDefault {
            get;
        }
    }
}
