//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5448
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheng.SailingEase.Components.Window.DesignComponent.Localisation {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Chinese__Simplified_ : ILanguage {
        
        private global::System.Resources.ResourceManager resourceMan;
        
        private global::System.Globalization.CultureInfo resourceCulture;
        
        public Chinese__Simplified_() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sheng.SailingEase.Components.Window.DesignComponent.Localisation.Chinese (Simplif" +
                            "ied)", typeof(Chinese__Simplified_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.Globalization.CultureInfo Culture {
            get {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    global::System.Globalization.CultureInfo temp = new global::System.Globalization.CultureInfo("zh-CHS");
                    resourceCulture = temp;
                }
                return resourceCulture;
            }
        }
        
        /// <summary>
        ///   查找类似 向前移动 的本地化字符串。
        /// </summary>
        public string ContextMenuCommandBringForward {
            get {
                return ResourceManager.GetString("ContextMenuCommandBringForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置于顶层 的本地化字符串。
        /// </summary>
        public string ContextMenuCommandBringToFront {
            get {
                return ResourceManager.GetString("ContextMenuCommandBringToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public string ContextMenuCommandCopy {
            get {
                return ResourceManager.GetString("ContextMenuCommandCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪切 的本地化字符串。
        /// </summary>
        public string ContextMenuCommandCut {
            get {
                return ResourceManager.GetString("ContextMenuCommandCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public string ContextMenuCommandDelete {
            get {
                return ResourceManager.GetString("ContextMenuCommandDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定控件 的本地化字符串。
        /// </summary>
        public string ContextMenuCommandLockControls {
            get {
                return ResourceManager.GetString("ContextMenuCommandLockControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴 的本地化字符串。
        /// </summary>
        public string ContextMenuCommandPaste {
            get {
                return ResourceManager.GetString("ContextMenuCommandPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        public string ContextMenuCommandProperties {
            get {
                return ResourceManager.GetString("ContextMenuCommandProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public string ContextMenuCommandSelectAll {
            get {
                return ResourceManager.GetString("ContextMenuCommandSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向后移动 的本地化字符串。
        /// </summary>
        public string ContextMenuCommandSendBackward {
            get {
                return ResourceManager.GetString("ContextMenuCommandSendBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置于底层 的本地化字符串。
        /// </summary>
        public string ContextMenuCommandSendToBack {
            get {
                return ResourceManager.GetString("ContextMenuCommandSendToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看事件 的本地化字符串。
        /// </summary>
        public string ContextMenuCommandShowEvents {
            get {
                return ResourceManager.GetString("ContextMenuCommandShowEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tab 键顺序 的本地化字符串。
        /// </summary>
        public string ContextMenuCommandTabOrder {
            get {
                return ResourceManager.GetString("ContextMenuCommandTabOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的代码已被其它窗体元素使用 的本地化字符串。
        /// </summary>
        public string FormDesigner_FormPropertyGrid_MessageFormElementCodeExist {
            get {
                return ResourceManager.GetString("FormDesigner_FormPropertyGrid_MessageFormElementCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定代码的窗体已存在 的本地化字符串。
        /// </summary>
        public string FormDesigner_FormPropertyGrid_MessageFormEntityExist {
            get {
                return ResourceManager.GetString("FormDesigner_FormPropertyGrid_MessageFormEntityExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件 的本地化字符串。
        /// </summary>
        public string FormDesignerEvents {
            get {
                return ResourceManager.GetString("FormDesignerEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件 的本地化字符串。
        /// </summary>
        public string FormDesignerEventTree_TabText {
            get {
                return ResourceManager.GetString("FormDesignerEventTree_TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public string FormDesignerEventTree_ToolStripButtonAddEvent {
            get {
                return ResourceManager.GetString("FormDesignerEventTree_ToolStripButtonAddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public string FormDesignerEventTree_ToolStripButtonDeleteEvent {
            get {
                return ResourceManager.GetString("FormDesignerEventTree_ToolStripButtonDeleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        public string FormDesignerEventTree_ToolStripButtonDownEvent {
            get {
                return ResourceManager.GetString("FormDesignerEventTree_ToolStripButtonDownEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public string FormDesignerEventTree_ToolStripButtonEditEvent {
            get {
                return ResourceManager.GetString("FormDesignerEventTree_ToolStripButtonEditEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        public string FormDesignerEventTree_ToolStripButtonUpEvent {
            get {
                return ResourceManager.GetString("FormDesignerEventTree_ToolStripButtonUpEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载,请稍候... 的本地化字符串。
        /// </summary>
        public string FormDesignSurfaceHosting_LabelLoadingMsg {
            get {
                return ResourceManager.GetString("FormDesignSurfaceHosting_LabelLoadingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在释放资源,请稍候... 的本地化字符串。
        /// </summary>
        public string FormDesignSurfaceHosting_LabelUnloadingMsg {
            get {
                return ResourceManager.GetString("FormDesignSurfaceHosting_LabelUnloadingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在处理... 的本地化字符串。
        /// </summary>
        public string FormDesignSurfaceHosting_LabelWorkingMsg {
            get {
                return ResourceManager.GetString("FormDesignSurfaceHosting_LabelWorkingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存对窗体 [{0}] 的更改吗? 的本地化字符串。
        /// </summary>
        public string FormDesignSurfaceHosting_MessageIsSave {
            get {
                return ResourceManager.GetString("FormDesignSurfaceHosting_MessageIsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 丢弃更改的部分，无法撤销 的本地化字符串。
        /// </summary>
        public string FormDesignSurfaceHosting_MessageIsSave_NoButtonDescription {
            get {
                return ResourceManager.GetString("FormDesignSurfaceHosting_MessageIsSave_NoButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存更改 的本地化字符串。
        /// </summary>
        public string FormDesignSurfaceHosting_MessageIsSave_YesButtonDescription {
            get {
                return ResourceManager.GetString("FormDesignSurfaceHosting_MessageIsSave_YesButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗体 [{0}] 的本地化字符串。
        /// </summary>
        public string FormDesignSurfaceHosting_TabText {
            get {
                return ResourceManager.GetString("FormDesignSurfaceHosting_TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗体 的本地化字符串。
        /// </summary>
        public string FormHostingContainer {
            get {
                return ResourceManager.GetString("FormHostingContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 底端对齐 的本地化字符串。
        /// </summary>
        public string FormHostingContainer_ToolStripButtonAlignBottom {
            get {
                return ResourceManager.GetString("FormHostingContainer_ToolStripButtonAlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中间对齐 的本地化字符串。
        /// </summary>
        public string FormHostingContainer_ToolStripButtonAlignHorizontalCenters {
            get {
                return ResourceManager.GetString("FormHostingContainer_ToolStripButtonAlignHorizontalCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左对齐 的本地化字符串。
        /// </summary>
        public string FormHostingContainer_ToolStripButtonAlignLeft {
            get {
                return ResourceManager.GetString("FormHostingContainer_ToolStripButtonAlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右对齐 的本地化字符串。
        /// </summary>
        public string FormHostingContainer_ToolStripButtonAlignRight {
            get {
                return ResourceManager.GetString("FormHostingContainer_ToolStripButtonAlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶端对齐 的本地化字符串。
        /// </summary>
        public string FormHostingContainer_ToolStripButtonAlignTop {
            get {
                return ResourceManager.GetString("FormHostingContainer_ToolStripButtonAlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居中对齐 的本地化字符串。
        /// </summary>
        public string FormHostingContainer_ToolStripButtonAlignVerticalCenters {
            get {
                return ResourceManager.GetString("FormHostingContainer_ToolStripButtonAlignVerticalCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public string FormHostingContainer_ToolStripButtonCopy {
            get {
                return ResourceManager.GetString("FormHostingContainer_ToolStripButtonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪切 的本地化字符串。
        /// </summary>
        public string FormHostingContainer_ToolStripButtonCut {
            get {
                return ResourceManager.GetString("FormHostingContainer_ToolStripButtonCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴 的本地化字符串。
        /// </summary>
        public string FormHostingContainer_ToolStripButtonPaste {
            get {
                return ResourceManager.GetString("FormHostingContainer_ToolStripButtonPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        public string FormHostingContainer_ToolStripButtonProperty {
            get {
                return ResourceManager.GetString("FormHostingContainer_ToolStripButtonProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复 的本地化字符串。
        /// </summary>
        public string FormHostingContainer_ToolStripButtonRedo {
            get {
                return ResourceManager.GetString("FormHostingContainer_ToolStripButtonRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public string FormHostingContainer_ToolStripButtonSave {
            get {
                return ResourceManager.GetString("FormHostingContainer_ToolStripButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使大小相同 的本地化字符串。
        /// </summary>
        public string FormHostingContainer_ToolStripButtonSizeToControl {
            get {
                return ResourceManager.GetString("FormHostingContainer_ToolStripButtonSizeToControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使高度相同 的本地化字符串。
        /// </summary>
        public string FormHostingContainer_ToolStripButtonSizeToControlHeight {
            get {
                return ResourceManager.GetString("FormHostingContainer_ToolStripButtonSizeToControlHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使宽度相同 的本地化字符串。
        /// </summary>
        public string FormHostingContainer_ToolStripButtonSizeToControlWidth {
            get {
                return ResourceManager.GetString("FormHostingContainer_ToolStripButtonSizeToControlWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具箱 的本地化字符串。
        /// </summary>
        public string FormHostingContainer_ToolStripButtonToolbox {
            get {
                return ResourceManager.GetString("FormHostingContainer_ToolStripButtonToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销 的本地化字符串。
        /// </summary>
        public string FormHostingContainer_ToolStripButtonUndo {
            get {
                return ResourceManager.GetString("FormHostingContainer_ToolStripButtonUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public string FormHostingContainer_ToolStripMenuItemRefreshWarning {
            get {
                return ResourceManager.GetString("FormHostingContainer_ToolStripMenuItemRefreshWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ({0}) 警告 的本地化字符串。
        /// </summary>
        public string FormHostingContainer_ToolStripSplitButtonWarning {
            get {
                return ResourceManager.GetString("FormHostingContainer_ToolStripSplitButtonWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public string FormMultiSave {
            get {
                return ResourceManager.GetString("FormMultiSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public string FormMultiSave_ButtonCancel {
            get {
                return ResourceManager.GetString("FormMultiSave_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public string FormMultiSave_ButtonNo {
            get {
                return ResourceManager.GetString("FormMultiSave_ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public string FormMultiSave_ButtonYes {
            get {
                return ResourceManager.GetString("FormMultiSave_ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存对以下各项的更改吗? 的本地化字符串。
        /// </summary>
        public string FormMultiSave_LabelNotice {
            get {
                return ResourceManager.GetString("FormMultiSave_LabelNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        public string FormPropertyGrid_TabText {
            get {
                return ResourceManager.GetString("FormPropertyGrid_TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具箱 的本地化字符串。
        /// </summary>
        public string FormToolbox_TabText {
            get {
                return ResourceManager.GetString("FormToolbox_TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public string HostingTabPageContextMenuStrip_Close {
            get {
                return ResourceManager.GetString("HostingTabPageContextMenuStrip_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭所有 的本地化字符串。
        /// </summary>
        public string HostingTabPageContextMenuStrip_CloseAll {
            get {
                return ResourceManager.GetString("HostingTabPageContextMenuStrip_CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 除此之外全部关闭 的本地化字符串。
        /// </summary>
        public string HostingTabPageContextMenuStrip_CloseAllButThis {
            get {
                return ResourceManager.GetString("HostingTabPageContextMenuStrip_CloseAllButThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已保存 的本地化字符串。
        /// </summary>
        public string StatusBarMessage_Saved {
            get {
                return ResourceManager.GetString("StatusBarMessage_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///  Returns true if the current language is the default language.
        /// </summary>
        public bool IsDefault {
            get {
                return true;
            }
        }
        
        /// <summary>
        ///  Returns a System.String that represents the current System.Object.
        /// </summary>
        public override string ToString() {
            return Culture.EnglishName;
        }
    }
}
