//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5448
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheng.SailingEase.Components.Window.DesignComponent.Localisation {
    
    
    public interface ILanguage {
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        global::System.Resources.ResourceManager ResourceManager {
            get;
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        global::System.Globalization.CultureInfo Culture {
            get;
        }
        
        /// <summary>
        ///   查找类似 向前移动 的本地化字符串。
        /// </summary>
        string ContextMenuCommandBringForward {
            get;
        }
        
        /// <summary>
        ///   查找类似 置于顶层 的本地化字符串。
        /// </summary>
        string ContextMenuCommandBringToFront {
            get;
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        string ContextMenuCommandCopy {
            get;
        }
        
        /// <summary>
        ///   查找类似 剪切 的本地化字符串。
        /// </summary>
        string ContextMenuCommandCut {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        string ContextMenuCommandDelete {
            get;
        }
        
        /// <summary>
        ///   查找类似 锁定控件 的本地化字符串。
        /// </summary>
        string ContextMenuCommandLockControls {
            get;
        }
        
        /// <summary>
        ///   查找类似 粘贴 的本地化字符串。
        /// </summary>
        string ContextMenuCommandPaste {
            get;
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        string ContextMenuCommandProperties {
            get;
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        string ContextMenuCommandSelectAll {
            get;
        }
        
        /// <summary>
        ///   查找类似 向后移动 的本地化字符串。
        /// </summary>
        string ContextMenuCommandSendBackward {
            get;
        }
        
        /// <summary>
        ///   查找类似 置于底层 的本地化字符串。
        /// </summary>
        string ContextMenuCommandSendToBack {
            get;
        }
        
        /// <summary>
        ///   查找类似 查看事件 的本地化字符串。
        /// </summary>
        string ContextMenuCommandShowEvents {
            get;
        }
        
        /// <summary>
        ///   查找类似 Tab 键顺序 的本地化字符串。
        /// </summary>
        string ContextMenuCommandTabOrder {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的代码已被其它窗体元素使用 的本地化字符串。
        /// </summary>
        string FormDesigner_FormPropertyGrid_MessageFormElementCodeExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定代码的窗体已存在 的本地化字符串。
        /// </summary>
        string FormDesigner_FormPropertyGrid_MessageFormEntityExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 事件 的本地化字符串。
        /// </summary>
        string FormDesignerEvents {
            get;
        }
        
        /// <summary>
        ///   查找类似 事件 的本地化字符串。
        /// </summary>
        string FormDesignerEventTree_TabText {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        string FormDesignerEventTree_ToolStripButtonAddEvent {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        string FormDesignerEventTree_ToolStripButtonDeleteEvent {
            get;
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        string FormDesignerEventTree_ToolStripButtonDownEvent {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        string FormDesignerEventTree_ToolStripButtonEditEvent {
            get;
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        string FormDesignerEventTree_ToolStripButtonUpEvent {
            get;
        }
        
        /// <summary>
        ///   查找类似 正在加载,请稍候... 的本地化字符串。
        /// </summary>
        string FormDesignSurfaceHosting_LabelLoadingMsg {
            get;
        }
        
        /// <summary>
        ///   查找类似 正在释放资源,请稍候... 的本地化字符串。
        /// </summary>
        string FormDesignSurfaceHosting_LabelUnloadingMsg {
            get;
        }
        
        /// <summary>
        ///   查找类似 正在处理... 的本地化字符串。
        /// </summary>
        string FormDesignSurfaceHosting_LabelWorkingMsg {
            get;
        }
        
        /// <summary>
        ///   查找类似 保存对窗体 [{0}] 的更改吗? 的本地化字符串。
        /// </summary>
        string FormDesignSurfaceHosting_MessageIsSave {
            get;
        }
        
        /// <summary>
        ///   查找类似 丢弃更改的部分，无法撤销 的本地化字符串。
        /// </summary>
        string FormDesignSurfaceHosting_MessageIsSave_NoButtonDescription {
            get;
        }
        
        /// <summary>
        ///   查找类似 保存更改 的本地化字符串。
        /// </summary>
        string FormDesignSurfaceHosting_MessageIsSave_YesButtonDescription {
            get;
        }
        
        /// <summary>
        ///   查找类似 窗体 [{0}] 的本地化字符串。
        /// </summary>
        string FormDesignSurfaceHosting_TabText {
            get;
        }
        
        /// <summary>
        ///   查找类似 窗体 的本地化字符串。
        /// </summary>
        string FormHostingContainer {
            get;
        }
        
        /// <summary>
        ///   查找类似 底端对齐 的本地化字符串。
        /// </summary>
        string FormHostingContainer_ToolStripButtonAlignBottom {
            get;
        }
        
        /// <summary>
        ///   查找类似 中间对齐 的本地化字符串。
        /// </summary>
        string FormHostingContainer_ToolStripButtonAlignHorizontalCenters {
            get;
        }
        
        /// <summary>
        ///   查找类似 左对齐 的本地化字符串。
        /// </summary>
        string FormHostingContainer_ToolStripButtonAlignLeft {
            get;
        }
        
        /// <summary>
        ///   查找类似 右对齐 的本地化字符串。
        /// </summary>
        string FormHostingContainer_ToolStripButtonAlignRight {
            get;
        }
        
        /// <summary>
        ///   查找类似 顶端对齐 的本地化字符串。
        /// </summary>
        string FormHostingContainer_ToolStripButtonAlignTop {
            get;
        }
        
        /// <summary>
        ///   查找类似 居中对齐 的本地化字符串。
        /// </summary>
        string FormHostingContainer_ToolStripButtonAlignVerticalCenters {
            get;
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        string FormHostingContainer_ToolStripButtonCopy {
            get;
        }
        
        /// <summary>
        ///   查找类似 剪切 的本地化字符串。
        /// </summary>
        string FormHostingContainer_ToolStripButtonCut {
            get;
        }
        
        /// <summary>
        ///   查找类似 粘贴 的本地化字符串。
        /// </summary>
        string FormHostingContainer_ToolStripButtonPaste {
            get;
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        string FormHostingContainer_ToolStripButtonProperty {
            get;
        }
        
        /// <summary>
        ///   查找类似 重复 的本地化字符串。
        /// </summary>
        string FormHostingContainer_ToolStripButtonRedo {
            get;
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        string FormHostingContainer_ToolStripButtonSave {
            get;
        }
        
        /// <summary>
        ///   查找类似 使大小相同 的本地化字符串。
        /// </summary>
        string FormHostingContainer_ToolStripButtonSizeToControl {
            get;
        }
        
        /// <summary>
        ///   查找类似 使高度相同 的本地化字符串。
        /// </summary>
        string FormHostingContainer_ToolStripButtonSizeToControlHeight {
            get;
        }
        
        /// <summary>
        ///   查找类似 使宽度相同 的本地化字符串。
        /// </summary>
        string FormHostingContainer_ToolStripButtonSizeToControlWidth {
            get;
        }
        
        /// <summary>
        ///   查找类似 工具箱 的本地化字符串。
        /// </summary>
        string FormHostingContainer_ToolStripButtonToolbox {
            get;
        }
        
        /// <summary>
        ///   查找类似 撤销 的本地化字符串。
        /// </summary>
        string FormHostingContainer_ToolStripButtonUndo {
            get;
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        string FormHostingContainer_ToolStripMenuItemRefreshWarning {
            get;
        }
        
        /// <summary>
        ///   查找类似 ({0}) 警告 的本地化字符串。
        /// </summary>
        string FormHostingContainer_ToolStripSplitButtonWarning {
            get;
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        string FormMultiSave {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string FormMultiSave_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        string FormMultiSave_ButtonNo {
            get;
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        string FormMultiSave_ButtonYes {
            get;
        }
        
        /// <summary>
        ///   查找类似 保存对以下各项的更改吗? 的本地化字符串。
        /// </summary>
        string FormMultiSave_LabelNotice {
            get;
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        string FormPropertyGrid_TabText {
            get;
        }
        
        /// <summary>
        ///   查找类似 工具箱 的本地化字符串。
        /// </summary>
        string FormToolbox_TabText {
            get;
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        string HostingTabPageContextMenuStrip_Close {
            get;
        }
        
        /// <summary>
        ///   查找类似 关闭所有 的本地化字符串。
        /// </summary>
        string HostingTabPageContextMenuStrip_CloseAll {
            get;
        }
        
        /// <summary>
        ///   查找类似 除此之外全部关闭 的本地化字符串。
        /// </summary>
        string HostingTabPageContextMenuStrip_CloseAllButThis {
            get;
        }
        
        /// <summary>
        ///   查找类似 已保存 的本地化字符串。
        /// </summary>
        string StatusBarMessage_Saved {
            get;
        }
        
        /// <summary>
        ///  Returns true if the current language is the default language.
        /// </summary>
        bool IsDefault {
            get;
        }
    }
}
