//===============================================================================
// Microsoft patterns & practices Enterprise Library
// Logging Application Block
//===============================================================================
// Copyright © Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.Logging.Configuration.Design.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.Logging.Configuration.Design.Properties.Res" +
                            "ources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Events.
        /// </summary>
        internal static string AllTraceSourceNode {
            get {
                return ResourceManager.GetString("AllTraceSourceNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Formatter.
        /// </summary>
        internal static string BinaryFormatterNode {
            get {
                return ResourceManager.GetString("BinaryFormatterNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new binary formatter..
        /// </summary>
        internal static string BinaryFormatterUICommandLongText {
            get {
                return ResourceManager.GetString("BinaryFormatterUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Formatter.
        /// </summary>
        internal static string BinaryFormatterUICommandText {
            get {
                return ResourceManager.GetString("BinaryFormatterUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the cateogory filter expression..
        /// </summary>
        internal static string CategoryFilterExpressionDescription {
            get {
                return ResourceManager.GetString("CategoryFilterExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Filter.
        /// </summary>
        internal static string CategoryFilterNode {
            get {
                return ResourceManager.GetString("CategoryFilterNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow all except.
        /// </summary>
        internal static string CategoryFilterSummaryAllow {
            get {
                return ResourceManager.GetString("CategoryFilterSummaryAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny all except.
        /// </summary>
        internal static string CategoryFilterSummaryDeny {
            get {
                return ResourceManager.GetString("CategoryFilterSummaryDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new Category Filter..
        /// </summary>
        internal static string CategoryFilterUICommandLongText {
            get {
                return ResourceManager.GetString("CategoryFilterUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Filter.
        /// </summary>
        internal static string CategoryFilterUICommandText {
            get {
                return ResourceManager.GetString("CategoryFilterUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string CategoryGeneral {
            get {
                return ResourceManager.GetString("CategoryGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Filter.
        /// </summary>
        internal static string CategoryLogFilterNode {
            get {
                return ResourceManager.GetString("CategoryLogFilterNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Sources.
        /// </summary>
        internal static string CategorySources {
            get {
                return ResourceManager.GetString("CategorySources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string CategoryTraceSourceNode {
            get {
                return ResourceManager.GetString("CategoryTraceSourceNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new category..
        /// </summary>
        internal static string CategoryTraceSourceUICommandLongText {
            get {
                return ResourceManager.GetString("CategoryTraceSourceUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string CategoryTraceSourceUICommandText {
            get {
                return ResourceManager.GetString("CategoryTraceSourceUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Filter.
        /// </summary>
        internal static string CustomFilterNode {
            get {
                return ResourceManager.GetString("CustomFilterNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Formatter.
        /// </summary>
        internal static string CustomFormatter {
            get {
                return ResourceManager.GetString("CustomFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom configuration properties for this Formatter..
        /// </summary>
        internal static string CustomFormatterAttributesDescription {
            get {
                return ResourceManager.GetString("CustomFormatterAttributesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new custom formatter..
        /// </summary>
        internal static string CustomFormatterUICommandLongText {
            get {
                return ResourceManager.GetString("CustomFormatterUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Formatter.
        /// </summary>
        internal static string CustomFormatterUICommandText {
            get {
                return ResourceManager.GetString("CustomFormatterUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new Custom Filter..
        /// </summary>
        internal static string CustomLogFilterUICommandLongText {
            get {
                return ResourceManager.GetString("CustomLogFilterUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Filter.
        /// </summary>
        internal static string CustomLogFilterUICommandText {
            get {
                return ResourceManager.GetString("CustomLogFilterUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Trace Listener.
        /// </summary>
        internal static string CustomTraceListenerNode {
            get {
                return ResourceManager.GetString("CustomTraceListenerNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of CustomTraceListener. Required..
        /// </summary>
        internal static string CustomTraceListenerNodeTypeDescription {
            get {
                return ResourceManager.GetString("CustomTraceListenerNodeTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new Custom Trace Listener..
        /// </summary>
        internal static string CustomTraceListenerUICommandLongText {
            get {
                return ResourceManager.GetString("CustomTraceListenerUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Trace Listener.
        /// </summary>
        internal static string CustomTraceListenerUICommandText {
            get {
                return ResourceManager.GetString("CustomTraceListenerUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string DefaultCategory {
            get {
                return ResourceManager.GetString("DefaultCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category to use if a category is not defined or is misspelled.
        /// </summary>
        internal static string DefaultCategoryDescription {
            get {
                return ResourceManager.GetString("DefaultCategoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Formatter.
        /// </summary>
        internal static string DefaultFormatter {
            get {
                return ResourceManager.GetString("DefaultFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default SourceLevels for this TraceSource.
        /// </summary>
        internal static string DefaultLevelDescription {
            get {
                return ResourceManager.GetString("DefaultLevelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp: {timestamp}
        ///Message: {message}
        ///Category: {category}
        ///Priority: {priority}
        ///EventId: {eventid}
        ///Severity: {severity}
        ///Title:{title}
        ///Machine: {machine}
        ///Application Domain: {appDomain}
        ///Process Id: {processId}
        ///Process Name: {processName}
        ///Win32 Thread Id: {win32ThreadId}
        ///Thread Name: {threadName}
        ///Extended Properties: {dictionary({key} - {value}
        ///)}.
        /// </summary>
        internal static string DefaultTextFormat {
            get {
                return ResourceManager.GetString("DefaultTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From email address.
        /// </summary>
        internal static string EmailTraceListenerFromAddressDescription {
            get {
                return ResourceManager.GetString("EmailTraceListenerFromAddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email TraceListener.
        /// </summary>
        internal static string EmailTraceListenerNode {
            get {
                return ResourceManager.GetString("EmailTraceListenerNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP server to send emails.
        /// </summary>
        internal static string EmailTraceListenerSmtpServerDescription {
            get {
                return ResourceManager.GetString("EmailTraceListenerSmtpServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard text to be added to the message subject after log message severity.
        /// </summary>
        internal static string EmailTraceListenerSubjectLineEnderDescription {
            get {
                return ResourceManager.GetString("EmailTraceListenerSubjectLineEnderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard text to be added to the message subject before log message severity.
        /// </summary>
        internal static string EmailTraceListenerSubjectLineStarterDescription {
            get {
                return ResourceManager.GetString("EmailTraceListenerSubjectLineStarterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more email addresses separated by semicolons.
        /// </summary>
        internal static string EmailTraceListenerToAddressDescription {
            get {
                return ResourceManager.GetString("EmailTraceListenerToAddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new Email Trace Listener..
        /// </summary>
        internal static string EmailTraceListenerUICommandLongText {
            get {
                return ResourceManager.GetString("EmailTraceListenerUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Trace Listener.
        /// </summary>
        internal static string EmailTraceListenerUICommandText {
            get {
                return ResourceManager.GetString("EmailTraceListenerUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting this value to true lets all LogEntries to pass, false will not let any LogEntries pass..
        /// </summary>
        internal static string EnabledDescription {
            get {
                return ResourceManager.GetString("EnabledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Errors &amp; Warnings.
        /// </summary>
        internal static string ErrorsTraceSourceNode {
            get {
                return ResourceManager.GetString("ErrorsTraceSourceNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event log name.  Optional - defaults to Application log..
        /// </summary>
        internal static string EventLogTraceListenerEventLogNameDescription {
            get {
                return ResourceManager.GetString("EventLogTraceListenerEventLogNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event source name..
        /// </summary>
        internal static string EventLogTraceListenerSourceNameDescription {
            get {
                return ResourceManager.GetString("EventLogTraceListenerSourceNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName.
        /// </summary>
        internal static string FileNameDescription {
            get {
                return ResourceManager.GetString("FileNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string FilterCollectionNodeName {
            get {
                return ResourceManager.GetString("FilterCollectionNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        internal static string FlatFileTraceListenerFileDialogFilter {
            get {
                return ResourceManager.GetString("FlatFileTraceListenerFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name and directory..
        /// </summary>
        internal static string FlatFileTraceListenerFileName {
            get {
                return ResourceManager.GetString("FlatFileTraceListenerFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer to append after each log entry.  Optional..
        /// </summary>
        internal static string FlatFileTraceListenerFooter {
            get {
                return ResourceManager.GetString("FlatFileTraceListenerFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header to append before each log entry.  Optional..
        /// </summary>
        internal static string FlatFileTraceListenerHeader {
            get {
                return ResourceManager.GetString("FlatFileTraceListenerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlatFile TraceListener.
        /// </summary>
        internal static string FlatFileTraceListenerNode {
            get {
                return ResourceManager.GetString("FlatFileTraceListenerNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new Flat File Trace Listener..
        /// </summary>
        internal static string FlatFileTraceListenerUICommandLongText {
            get {
                return ResourceManager.GetString("FlatFileTraceListenerUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat File Trace Listener.
        /// </summary>
        internal static string FlatFileTraceListenerUICommandText {
            get {
                return ResourceManager.GetString("FlatFileTraceListenerUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination format.  Optional..
        /// </summary>
        internal static string FormatDescription {
            get {
                return ResourceManager.GetString("FormatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted EventLog TraceListener.
        /// </summary>
        internal static string FormattedEventLogTraceListenerNode {
            get {
                return ResourceManager.GetString("FormattedEventLogTraceListenerNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new Formatted Event Log Trace Listener..
        /// </summary>
        internal static string FormattedEventLogTraceListenerUICommandLongText {
            get {
                return ResourceManager.GetString("FormattedEventLogTraceListenerUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted Event Log Trace Listener.
        /// </summary>
        internal static string FormattedEventLogTraceListenerUICommandText {
            get {
                return ResourceManager.GetString("FormattedEventLogTraceListenerUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatters.
        /// </summary>
        internal static string Formatters {
            get {
                return ResourceManager.GetString("Formatters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new {0}.
        /// </summary>
        internal static string GenericCreateStatusText {
            get {
                return ResourceManager.GetString("GenericCreateStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initData for this System.Diagnostics TraceListener.
        /// </summary>
        internal static string InitDataDescription {
            get {
                return ResourceManager.GetString("InitDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Behavior.
        /// </summary>
        internal static string LockBehaviorDescription {
            get {
                return ResourceManager.GetString("LockBehaviorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogEnabled Filter.
        /// </summary>
        internal static string LogEnabledFilterNode {
            get {
                return ResourceManager.GetString("LogEnabledFilterNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new Log Enabled Filter..
        /// </summary>
        internal static string LogEnabledFilterUICommandLongText {
            get {
                return ResourceManager.GetString("LogEnabledFilterUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Enabled Filter.
        /// </summary>
        internal static string LogEnabledFilterUICommandText {
            get {
                return ResourceManager.GetString("LogEnabledFilterUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the Logging Application Block..
        /// </summary>
        internal static string LogSettingsCommandLongText {
            get {
                return ResourceManager.GetString("LogSettingsCommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Application Block.
        /// </summary>
        internal static string LogSettingsCommandText {
            get {
                return ResourceManager.GetString("LogSettingsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Application Block.
        /// </summary>
        internal static string LogSettingsNode {
            get {
                return ResourceManager.GetString("LogSettingsNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogEntries that have a priority greater than this value do not pass the filter .
        /// </summary>
        internal static string MaximumPriorityDescription {
            get {
                return ResourceManager.GetString("MaximumPriorityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for MaximumPriority should be greater than the value for MinimumPriority.
        /// </summary>
        internal static string MaxPrioShouldBeGreaterThanMinPrioError {
            get {
                return ResourceManager.GetString("MaxPrioShouldBeGreaterThanMinPrioError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The priority of messages written to MSMQ.
        /// </summary>
        internal static string MessagePriorityDescription {
            get {
                return ResourceManager.GetString("MessagePriorityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum message priority to be delivered.
        /// </summary>
        internal static string MinimumPriority {
            get {
                return ResourceManager.GetString("MinimumPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogEntries that have a priority lower than this value do not pass the filter .
        /// </summary>
        internal static string MinimumPriorityDescription {
            get {
                return ResourceManager.GetString("MinimumPriorityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private or public message queue path.
        /// </summary>
        internal static string MsmqPathDescription {
            get {
                return ResourceManager.GetString("MsmqPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A priority for the message when sent to the queue..
        /// </summary>
        internal static string MsmqSinkMessagePriorityDescription {
            get {
                return ResourceManager.GetString("MsmqSinkMessagePriorityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private or public message queue.
        /// </summary>
        internal static string MsmqSinkQueuePathDescription {
            get {
                return ResourceManager.GetString("MsmqSinkQueuePathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSMQ Sink.
        /// </summary>
        internal static string MsmqTraceListener {
            get {
                return ResourceManager.GetString("MsmqTraceListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Msmq TraceListener.
        /// </summary>
        internal static string MsmqTraceListenerNode {
            get {
                return ResourceManager.GetString("MsmqTraceListenerNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new Msmq Trace Listener..
        /// </summary>
        internal static string MsmqTraceListenerUICommandLongText {
            get {
                return ResourceManager.GetString("MsmqTraceListenerUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Msmq Trace Listener.
        /// </summary>
        internal static string MsmqTraceListenerUICommandText {
            get {
                return ResourceManager.GetString("MsmqTraceListenerUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority Filter.
        /// </summary>
        internal static string PriorityFilterNode {
            get {
                return ResourceManager.GetString("PriorityFilterNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new priority filter..
        /// </summary>
        internal static string PriorityFilterUICommandLongText {
            get {
                return ResourceManager.GetString("PriorityFilterUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority Filter.
        /// </summary>
        internal static string PriorityFilterUICommandText {
            get {
                return ResourceManager.GetString("PriorityFilterUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MSMQ path that is used to write LogEntries.
        /// </summary>
        internal static string QueuePathDescription {
            get {
                return ResourceManager.GetString("QueuePathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer interval for the distributor service to check MSMQ for new messages.
        /// </summary>
        internal static string QueueTimerIntervalDescription {
            get {
                return ResourceManager.GetString("QueueTimerIntervalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A boolean that indicates whether MSMQ messages written by this TraceListener are recoverable.
        /// </summary>
        internal static string RecoverableDescription {
            get {
                return ResourceManager.GetString("RecoverableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reference to TraceListener {0} already exists for this source..
        /// </summary>
        internal static string ReferenceAlreadyExists {
            get {
                return ResourceManager.GetString("ReferenceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert impersonation temporarily while logging..
        /// </summary>
        internal static string RevertImpersonationDescription {
            get {
                return ResourceManager.GetString("RevertImpersonationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exists Behavior.
        /// </summary>
        internal static string RollFileExistsBehaviorDescription {
            get {
                return ResourceManager.GetString("RollFileExistsBehaviorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling Flat File Trace Listener.
        /// </summary>
        internal static string RollingTraceListenerNodeUICommandLongText {
            get {
                return ResourceManager.GetString("RollingTraceListenerNodeUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling Flat File Trace Listener.
        /// </summary>
        internal static string RollingTraceListenerNodeUICommandText {
            get {
                return ResourceManager.GetString("RollingTraceListenerNodeUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll Interval.
        /// </summary>
        internal static string RollIntervalDescription {
            get {
                return ResourceManager.GetString("RollIntervalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll Size KB.
        /// </summary>
        internal static string RollSizeKBDescription {
            get {
                return ResourceManager.GetString("RollSizeKBDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Sources.
        /// </summary>
        internal static string SpecialTraceSourcesNodeName {
            get {
                return ResourceManager.GetString("SpecialTraceSourcesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Diagnostics TraceListener.
        /// </summary>
        internal static string SystemDiagnosticsTraceListenerNode {
            get {
                return ResourceManager.GetString("SystemDiagnosticsTraceListenerNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of TraceListener.
        /// </summary>
        internal static string SystemDiagnosticsTraceListenerTypeDescription {
            get {
                return ResourceManager.GetString("SystemDiagnosticsTraceListenerTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new System Diagnostics Trace Listener..
        /// </summary>
        internal static string SystemDiagnosticsTraceListenerUICommandLongText {
            get {
                return ResourceManager.GetString("SystemDiagnosticsTraceListenerUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Diagnostics Trace Listener.
        /// </summary>
        internal static string SystemDiagnosticsTraceListenerUICommandText {
            get {
                return ResourceManager.GetString("SystemDiagnosticsTraceListenerUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;template&gt;.
        /// </summary>
        internal static string TemplatePlaceHolder {
            get {
                return ResourceManager.GetString("TemplatePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Formatter.
        /// </summary>
        internal static string TextFormatterNode {
            get {
                return ResourceManager.GetString("TextFormatterNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new text formatter..
        /// </summary>
        internal static string TextFormatterUICommandLongText {
            get {
                return ResourceManager.GetString("TextFormatterUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Formatter.
        /// </summary>
        internal static string TextFormatterUICommandText {
            get {
                return ResourceManager.GetString("TextFormatterUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeStampt.
        /// </summary>
        internal static string TimeStampPatternDescription {
            get {
                return ResourceManager.GetString("TimeStampPatternDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum time for a message to have been received by the message queue.
        /// </summary>
        internal static string TimeToBeReceivedDescription {
            get {
                return ResourceManager.GetString("TimeToBeReceivedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Listeners.
        /// </summary>
        internal static string TraceListenerCollectionNode {
            get {
                return ResourceManager.GetString("TraceListenerCollectionNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TraceListener Reference.
        /// </summary>
        internal static string TraceListenerReferenceNode {
            get {
                return ResourceManager.GetString("TraceListenerReferenceNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new Trace Listener Reference..
        /// </summary>
        internal static string TraceListenerReferenceUICommandLongText {
            get {
                return ResourceManager.GetString("TraceListenerReferenceUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Listener Reference.
        /// </summary>
        internal static string TraceListenerReferenceUICommandText {
            get {
                return ResourceManager.GetString("TraceListenerReferenceUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace output options.
        /// </summary>
        internal static string TraceOutputOptionsDescription {
            get {
                return ResourceManager.GetString("TraceOutputOptionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string TraceSourceCategoryGeneral {
            get {
                return ResourceManager.GetString("TraceSourceCategoryGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of transaction used for writing messages to MSMQ.
        /// </summary>
        internal static string TransactionTypeDescription {
            get {
                return ResourceManager.GetString("TransactionTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unprocessed Category.
        /// </summary>
        internal static string UnprocessedTraceSourceNode {
            get {
                return ResourceManager.GetString("UnprocessedTraceSourceNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A boolean that indicates whether the TraceListener should authenticate against MSMQ.
        /// </summary>
        internal static string UseAuthenticationDescription {
            get {
                return ResourceManager.GetString("UseAuthenticationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A boolean that indicates whether the deadletter queue should be used.
        /// </summary>
        internal static string UseDeadLetterQueueDescription {
            get {
                return ResourceManager.GetString("UseDeadLetterQueueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A boolean that indicates whether messages written to the MSMQ should be encrypted.
        /// </summary>
        internal static string UseEncryptionDescription {
            get {
                return ResourceManager.GetString("UseEncryptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMI TraceListener.
        /// </summary>
        internal static string WmiTraceListenerNode {
            get {
                return ResourceManager.GetString("WmiTraceListenerNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new WMI Trace Listener..
        /// </summary>
        internal static string WmiTraceListenerUICommandLongText {
            get {
                return ResourceManager.GetString("WmiTraceListenerUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMI Trace Listener.
        /// </summary>
        internal static string WmiTraceListenerUICommandText {
            get {
                return ResourceManager.GetString("WmiTraceListenerUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        internal static string XmlTraceListenerFileDialogFilter {
            get {
                return ResourceManager.GetString("XmlTraceListenerFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Trace Listener.
        /// </summary>
        internal static string XmlTraceListenerNodeUICommandLongText {
            get {
                return ResourceManager.GetString("XmlTraceListenerNodeUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Trace Listener.
        /// </summary>
        internal static string XmlTraceListenerNodeUICommandText {
            get {
                return ResourceManager.GetString("XmlTraceListenerNodeUICommandText", resourceCulture);
            }
        }
    }
}
