//===============================================================================
// Microsoft patterns & practices Enterprise Library
// Data Access Application Block
//===============================================================================
// Copyright © Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.Data.Configuration.Design.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.Data.Configuration.Design.Properties.Resour" +
                            "ces", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string CategoryGeneral {
            get {
                return ResourceManager.GetString("CategoryGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the connection string..
        /// </summary>
        internal static string ConnectionStringDescription {
            get {
                return ResourceManager.GetString("ConnectionStringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection String.
        /// </summary>
        internal static string ConnectionStringNodeDefaultName {
            get {
                return ResourceManager.GetString("ConnectionStringNodeDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Strings.
        /// </summary>
        internal static string ConnectionStringsNodeName {
            get {
                return ResourceManager.GetString("ConnectionStringsNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add connection strings.
        /// </summary>
        internal static string ConnectionStringsUICommandLongText {
            get {
                return ResourceManager.GetString("ConnectionStringsUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Strings.
        /// </summary>
        internal static string ConnectionStringsUICommandText {
            get {
                return ResourceManager.GetString("ConnectionStringsUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a connection string.
        /// </summary>
        internal static string ConnectionStringUICommandLongText {
            get {
                return ResourceManager.GetString("ConnectionStringUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection String.
        /// </summary>
        internal static string ConnectionStringUICommandText {
            get {
                return ResourceManager.GetString("ConnectionStringUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the database..
        /// </summary>
        internal static string DatabaseTypeFullyQualifedNameDescription {
            get {
                return ResourceManager.GetString("DatabaseTypeFullyQualifedNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Access Application Block.
        /// </summary>
        internal static string DataSectionNodeName {
            get {
                return ResourceManager.GetString("DataSectionNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the Data Access Application Block.
        /// </summary>
        internal static string DataUICommandLongText {
            get {
                return ResourceManager.GetString("DataUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Access Application Block.
        /// </summary>
        internal static string DataUICommandText {
            get {
                return ResourceManager.GetString("DataUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the default database connection string..
        /// </summary>
        internal static string DefaultDatabaseDescription {
            get {
                return ResourceManager.GetString("DefaultDatabaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string DefaultParameterNodeName {
            get {
                return ResourceManager.GetString("DefaultParameterNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package for connection string {0} will not be loaded. The connection string is missing..
        /// </summary>
        internal static string ExceptionConnectionStringMissing {
            get {
                return ResourceManager.GetString("ExceptionConnectionStringMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Connection Strings or not loaded or are missing from configuration..
        /// </summary>
        internal static string ExceptionMissingConnectionStrings {
            get {
                return ResourceManager.GetString("ExceptionMissingConnectionStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle Package.
        /// </summary>
        internal static string OracleConnectionElementNodeName {
            get {
                return ResourceManager.GetString("OracleConnectionElementNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Oracle package information for the connection string.
        /// </summary>
        internal static string OracleConnectionUICommandLongText {
            get {
                return ResourceManager.GetString("OracleConnectionUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle Packages.
        /// </summary>
        internal static string OracleConnectionUICommandText {
            get {
                return ResourceManager.GetString("OracleConnectionUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle Packages.
        /// </summary>
        internal static string OraclePackagesNodeName {
            get {
                return ResourceManager.GetString("OraclePackagesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an Oracle package definition.
        /// </summary>
        internal static string OraclePackageUICommandLongText {
            get {
                return ResourceManager.GetString("OraclePackageUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle Package.
        /// </summary>
        internal static string OraclePackageUICommandText {
            get {
                return ResourceManager.GetString("OraclePackageUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the preifix used for the oracle objects..
        /// </summary>
        internal static string PrefixDescription {
            get {
                return ResourceManager.GetString("PrefixDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Provider Mappings.
        /// </summary>
        internal static string ProviderMappingsNodeName {
            get {
                return ResourceManager.GetString("ProviderMappingsNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a custom provider mapping.
        /// </summary>
        internal static string ProviderMappingUICommandLongText {
            get {
                return ResourceManager.GetString("ProviderMappingUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Mapping.
        /// </summary>
        internal static string ProviderMappingUICommandText {
            get {
                return ResourceManager.GetString("ProviderMappingUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the provider name for the connection string..
        /// </summary>
        internal static string ProviderNameDescription {
            get {
                return ResourceManager.GetString("ProviderNameDescription", resourceCulture);
            }
        }
    }
}
