//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5446
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheng.SailingEase.Components.DataEntityComponent.Localisation {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Chinese__Simplified_ : ILanguage {
        
        private global::System.Resources.ResourceManager resourceMan;
        
        private global::System.Globalization.CultureInfo resourceCulture;
        
        public Chinese__Simplified_() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sheng.SailingEase.Components.DataEntityComponent.Localisation.Chinese (Simplified" +
                            ")", typeof(Chinese__Simplified_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.Globalization.CultureInfo Culture {
            get {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    global::System.Globalization.CultureInfo temp = new global::System.Globalization.CultureInfo("zh-CHS");
                    resourceCulture = temp;
                }
                return resourceCulture;
            }
        }
        
        /// <summary>
        ///   查找类似 请先设置数据源。 的本地化字符串。
        /// </summary>
        public string DataBaseCreateWizard_DataBaseName_MessageConnectionStringSettingsIsNull {
            get {
                return ResourceManager.GetString("DataBaseCreateWizard_DataBaseName_MessageConnectionStringSettingsIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 枚举 的本地化字符串。
        /// </summary>
        public string DataEntity_Enum {
            get {
                return ResourceManager.GetString("DataEntity_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 枚举代码 的本地化字符串。
        /// </summary>
        public string DataEntity_Enum_EnumKey {
            get {
                return ResourceManager.GetString("DataEntity_Enum_EnumKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        public string DataEntity_Enum_Sort {
            get {
                return ResourceManager.GetString("DataEntity_Enum_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本 的本地化字符串。
        /// </summary>
        public string DataEntity_Enum_Text {
            get {
                return ResourceManager.GetString("DataEntity_Enum_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        public string DataEntity_Enum_Value {
            get {
                return ResourceManager.GetString("DataEntity_Enum_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public string DataEntity_User {
            get {
                return ResourceManager.GetString("DataEntity_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组标识 的本地化字符串。
        /// </summary>
        public string DataEntity_User_GroupId {
            get {
                return ResourceManager.GetString("DataEntity_User_GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后登陆时间 的本地化字符串。
        /// </summary>
        public string DataEntity_User_LastLoginTime {
            get {
                return ResourceManager.GetString("DataEntity_User_LastLoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录名 的本地化字符串。
        /// </summary>
        public string DataEntity_User_LoginName {
            get {
                return ResourceManager.GetString("DataEntity_User_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public string DataEntity_User_Name {
            get {
                return ResourceManager.GetString("DataEntity_User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public string DataEntity_User_Password {
            get {
                return ResourceManager.GetString("DataEntity_User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户组 的本地化字符串。
        /// </summary>
        public string DataEntity_UserGroup {
            get {
                return ResourceManager.GetString("DataEntity_UserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组名 的本地化字符串。
        /// </summary>
        public string DataEntity_UserGroup_Name {
            get {
                return ResourceManager.GetString("DataEntity_UserGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脚本 的本地化字符串。
        /// </summary>
        public string DataEntityCreateSqlView_TabText {
            get {
                return ResourceManager.GetString("DataEntityCreateSqlView_TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据实体 的本地化字符串。
        /// </summary>
        public string DataEntityEditView {
            get {
                return ResourceManager.GetString("DataEntityEditView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public string DataEntityEditView_ButtonCancel {
            get {
                return ResourceManager.GetString("DataEntityEditView_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public string DataEntityEditView_ButtonOK {
            get {
                return ResourceManager.GetString("DataEntityEditView_ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        public string DataEntityEditView_LabelCode {
            get {
                return ResourceManager.GetString("DataEntityEditView_LabelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体名 的本地化字符串。
        /// </summary>
        public string DataEntityEditView_LabelDataEntityName {
            get {
                return ResourceManager.GetString("DataEntityEditView_LabelDataEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定代码的数据实体已存在 的本地化字符串。
        /// </summary>
        public string DataEntityEditView_MessageDataEntityCodeExist {
            get {
                return ResourceManager.GetString("DataEntityEditView_MessageDataEntityCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        public string DataEntityEditView_TabPageGeneral {
            get {
                return ResourceManager.GetString("DataEntityEditView_TabPageGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public string DataEntityEditView_TabPageRemark {
            get {
                return ResourceManager.GetString("DataEntityEditView_TabPageRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据实体 的本地化字符串。
        /// </summary>
        public string DataEntityView_TabText {
            get {
                return ResourceManager.GetString("DataEntityView_TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据项 的本地化字符串。
        /// </summary>
        public string DataItemEditView {
            get {
                return ResourceManager.GetString("DataItemEditView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public string DataItemEditView_ButtonCancel {
            get {
                return ResourceManager.GetString("DataItemEditView_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public string DataItemEditView_ButtonOK {
            get {
                return ResourceManager.GetString("DataItemEditView_ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许空 的本地化字符串。
        /// </summary>
        public string DataItemEditView_CheckBoxAllowEmpty {
            get {
                return ResourceManager.GetString("DataItemEditView_CheckBoxAllowEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保持数据唯一 的本地化字符串。
        /// </summary>
        public string DataItemEditView_CheckBoxExclusive {
            get {
                return ResourceManager.GetString("DataItemEditView_CheckBoxExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定代码的数据项已存在 的本地化字符串。
        /// </summary>
        public string DataItemEditView_DataEntityItemCodeExist {
            get {
                return ResourceManager.GetString("DataItemEditView_DataEntityItemCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        public string DataItemEditView_LabelCode {
            get {
                return ResourceManager.GetString("DataItemEditView_LabelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据类型 的本地化字符串。
        /// </summary>
        public string DataItemEditView_LabelDataType {
            get {
                return ResourceManager.GetString("DataItemEditView_LabelDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小数位数 的本地化字符串。
        /// </summary>
        public string DataItemEditView_LabelDecimalDigits {
            get {
                return ResourceManager.GetString("DataItemEditView_LabelDecimalDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认值 的本地化字符串。
        /// </summary>
        public string DataItemEditView_LabelDefaultValue {
            get {
                return ResourceManager.GetString("DataItemEditView_LabelDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度 的本地化字符串。
        /// </summary>
        public string DataItemEditView_LabelLength {
            get {
                return ResourceManager.GetString("DataItemEditView_LabelLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据项名 的本地化字符串。
        /// </summary>
        public string DataItemEditView_LabelName {
            get {
                return ResourceManager.GetString("DataItemEditView_LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或指定为 &quot;MAX&quot;。 的本地化字符串。
        /// </summary>
        public string DataItemEditView_MessageLengthOrMax {
            get {
                return ResourceManager.GetString("DataItemEditView_MessageLengthOrMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度范围应在 {0} 至 {1} 之间。 的本地化字符串。
        /// </summary>
        public string DataItemEditView_MessageLengthOutOfRange {
            get {
                return ResourceManager.GetString("DataItemEditView_MessageLengthOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        public string DataItemEditView_TabPageGeneral {
            get {
                return ResourceManager.GetString("DataItemEditView_TabPageGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public string DataItemEditView_TabPageRemark {
            get {
                return ResourceManager.GetString("DataItemEditView_TabPageRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        public string GridViewController_DataEntityColumns_Code {
            get {
                return ResourceManager.GetString("GridViewController_DataEntityColumns_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体名 的本地化字符串。
        /// </summary>
        public string GridViewController_DataEntityColumns_Name {
            get {
                return ResourceManager.GetString("GridViewController_DataEntityColumns_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许空 的本地化字符串。
        /// </summary>
        public string GridViewController_DataItemEntityColumns_AllowEmpty {
            get {
                return ResourceManager.GetString("GridViewController_DataItemEntityColumns_AllowEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        public string GridViewController_DataItemEntityColumns_Code {
            get {
                return ResourceManager.GetString("GridViewController_DataItemEntityColumns_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认值 的本地化字符串。
        /// </summary>
        public string GridViewController_DataItemEntityColumns_DefaultValue {
            get {
                return ResourceManager.GetString("GridViewController_DataItemEntityColumns_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度 的本地化字符串。
        /// </summary>
        public string GridViewController_DataItemEntityColumns_Length {
            get {
                return ResourceManager.GetString("GridViewController_DataItemEntityColumns_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体名 的本地化字符串。
        /// </summary>
        public string GridViewController_DataItemEntityColumns_Name {
            get {
                return ResourceManager.GetString("GridViewController_DataItemEntityColumns_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据类型 的本地化字符串。
        /// </summary>
        public string GridViewController_DataItemEntityColumns_TypeName {
            get {
                return ResourceManager.GetString("GridViewController_DataItemEntityColumns_TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public string GridViewMenuDataEntity_Add {
            get {
                return ResourceManager.GetString("GridViewMenuDataEntity_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建脚本 的本地化字符串。
        /// </summary>
        public string GridViewMenuDataEntity_CreateSql {
            get {
                return ResourceManager.GetString("GridViewMenuDataEntity_CreateSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public string GridViewMenuDataEntity_Delete {
            get {
                return ResourceManager.GetString("GridViewMenuDataEntity_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public string GridViewMenuDataEntity_Edit {
            get {
                return ResourceManager.GetString("GridViewMenuDataEntity_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public string GridViewMenuDataItemEntity_Add {
            get {
                return ResourceManager.GetString("GridViewMenuDataItemEntity_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public string GridViewMenuDataItemEntity_Delete {
            get {
                return ResourceManager.GetString("GridViewMenuDataItemEntity_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public string GridViewMenuDataItemEntity_Edit {
            get {
                return ResourceManager.GetString("GridViewMenuDataItemEntity_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库生成向导 的本地化字符串。
        /// </summary>
        public string Navigation_Menu_DataBaseCreateWizard {
            get {
                return ResourceManager.GetString("Navigation_Menu_DataBaseCreateWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据实体 的本地化字符串。
        /// </summary>
        public string Navigation_Menu_DataEntity {
            get {
                return ResourceManager.GetString("Navigation_Menu_DataEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据实体 的本地化字符串。
        /// </summary>
        public string Navigation_ToolStrip_DataEntity {
            get {
                return ResourceManager.GetString("Navigation_ToolStrip_DataEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据实体 的本地化字符串。
        /// </summary>
        public string NavigationTreeController_DataEntity {
            get {
                return ResourceManager.GetString("NavigationTreeController_DataEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        public string NavigationTreeView {
            get {
                return ResourceManager.GetString("NavigationTreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        public string PropertyGridView {
            get {
                return ResourceManager.GetString("PropertyGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定代码的数据实体已存在 的本地化字符串。
        /// </summary>
        public string PropertyGridView_MessageDataEntityCodeExist {
            get {
                return ResourceManager.GetString("PropertyGridView_MessageDataEntityCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定代码的数据项已存在 的本地化字符串。
        /// </summary>
        public string PropertyGridView_MessageDataItemEntityCodeExist {
            get {
                return ResourceManager.GetString("PropertyGridView_MessageDataItemEntityCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public string ToolStripGeneral_Add {
            get {
                return ResourceManager.GetString("ToolStripGeneral_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建脚本 的本地化字符串。
        /// </summary>
        public string ToolStripGeneral_CreateSql {
            get {
                return ResourceManager.GetString("ToolStripGeneral_CreateSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public string ToolStripGeneral_Delete {
            get {
                return ResourceManager.GetString("ToolStripGeneral_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public string ToolStripGeneral_Edit {
            get {
                return ResourceManager.GetString("ToolStripGeneral_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public string TreeMenuDataEntity_Add {
            get {
                return ResourceManager.GetString("TreeMenuDataEntity_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加数据项 的本地化字符串。
        /// </summary>
        public string TreeMenuDataEntity_AddItem {
            get {
                return ResourceManager.GetString("TreeMenuDataEntity_AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建脚本 的本地化字符串。
        /// </summary>
        public string TreeMenuDataEntity_CreateSql {
            get {
                return ResourceManager.GetString("TreeMenuDataEntity_CreateSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public string TreeMenuDataEntity_Delete {
            get {
                return ResourceManager.GetString("TreeMenuDataEntity_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public string TreeMenuDataEntity_Edit {
            get {
                return ResourceManager.GetString("TreeMenuDataEntity_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public string TreeMenuDataEntityFolder_Add {
            get {
                return ResourceManager.GetString("TreeMenuDataEntityFolder_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public string TreeMenuDataItemEntity_Add {
            get {
                return ResourceManager.GetString("TreeMenuDataItemEntity_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public string TreeMenuDataItemEntity_Delete {
            get {
                return ResourceManager.GetString("TreeMenuDataItemEntity_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public string TreeMenuDataItemEntity_Edit {
            get {
                return ResourceManager.GetString("TreeMenuDataItemEntity_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示密码 的本地化字符串。
        /// </summary>
        public string UserControlCreateDataBaseWizardStepAccount_CheckBoxNoPasswordChar {
            get {
                return ResourceManager.GetString("UserControlCreateDataBaseWizardStepAccount_CheckBoxNoPasswordChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此帐户用以登录系统,并且具有最高管理员权限 的本地化字符串。
        /// </summary>
        public string UserControlCreateDataBaseWizardStepAccount_Description {
            get {
                return ResourceManager.GetString("UserControlCreateDataBaseWizardStepAccount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帐户 的本地化字符串。
        /// </summary>
        public string UserControlCreateDataBaseWizardStepAccount_LabelAccount {
            get {
                return ResourceManager.GetString("UserControlCreateDataBaseWizardStepAccount_LabelAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认管理员帐户 的本地化字符串。
        /// </summary>
        public string UserControlCreateDataBaseWizardStepAccount_LabelDefaultAdminAccount {
            get {
                return ResourceManager.GetString("UserControlCreateDataBaseWizardStepAccount_LabelDefaultAdminAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public string UserControlCreateDataBaseWizardStepAccount_LabelPassword {
            get {
                return ResourceManager.GetString("UserControlCreateDataBaseWizardStepAccount_LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有关生成数据库的所有准备工作已经就绪,单击按钮 &quot;下一步&quot; 开始生成 的本地化字符串。
        /// </summary>
        public string UserControlCreateDataBaseWizardStepConfirm_LabelDescription {
            get {
                return ResourceManager.GetString("UserControlCreateDataBaseWizardStepConfirm_LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成数据库 的本地化字符串。
        /// </summary>
        public string UserControlCreateDataBaseWizardStepCreate_LabelCreate {
            get {
                return ResourceManager.GetString("UserControlCreateDataBaseWizardStepCreate_LabelCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        public string UserControlCreateDataBaseWizardStepCreate_LabelFailure {
            get {
                return ResourceManager.GetString("UserControlCreateDataBaseWizardStepCreate_LabelFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成! 的本地化字符串。
        /// </summary>
        public string UserControlCreateDataBaseWizardStepDone_LabelDone {
            get {
                return ResourceManager.GetString("UserControlCreateDataBaseWizardStepDone_LabelDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库名 的本地化字符串。
        /// </summary>
        public string UserControlCreateDataBaseWizardStepEnterDataBaseName_LabelDataBaseName {
            get {
                return ResourceManager.GetString("UserControlCreateDataBaseWizardStepEnterDataBaseName_LabelDataBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成完毕后将枚举写入枚举表 的本地化字符串。
        /// </summary>
        public string UserControlCreateDataBaseWizardStepOption_CheckBoxInsertEnum {
            get {
                return ResourceManager.GetString("UserControlCreateDataBaseWizardStepOption_CheckBoxInsertEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅在指定的数据库中创建数据库对象,而不尝试创建数据库 的本地化字符串。
        /// </summary>
        public string UserControlCreateDataBaseWizardStepOption_CheckBoxNoCreateDataBase {
            get {
                return ResourceManager.GetString("UserControlCreateDataBaseWizardStepOption_CheckBoxNoCreateDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能覆盖任何已存在的数据库或数据库对象 的本地化字符串。
        /// </summary>
        public string UserControlCreateDataBaseWizardStepOption_Description {
            get {
                return ResourceManager.GetString("UserControlCreateDataBaseWizardStepOption_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (应在您已手动建立数据库的情况下使用) 的本地化字符串。
        /// </summary>
        public string UserControlCreateDataBaseWizardStepOption_LabelNoCreateDataBaseDescription {
            get {
                return ResourceManager.GetString("UserControlCreateDataBaseWizardStepOption_LabelNoCreateDataBaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项 的本地化字符串。
        /// </summary>
        public string UserControlCreateDataBaseWizardStepOption_LabelOption {
            get {
                return ResourceManager.GetString("UserControlCreateDataBaseWizardStepOption_LabelOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///  Returns true if the current language is the default language.
        /// </summary>
        public bool IsDefault {
            get {
                return true;
            }
        }
        
        /// <summary>
        ///  Returns a System.String that represents the current System.Object.
        /// </summary>
        public override string ToString() {
            return Culture.EnglishName;
        }
    }
}
