//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5446
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheng.SailingEase.Components.DataEntityComponent.Localisation {
    
    
    public interface ILanguage {
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        global::System.Resources.ResourceManager ResourceManager {
            get;
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        global::System.Globalization.CultureInfo Culture {
            get;
        }
        
        /// <summary>
        ///   查找类似 请先设置数据源。 的本地化字符串。
        /// </summary>
        string DataBaseCreateWizard_DataBaseName_MessageConnectionStringSettingsIsNull {
            get;
        }
        
        /// <summary>
        ///   查找类似 枚举 的本地化字符串。
        /// </summary>
        string DataEntity_Enum {
            get;
        }
        
        /// <summary>
        ///   查找类似 枚举代码 的本地化字符串。
        /// </summary>
        string DataEntity_Enum_EnumKey {
            get;
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        string DataEntity_Enum_Sort {
            get;
        }
        
        /// <summary>
        ///   查找类似 文本 的本地化字符串。
        /// </summary>
        string DataEntity_Enum_Text {
            get;
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        string DataEntity_Enum_Value {
            get;
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        string DataEntity_User {
            get;
        }
        
        /// <summary>
        ///   查找类似 分组标识 的本地化字符串。
        /// </summary>
        string DataEntity_User_GroupId {
            get;
        }
        
        /// <summary>
        ///   查找类似 最后登陆时间 的本地化字符串。
        /// </summary>
        string DataEntity_User_LastLoginTime {
            get;
        }
        
        /// <summary>
        ///   查找类似 登录名 的本地化字符串。
        /// </summary>
        string DataEntity_User_LoginName {
            get;
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        string DataEntity_User_Name {
            get;
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        string DataEntity_User_Password {
            get;
        }
        
        /// <summary>
        ///   查找类似 用户组 的本地化字符串。
        /// </summary>
        string DataEntity_UserGroup {
            get;
        }
        
        /// <summary>
        ///   查找类似 分组名 的本地化字符串。
        /// </summary>
        string DataEntity_UserGroup_Name {
            get;
        }
        
        /// <summary>
        ///   查找类似 脚本 的本地化字符串。
        /// </summary>
        string DataEntityCreateSqlView_TabText {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据实体 的本地化字符串。
        /// </summary>
        string DataEntityEditView {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string DataEntityEditView_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string DataEntityEditView_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string DataEntityEditView_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 实体名 的本地化字符串。
        /// </summary>
        string DataEntityEditView_LabelDataEntityName {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定代码的数据实体已存在 的本地化字符串。
        /// </summary>
        string DataEntityEditView_MessageDataEntityCodeExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string DataEntityEditView_TabPageGeneral {
            get;
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        string DataEntityEditView_TabPageRemark {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据实体 的本地化字符串。
        /// </summary>
        string DataEntityView_TabText {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据项 的本地化字符串。
        /// </summary>
        string DataItemEditView {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string DataItemEditView_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string DataItemEditView_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 允许空 的本地化字符串。
        /// </summary>
        string DataItemEditView_CheckBoxAllowEmpty {
            get;
        }
        
        /// <summary>
        ///   查找类似 保持数据唯一 的本地化字符串。
        /// </summary>
        string DataItemEditView_CheckBoxExclusive {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定代码的数据项已存在 的本地化字符串。
        /// </summary>
        string DataItemEditView_DataEntityItemCodeExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string DataItemEditView_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据类型 的本地化字符串。
        /// </summary>
        string DataItemEditView_LabelDataType {
            get;
        }
        
        /// <summary>
        ///   查找类似 小数位数 的本地化字符串。
        /// </summary>
        string DataItemEditView_LabelDecimalDigits {
            get;
        }
        
        /// <summary>
        ///   查找类似 默认值 的本地化字符串。
        /// </summary>
        string DataItemEditView_LabelDefaultValue {
            get;
        }
        
        /// <summary>
        ///   查找类似 长度 的本地化字符串。
        /// </summary>
        string DataItemEditView_LabelLength {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据项名 的本地化字符串。
        /// </summary>
        string DataItemEditView_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 或指定为 &quot;MAX&quot;。 的本地化字符串。
        /// </summary>
        string DataItemEditView_MessageLengthOrMax {
            get;
        }
        
        /// <summary>
        ///   查找类似 长度范围应在 {0} 至 {1} 之间。 的本地化字符串。
        /// </summary>
        string DataItemEditView_MessageLengthOutOfRange {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string DataItemEditView_TabPageGeneral {
            get;
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        string DataItemEditView_TabPageRemark {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string GridViewController_DataEntityColumns_Code {
            get;
        }
        
        /// <summary>
        ///   查找类似 实体名 的本地化字符串。
        /// </summary>
        string GridViewController_DataEntityColumns_Name {
            get;
        }
        
        /// <summary>
        ///   查找类似 允许空 的本地化字符串。
        /// </summary>
        string GridViewController_DataItemEntityColumns_AllowEmpty {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string GridViewController_DataItemEntityColumns_Code {
            get;
        }
        
        /// <summary>
        ///   查找类似 默认值 的本地化字符串。
        /// </summary>
        string GridViewController_DataItemEntityColumns_DefaultValue {
            get;
        }
        
        /// <summary>
        ///   查找类似 长度 的本地化字符串。
        /// </summary>
        string GridViewController_DataItemEntityColumns_Length {
            get;
        }
        
        /// <summary>
        ///   查找类似 实体名 的本地化字符串。
        /// </summary>
        string GridViewController_DataItemEntityColumns_Name {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据类型 的本地化字符串。
        /// </summary>
        string GridViewController_DataItemEntityColumns_TypeName {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        string GridViewMenuDataEntity_Add {
            get;
        }
        
        /// <summary>
        ///   查找类似 创建脚本 的本地化字符串。
        /// </summary>
        string GridViewMenuDataEntity_CreateSql {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        string GridViewMenuDataEntity_Delete {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        string GridViewMenuDataEntity_Edit {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        string GridViewMenuDataItemEntity_Add {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        string GridViewMenuDataItemEntity_Delete {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        string GridViewMenuDataItemEntity_Edit {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据库生成向导 的本地化字符串。
        /// </summary>
        string Navigation_Menu_DataBaseCreateWizard {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据实体 的本地化字符串。
        /// </summary>
        string Navigation_Menu_DataEntity {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据实体 的本地化字符串。
        /// </summary>
        string Navigation_ToolStrip_DataEntity {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据实体 的本地化字符串。
        /// </summary>
        string NavigationTreeController_DataEntity {
            get;
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        string NavigationTreeView {
            get;
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        string PropertyGridView {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定代码的数据实体已存在 的本地化字符串。
        /// </summary>
        string PropertyGridView_MessageDataEntityCodeExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定代码的数据项已存在 的本地化字符串。
        /// </summary>
        string PropertyGridView_MessageDataItemEntityCodeExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        string ToolStripGeneral_Add {
            get;
        }
        
        /// <summary>
        ///   查找类似 创建脚本 的本地化字符串。
        /// </summary>
        string ToolStripGeneral_CreateSql {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        string ToolStripGeneral_Delete {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        string ToolStripGeneral_Edit {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        string TreeMenuDataEntity_Add {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加数据项 的本地化字符串。
        /// </summary>
        string TreeMenuDataEntity_AddItem {
            get;
        }
        
        /// <summary>
        ///   查找类似 创建脚本 的本地化字符串。
        /// </summary>
        string TreeMenuDataEntity_CreateSql {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        string TreeMenuDataEntity_Delete {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        string TreeMenuDataEntity_Edit {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        string TreeMenuDataEntityFolder_Add {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        string TreeMenuDataItemEntity_Add {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        string TreeMenuDataItemEntity_Delete {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        string TreeMenuDataItemEntity_Edit {
            get;
        }
        
        /// <summary>
        ///   查找类似 显示密码 的本地化字符串。
        /// </summary>
        string UserControlCreateDataBaseWizardStepAccount_CheckBoxNoPasswordChar {
            get;
        }
        
        /// <summary>
        ///   查找类似 此帐户用以登录系统,并且具有最高管理员权限 的本地化字符串。
        /// </summary>
        string UserControlCreateDataBaseWizardStepAccount_Description {
            get;
        }
        
        /// <summary>
        ///   查找类似 帐户 的本地化字符串。
        /// </summary>
        string UserControlCreateDataBaseWizardStepAccount_LabelAccount {
            get;
        }
        
        /// <summary>
        ///   查找类似 默认管理员帐户 的本地化字符串。
        /// </summary>
        string UserControlCreateDataBaseWizardStepAccount_LabelDefaultAdminAccount {
            get;
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        string UserControlCreateDataBaseWizardStepAccount_LabelPassword {
            get;
        }
        
        /// <summary>
        ///   查找类似 有关生成数据库的所有准备工作已经就绪,单击按钮 &quot;下一步&quot; 开始生成 的本地化字符串。
        /// </summary>
        string UserControlCreateDataBaseWizardStepConfirm_LabelDescription {
            get;
        }
        
        /// <summary>
        ///   查找类似 生成数据库 的本地化字符串。
        /// </summary>
        string UserControlCreateDataBaseWizardStepCreate_LabelCreate {
            get;
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        string UserControlCreateDataBaseWizardStepCreate_LabelFailure {
            get;
        }
        
        /// <summary>
        ///   查找类似 完成! 的本地化字符串。
        /// </summary>
        string UserControlCreateDataBaseWizardStepDone_LabelDone {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据库名 的本地化字符串。
        /// </summary>
        string UserControlCreateDataBaseWizardStepEnterDataBaseName_LabelDataBaseName {
            get;
        }
        
        /// <summary>
        ///   查找类似 生成完毕后将枚举写入枚举表 的本地化字符串。
        /// </summary>
        string UserControlCreateDataBaseWizardStepOption_CheckBoxInsertEnum {
            get;
        }
        
        /// <summary>
        ///   查找类似 仅在指定的数据库中创建数据库对象,而不尝试创建数据库 的本地化字符串。
        /// </summary>
        string UserControlCreateDataBaseWizardStepOption_CheckBoxNoCreateDataBase {
            get;
        }
        
        /// <summary>
        ///   查找类似 不能覆盖任何已存在的数据库或数据库对象 的本地化字符串。
        /// </summary>
        string UserControlCreateDataBaseWizardStepOption_Description {
            get;
        }
        
        /// <summary>
        ///   查找类似 (应在您已手动建立数据库的情况下使用) 的本地化字符串。
        /// </summary>
        string UserControlCreateDataBaseWizardStepOption_LabelNoCreateDataBaseDescription {
            get;
        }
        
        /// <summary>
        ///   查找类似 选项 的本地化字符串。
        /// </summary>
        string UserControlCreateDataBaseWizardStepOption_LabelOption {
            get;
        }
        
        /// <summary>
        ///  Returns true if the current language is the default language.
        /// </summary>
        bool IsDefault {
            get;
        }
    }
}
