//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5446
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheng.SailingEase.Components.WindowComponent.Localisation {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Chinese__Simplified_ : ILanguage {
        
        private global::System.Resources.ResourceManager resourceMan;
        
        private global::System.Globalization.CultureInfo resourceCulture;
        
        public Chinese__Simplified_() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sheng.SailingEase.Components.WindowComponent.Localisation.Chinese (Simplified)", typeof(Chinese__Simplified_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.Globalization.CultureInfo Culture {
            get {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    global::System.Globalization.CultureInfo temp = new global::System.Globalization.CultureInfo("zh-CHS");
                    resourceCulture = temp;
                }
                return resourceCulture;
            }
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        public string Explorer_GridColumns_Code {
            get {
                return ResourceManager.GetString("Explorer_GridColumns_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public string Explorer_GridColumns_Name {
            get {
                return ResourceManager.GetString("Explorer_GridColumns_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加窗体 的本地化字符串。
        /// </summary>
        public string Explorer_GridViewContextMenu_Add {
            get {
                return ResourceManager.GetString("Explorer_GridViewContextMenu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加文件夹 的本地化字符串。
        /// </summary>
        public string Explorer_GridViewContextMenu_AddFolder {
            get {
                return ResourceManager.GetString("Explorer_GridViewContextMenu_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public string Explorer_GridViewContextMenu_Delete {
            get {
                return ResourceManager.GetString("Explorer_GridViewContextMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public string Explorer_GridViewContextMenu_Edit {
            get {
                return ResourceManager.GetString("Explorer_GridViewContextMenu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定代码的项已存在。 的本地化字符串。
        /// </summary>
        public string Explorer_PropertyView_MessageCodeExist {
            get {
                return ResourceManager.GetString("Explorer_PropertyView_MessageCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        public string Explorer_PropertyView_TabText {
            get {
                return ResourceManager.GetString("Explorer_PropertyView_TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public string Explorer_ToolStripGeneral_Add {
            get {
                return ResourceManager.GetString("Explorer_ToolStripGeneral_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加文件夹 的本地化字符串。
        /// </summary>
        public string Explorer_ToolStripGeneral_AddFolder {
            get {
                return ResourceManager.GetString("Explorer_ToolStripGeneral_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public string Explorer_ToolStripGeneral_Delete {
            get {
                return ResourceManager.GetString("Explorer_ToolStripGeneral_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public string Explorer_ToolStripGeneral_Edit {
            get {
                return ResourceManager.GetString("Explorer_ToolStripGeneral_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗体 的本地化字符串。
        /// </summary>
        public string ExplorerView_RootFolder {
            get {
                return ResourceManager.GetString("ExplorerView_RootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗体 的本地化字符串。
        /// </summary>
        public string ExplorerView_TabText {
            get {
                return ResourceManager.GetString("ExplorerView_TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹 的本地化字符串。
        /// </summary>
        public string FolderEditView {
            get {
                return ResourceManager.GetString("FolderEditView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public string FolderEditView_ButtonCancel {
            get {
                return ResourceManager.GetString("FolderEditView_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public string FolderEditView_ButtonOK {
            get {
                return ResourceManager.GetString("FolderEditView_ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹名 的本地化字符串。
        /// </summary>
        public string FolderEditView_LabelName {
            get {
                return ResourceManager.GetString("FolderEditView_LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗体 的本地化字符串。
        /// </summary>
        public string Navigation_Menu_Window {
            get {
                return ResourceManager.GetString("Navigation_Menu_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗体 的本地化字符串。
        /// </summary>
        public string Navigation_ToolStrip_Window {
            get {
                return ResourceManager.GetString("Navigation_ToolStrip_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        public string NavigationTreeView {
            get {
                return ResourceManager.GetString("NavigationTreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public string TreeMenuFolder_Add {
            get {
                return ResourceManager.GetString("TreeMenuFolder_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加窗体 的本地化字符串。
        /// </summary>
        public string TreeMenuFolder_AddWindow {
            get {
                return ResourceManager.GetString("TreeMenuFolder_AddWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public string TreeMenuFolder_Delete {
            get {
                return ResourceManager.GetString("TreeMenuFolder_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public string TreeMenuFolder_Edit {
            get {
                return ResourceManager.GetString("TreeMenuFolder_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public string TreeMenuWindowEntity_Add {
            get {
                return ResourceManager.GetString("TreeMenuWindowEntity_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public string TreeMenuWindowEntity_Delete {
            get {
                return ResourceManager.GetString("TreeMenuWindowEntity_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public string TreeMenuWindowEntity_Edit {
            get {
                return ResourceManager.GetString("TreeMenuWindowEntity_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗体 的本地化字符串。
        /// </summary>
        public string WindowEditView {
            get {
                return ResourceManager.GetString("WindowEditView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public string WindowEditView_ButtonCancel {
            get {
                return ResourceManager.GetString("WindowEditView_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public string WindowEditView_ButtonOK {
            get {
                return ResourceManager.GetString("WindowEditView_ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        public string WindowEditView_LabelCode {
            get {
                return ResourceManager.GetString("WindowEditView_LabelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public string WindowEditView_LabelName {
            get {
                return ResourceManager.GetString("WindowEditView_LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定代码的窗体已存在 的本地化字符串。
        /// </summary>
        public string WindowEditView_MessageFormEntityCodeExist {
            get {
                return ResourceManager.GetString("WindowEditView_MessageFormEntityCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///  Returns true if the current language is the default language.
        /// </summary>
        public bool IsDefault {
            get {
                return true;
            }
        }
        
        /// <summary>
        ///  Returns a System.String that represents the current System.Object.
        /// </summary>
        public override string ToString() {
            return Culture.EnglishName;
        }
    }
}
