//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.Common.Configuration.Manageability.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.Common.Configuration.Manageability.Properti" +
                            "es.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Expected an instance of InstrumentationConfigurationSection. 的本地化字符串。
        /// </summary>
        internal static string ConfigurationElementNotInstrumentationConfigurationSection {
            get {
                return ResourceManager.GetString("ConfigurationElementNotInstrumentationConfigurationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected and instance of &apos;{0}&apos; but got an instance of &apos;{1}&apos; instead. 的本地化字符串。
        /// </summary>
        internal static string ConfigurationElementOfWrongType {
            get {
                return ResourceManager.GetString("ConfigurationElementOfWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attributes 的本地化字符串。
        /// </summary>
        internal static string CustomProviderAttributesPartName {
            get {
                return ResourceManager.GetString("CustomProviderAttributesPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string CustomProviderTypePartName {
            get {
                return ResourceManager.GetString("CustomProviderTypePartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A started category is required to perform the operation. 的本地化字符串。
        /// </summary>
        internal static string ExceptionAdmBuildingNoCurrentCategory {
            get {
                return ResourceManager.GetString("ExceptionAdmBuildingNoCurrentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A started policy is required to perform the operation. 的本地化字符串。
        /// </summary>
        internal static string ExceptionAdmBuildingNoCurrentPolicy {
            get {
                return ResourceManager.GetString("ExceptionAdmBuildingNoCurrentPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A policy construction is in process. 的本地化字符串。
        /// </summary>
        internal static string ExceptionAdmBuildingPolicyNotFinished {
            get {
                return ResourceManager.GetString("ExceptionAdmBuildingPolicyNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The built content is requested but there are outstanding categories being built. 的本地化字符串。
        /// </summary>
        internal static string ExceptionAdmBuildingProcessNotFinished {
            get {
                return ResourceManager.GetString("ExceptionAdmBuildingProcessNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The default value is above the max value for part &apos;{0}&apos; on policy &apos;{1}&apos;: {2} vs {3}. 的本地化字符串。
        /// </summary>
        internal static string ExceptionAdmDefaultValueAboveMaxValue {
            get {
                return ResourceManager.GetString("ExceptionAdmDefaultValueAboveMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The default value is below the min value for part &apos;{0}&apos; on policy &apos;{1}&apos;: {2} vs {3}. 的本地化字符串。
        /// </summary>
        internal static string ExceptionAdmDefaultValueBelowMinValue {
            get {
                return ResourceManager.GetString("ExceptionAdmDefaultValueBelowMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The default value for part &apos;{0}&apos; on policy &apos;{1}&apos; is longer than the max length {2}. 的本地化字符串。
        /// </summary>
        internal static string ExceptionAdmDefaultValueLongerThanMaxlen {
            get {
                return ResourceManager.GetString("ExceptionAdmDefaultValueLongerThanMaxlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registry key path contains invalid characters or is missing parts: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExceptionAdmInvalidCharactersInRegistryKey {
            get {
                return ResourceManager.GetString("ExceptionAdmInvalidCharactersInRegistryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The default value is invalid: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExceptionAdmInvalidDefaultValue {
            get {
                return ResourceManager.GetString("ExceptionAdmInvalidDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The max len of {2} is invalid on part &apos;{0}&apos; for policy &apos;{1}&apos;. The allowed values are 0-1024. 的本地化字符串。
        /// </summary>
        internal static string ExceptionAdmInvalidMaxlen {
            get {
                return ResourceManager.GetString("ExceptionAdmInvalidMaxlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String &apos;{0}&apos; is not a valid name on an ADM template. 的本地化字符串。
        /// </summary>
        internal static string ExceptionAdmInvalidName {
            get {
                return ResourceManager.GetString("ExceptionAdmInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The suggestion is invalid: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExceptionAdmInvalidSuggestion {
            get {
                return ResourceManager.GetString("ExceptionAdmInvalidSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min value is larger than max value for part &apos;{0}&apos; on policy &apos;{1}&apos;: {2} vs {3}. 的本地化字符串。
        /// </summary>
        internal static string ExceptionAdmMinValueLargerThanMaxValue {
            get {
                return ResourceManager.GetString("ExceptionAdmMinValueLargerThanMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The numeric constraint &apos;{2}&apos; for part &apos;{0}&apos; on policy &apos;{1}&apos; is outside the allowed range. The valued values are 0-999999999.  的本地化字符串。
        /// </summary>
        internal static string ExceptionAdmNumericConstraintOutsideRange {
            get {
                return ResourceManager.GetString("ExceptionAdmNumericConstraintOutsideRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path segment over 255 chars in length for registry key: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExceptionAdmRegistryKeyPathSegmentTooLong {
            get {
                return ResourceManager.GetString("ExceptionAdmRegistryKeyPathSegmentTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registry value name over 255 chars in length: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExceptionAdmRegistryValueNameTooLong {
            get {
                return ResourceManager.GetString("ExceptionAdmRegistryValueNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The application name cannot be longer than 255 characters. 的本地化字符串。
        /// </summary>
        internal static string ExceptionApplicationNameTooLong {
            get {
                return ResourceManager.GetString("ExceptionApplicationNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter is an empty string 的本地化字符串。
        /// </summary>
        internal static string ExceptionArgumentEmpty {
            get {
                return ResourceManager.GetString("ExceptionArgumentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group policy processing could not be locked prior to reading the registry 的本地化字符串。
        /// </summary>
        internal static string ExceptionCannotLockGroupPolicy {
            get {
                return ResourceManager.GetString("ExceptionCannotLockGroupPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The configuration file {0} could not be found. 的本地化字符串。
        /// </summary>
        internal static string ExceptionConfigurationLoadFileNotFound {
            get {
                return ResourceManager.GetString("ExceptionConfigurationLoadFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception caught from callback for change on section &apos;{0}&apos; calling method &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExceptionErrorOnCallbackForSectionUpdate {
            get {
                return ResourceManager.GetString("ExceptionErrorOnCallbackForSectionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error was detected while a configuration element&apos;s properties were being overriden with policy values. 的本地化字符串。
        /// </summary>
        internal static string ExceptionErrorWhileOverriding {
            get {
                return ResourceManager.GetString("ExceptionErrorWhileOverriding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no value with name &apos;{1}&apos; on key &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ExceptionMissingRegistryValue {
            get {
                return ResourceManager.GetString("ExceptionMissingRegistryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value for &apos;{1}&apos; on key &apos;{0}&apos; is not a valid value name for enum type &apos;{2}&apos;: &apos;{3}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExceptionRegistryValueNotEnumValue {
            get {
                return ResourceManager.GetString("ExceptionRegistryValueNotEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value for &apos;{1}&apos; on key &apos;{0}&apos; is not a valid assembly qualified type name: &apos;{2}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExceptionRegistryValueNotTypeName {
            get {
                return ResourceManager.GetString("ExceptionRegistryValueNotTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value for &apos;{1}&apos; on key &apos;{0}&apos; is not of the correct type:
        ///Expected {2} but got {3} instead. 的本地化字符串。
        /// </summary>
        internal static string ExceptionRegistryValueOfWrongType {
            get {
                return ResourceManager.GetString("ExceptionRegistryValueOfWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value can not be null or string or empty. 的本地化字符串。
        /// </summary>
        internal static string ExceptionStringNullOrEmpty {
            get {
                return ResourceManager.GetString("ExceptionStringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected error while processing section &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExceptionUnexpectedErrorProcessingSection {
            get {
                return ResourceManager.GetString("ExceptionUnexpectedErrorProcessingSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The expected type &apos;{0}&apos; was not provided. 的本地化字符串。
        /// </summary>
        internal static string ExceptionUnexpectedType {
            get {
                return ResourceManager.GetString("ExceptionUnexpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No WmiImplementationAttribute was found for implementation &apos;{0}&apos; on type {1}. 的本地化字符串。
        /// </summary>
        internal static string ExceptionWmiImplementationAttributeNotFound {
            get {
                return ResourceManager.GetString("ExceptionWmiImplementationAttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type specified in the WmiImplementationAttribute for implementation &apos;{0}&apos; on type {2} is incompatible with the requested type {1}. 的本地化字符串。
        /// </summary>
        internal static string ExceptionWmiImplementationIncompatibleType {
            get {
                return ResourceManager.GetString("ExceptionWmiImplementationIncompatibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type specified in the WmiImplementationAttribute for implementation &apos;{0}&apos; on type {1} is invalid or cannot be found. 的本地化字符串。
        /// </summary>
        internal static string ExceptionWmiImplementationInvalidTypeName {
            get {
                return ResourceManager.GetString("ExceptionWmiImplementationInvalidTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group policy notification thread 的本地化字符串。
        /// </summary>
        internal static string GroupPolicyWatcherThread {
            get {
                return ResourceManager.GetString("GroupPolicyWatcherThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instrumentation 的本地化字符串。
        /// </summary>
        internal static string InstrumentationSectionCategoryName {
            get {
                return ResourceManager.GetString("InstrumentationSectionCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event logging enabled 的本地化字符串。
        /// </summary>
        internal static string InstrumentationSectionEventLoggingEnabledPartName {
            get {
                return ResourceManager.GetString("InstrumentationSectionEventLoggingEnabledPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performance counters enabled 的本地化字符串。
        /// </summary>
        internal static string InstrumentationSectionPerformanceCountersEnabledPartName {
            get {
                return ResourceManager.GetString("InstrumentationSectionPerformanceCountersEnabledPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specify settings for the instrumentation section 的本地化字符串。
        /// </summary>
        internal static string InstrumentationSectionPolicyName {
            get {
                return ResourceManager.GetString("InstrumentationSectionPolicyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WMI enabled 的本地化字符串。
        /// </summary>
        internal static string InstrumentationSectionWmiEnabledPartName {
            get {
                return ResourceManager.GetString("InstrumentationSectionWmiEnabledPartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manageable Configuration Source 的本地化字符串。
        /// </summary>
        internal static string ManageableConfigurationSourceName {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updates to configuration through the ManageableConfigurationSource are not supported. Use the FileConfigurationSource instead. 的本地化字符串。
        /// </summary>
        internal static string ManageableConfigurationSourceUpdateNotAvailable {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceUpdateNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string NoneListItem {
            get {
                return ResourceManager.GetString("NoneListItem", resourceCulture);
            }
        }
    }
}
