//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5448
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheng.SailingEase.Core.Development.Localisation {
    
    
    public interface ILanguage {
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        global::System.Resources.ResourceManager ResourceManager {
            get;
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        global::System.Globalization.CultureInfo Culture {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string CallAddInDev_EditorPanel_General {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string CallEntityMethodDev_EditorPanel_General {
            get;
        }
        
        /// <summary>
        ///   查找类似 窗体元素 的本地化字符串。
        /// </summary>
        string ClearFormDataDev_EditorPanel_FormElement {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string ClearFormDataDev_EditorPanel_General {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string ClearFormDataDev_EditorPanel_Parameter {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据 的本地化字符串。
        /// </summary>
        string DataEntityItemDataSourceEditView {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string DataEntityItemDataSourceEditView_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string DataEntityItemDataSourceEditView_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据项 的本地化字符串。
        /// </summary>
        string DataEntityItemDataSourceEditView_LabelDataItem {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        string DataEntityItemDataSourceEditView_LabelDataSource {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据实体/数据项 的本地化字符串。
        /// </summary>
        string DataEntityTreeChooseView {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string DataEntityTreeChooseView_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        string DataEntityTreeChooseView_ButtonClear {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string DataEntityTreeChooseView_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 请在树节点中选择数据实体下的数据项 的本地化字符串。
        /// </summary>
        string DataEntityTreeChooseView_NoDataItemSelected {
            get;
        }
        
        /// <summary>
        ///   查找类似 请在树节点中选择项目 的本地化字符串。
        /// </summary>
        string DataEntityTreeChooseView_NoItemSelected {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据 的本地化字符串。
        /// </summary>
        string DataListAddRowDev_EditorPanel_Data {
            get;
        }
        
        /// <summary>
        ///   查找类似 方法参数 的本地化字符串。
        /// </summary>
        string DataListAddRowDev_EditorPanel_Parameter {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据 的本地化字符串。
        /// </summary>
        string DataListDataItemEditView {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string DataListDataItemEditView_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string DataListDataItemEditView_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 列 的本地化字符串。
        /// </summary>
        string DataListDataItemEditView_LabelDataColumn {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        string DataListDataItemEditView_LabelDataSource {
            get;
        }
        
        /// <summary>
        ///   查找类似 方法参数 的本地化字符串。
        /// </summary>
        string DataListDeleteRowDev_EditorPanel_Parameter {
            get;
        }
        
        /// <summary>
        ///   查找类似 条件 的本地化字符串。
        /// </summary>
        string DataListDeleteRowDev_EditorPanel_Where {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string DataListRefreshDev_EditorPanel_General {
            get;
        }
        
        /// <summary>
        ///   查找类似 方法参数 的本地化字符串。
        /// </summary>
        string DataListRefreshDev_EditorPanel_Parameter {
            get;
        }
        
        /// <summary>
        ///   查找类似 Sql 的本地化字符串。
        /// </summary>
        string DataListRefreshDev_EditorPanel_Sql {
            get;
        }
        
        /// <summary>
        ///   查找类似 条件 的本地化字符串。
        /// </summary>
        string DataListRefreshDev_EditorPanel_Where {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据 的本地化字符串。
        /// </summary>
        string DataListUpdateRowDev_EditorPanel_Data {
            get;
        }
        
        /// <summary>
        ///   查找类似 方法参数 的本地化字符串。
        /// </summary>
        string DataListUpdateRowDev_EditorPanel_Parameter {
            get;
        }
        
        /// <summary>
        ///   查找类似 窗体元素 的本地化字符串。
        /// </summary>
        string DataSource_FormElement {
            get;
        }
        
        /// <summary>
        ///   查找类似 系统 的本地化字符串。
        /// </summary>
        string DataSource_System {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        string DataSourceEditView {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string DataSourceEditView_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string DataSourceEditView_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        string DataSourceEditView_LabelDataSource {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源提供程序 的本地化字符串。
        /// </summary>
        string DataSourceEditView_LabelProvide {
            get;
        }
        
        /// <summary>
        ///   查找类似 点击设置数据源 的本地化字符串。
        /// </summary>
        string DataSourceSelector_linkLabelDataSource {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据实体 的本地化字符串。
        /// </summary>
        string DeleteDataDev_EditorPanel_DataEntity {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string DeleteDataDev_EditorPanel_General {
            get;
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        string DeleteDataDev_EditorPanel_Parameter {
            get;
        }
        
        /// <summary>
        ///   查找类似 Sql 的本地化字符串。
        /// </summary>
        string DeleteDataDev_EditorPanel_Sql {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的代码已存在于此事件序列中 的本地化字符串。
        /// </summary>
        string EditorHelper_MessageEventCodeExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的窗体元素不存在 的本地化字符串。
        /// </summary>
        string EventDev_ClearFormDataDev_FormElementNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的数据列不存在 的本地化字符串。
        /// </summary>
        string EventDev_DataListOperatorDev_DataColumnNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的数据列表不存在 的本地化字符串。
        /// </summary>
        string EventDev_DataListOperatorDev_DataListNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的窗体元素不存在 的本地化字符串。
        /// </summary>
        string EventDev_DataListOperatorDev_FormElementNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的数据实体不存在 的本地化字符串。
        /// </summary>
        string EventDev_DeleteDataDev_DataEntityNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的数据项不存在 的本地化字符串。
        /// </summary>
        string EventDev_DeleteDataDev_DataItemEntityNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的窗体元素不存在 的本地化字符串。
        /// </summary>
        string EventDev_DeleteDataDev_FormElementNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的数据实体不存在 的本地化字符串。
        /// </summary>
        string EventDev_LoadDataToFormDev_DataEntityNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的数据项不存在 的本地化字符串。
        /// </summary>
        string EventDev_LoadDataToFormDev_DataItemEntityNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的窗体元素不存在 的本地化字符串。
        /// </summary>
        string EventDev_LoadDataToFormDev_FormElementNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的窗体元素不存在 的本地化字符串。
        /// </summary>
        string EventDev_NewGuidDev_FormElementNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的窗体元素不存在 的本地化字符串。
        /// </summary>
        string EventDev_OpenFormDev_FormElementNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的窗体不存在 的本地化字符串。
        /// </summary>
        string EventDev_OpenFormDev_FormNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的窗体元素不存在 的本地化字符串。
        /// </summary>
        string EventDev_ReceiveDataDev_FormElementNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据列表所关联的数据实体不存在 的本地化字符串。
        /// </summary>
        string EventDev_RefreshListDev_DataEntityNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的数据项不存在 的本地化字符串。
        /// </summary>
        string EventDev_RefreshListDev_DataItemEntityNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的数据列表不存在 的本地化字符串。
        /// </summary>
        string EventDev_RefreshListDev_DataListNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的窗体元素不存在 的本地化字符串。
        /// </summary>
        string EventDev_RefreshListDev_FormElementNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的窗体元素不存在 的本地化字符串。
        /// </summary>
        string EventDev_ReturnDataToCallerFormDev_FormElementNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的数据实体不存在 的本地化字符串。
        /// </summary>
        string EventDev_SaveFormDataDev_DataEntityNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的数据项不存在 的本地化字符串。
        /// </summary>
        string EventDev_SaveFormDataDev_DataItemEntityNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的窗体元素不存在 的本地化字符串。
        /// </summary>
        string EventDev_SaveFormDataDev_FormElementNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的数据实体不存在 的本地化字符串。
        /// </summary>
        string EventDev_UpdateFormDataDev_DataEntityNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的数据项不存在 的本地化字符串。
        /// </summary>
        string EventDev_UpdateFormDataDev_DataItemEntityNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的窗体元素不存在 的本地化字符串。
        /// </summary>
        string EventDev_UpdateFormDataDev_FormElementNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的窗体元素不存在 的本地化字符串。
        /// </summary>
        string EventDev_ValidateFormDataDev_FormElementNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        string EventEditorAdapterAbstract_EventEditorTreeNodeRoot {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string ExitDev_EditorPanel_General {
            get;
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        string ExitDev_EditorPanel_Parameter {
            get;
        }
        
        /// <summary>
        ///   查找类似 集合 的本地化字符串。
        /// </summary>
        string FormCollectionEditor {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string FormCollectionEditor_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string FormCollectionEditor_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        string FormCollectionEditor_ToolStripButtonAdd {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        string FormCollectionEditor_ToolStripButtonDelete {
            get;
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        string FormCollectionEditor_ToolStripButtonDown {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        string FormCollectionEditor_ToolStripButtonEdit {
            get;
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        string FormCollectionEditor_ToolStripButtonUp {
            get;
        }
        
        /// <summary>
        ///   查找类似 枚举选择 的本地化字符串。
        /// </summary>
        string FormEnumChoose {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string FormEnumChoose_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string FormEnumChoose_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string FormEnumChoose_ColumnCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 枚举名 的本地化字符串。
        /// </summary>
        string FormEnumChoose_ColumnName {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据 的本地化字符串。
        /// </summary>
        string FormEventDataItemDataSet {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string FormEventDataItemDataSet_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string FormEventDataItemDataSet_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据项 的本地化字符串。
        /// </summary>
        string FormEventDataItemDataSet_LabelDataItem {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        string FormEventDataItemDataSet_LabelDataSource {
            get;
        }
        
        /// <summary>
        ///   查找类似 载入至 的本地化字符串。
        /// </summary>
        string FormEventDataItemDataSet_LabelDataSource_LoadTo {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据 的本地化字符串。
        /// </summary>
        string FormEventDataListDataSet {
            get;
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        string FormEventDataListDataSet_ButtonBrowse {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string FormEventDataListDataSet_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string FormEventDataListDataSet_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据列 的本地化字符串。
        /// </summary>
        string FormEventDataListDataSet_LabelDataColumn {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        string FormEventDataListDataSet_LabelDataSource {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        string FormEventDataListDataSet_LabelFormElement {
            get;
        }
        
        /// <summary>
        ///   查找类似 事件 的本地化字符串。
        /// </summary>
        string FormEventEditor {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string FormEventEditor_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string FormEventEditor_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 可用事件 的本地化字符串。
        /// </summary>
        string FormEventEditor_LabelEvent {
            get;
        }
        
        /// <summary>
        ///   查找类似 触发时机 的本地化字符串。
        /// </summary>
        string FormEventEditor_LabelEventTime {
            get;
        }
        
        /// <summary>
        ///   查找类似 ({0}) 警告 的本地化字符串。
        /// </summary>
        string FormEventEditor_WarningNode {
            get;
        }
        
        /// <summary>
        ///   查找类似 传入数据 的本地化字符串。
        /// </summary>
        string FormEventOpenFormSendDataSet {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string FormEventOpenFormSendDataSet_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string FormEventOpenFormSendDataSet_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        string FormEventOpenFormSendDataSet_ComboBoxFormElement {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据代码 的本地化字符串。
        /// </summary>
        string FormEventOpenFormSendDataSet_LabelDataCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据名 的本地化字符串。
        /// </summary>
        string FormEventOpenFormSendDataSet_LabelDataName {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        string FormEventOpenFormSendDataSet_LabelDataSource {
            get;
        }
        
        /// <summary>
        ///   查找类似 接收数据 的本地化字符串。
        /// </summary>
        string FormEventReceiveDataSet {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string FormEventReceiveDataSet_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string FormEventReceiveDataSet_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据代码 的本地化字符串。
        /// </summary>
        string FormEventReceiveDataSet_LabelDataCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 设置到 的本地化字符串。
        /// </summary>
        string FormEventReceiveDataSet_LabelReceiveTo {
            get;
        }
        
        /// <summary>
        ///   查找类似 返回数据 的本地化字符串。
        /// </summary>
        string FormEventReturnDataToCallerFormSet {
            get;
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        string FormEventReturnDataToCallerFormSet_ButtonBrowse {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string FormEventReturnDataToCallerFormSet_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string FormEventReturnDataToCallerFormSet_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        string FormEventReturnDataToCallerFormSet_LabelDataSource {
            get;
        }
        
        /// <summary>
        ///   查找类似 窗体元素代码 的本地化字符串。
        /// </summary>
        string FormEventReturnDataToCallerFormSet_LabelFormElementCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 窗体选择 的本地化字符串。
        /// </summary>
        string FormFormChoose {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string FormFormChoose_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string FormFormChoose_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string FormFormChoose_ColumnCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string FormFormChoose_ColumnName {
            get;
        }
        
        /// <summary>
        ///   查找类似 选择窗体元素 的本地化字符串。
        /// </summary>
        string FormFormElementChoose {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string FormFormElementChoose_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string FormFormElementChoose_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 窗体元素 的本地化字符串。
        /// </summary>
        string FormFormElementChoose_LabelFormElement {
            get;
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        string FormGlobalFormElementChoose {
            get;
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        string FormGlobalFormElementChoose_AllowFormElementControlType_All {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string FormGlobalFormElementChoose_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string FormGlobalFormElementChoose_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 当前允许选择的元素类型 的本地化字符串。
        /// </summary>
        string FormGlobalFormElementChoose_CurrentAllowFormElementControlType {
            get;
        }
        
        /// <summary>
        ///   查找类似 一些窗体元素可能未被列出,因为它们在当前所要使用的地方不受支持.$NewLine$相关信息请参考帮助文档. 的本地化字符串。
        /// </summary>
        string FormGlobalFormElementChoose_LabelDescription {
            get;
        }
        
        /// <summary>
        ///   查找类似 全局窗体元素选择 的本地化字符串。
        /// </summary>
        string FormGlobalFormElementChoose_LabelTitle {
            get;
        }
        
        /// <summary>
        ///   查找类似 请选择窗体元素 的本地化字符串。
        /// </summary>
        string FormGlobalFormElementChoose_MessageChooseFormElement {
            get;
        }
        
        /// <summary>
        ///   查找类似 选择的窗体元素类型不支持 的本地化字符串。
        /// </summary>
        string FormGlobalFormElementChoose_MessageChooseFormElementNotSupport {
            get;
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        string FormGlobalFormElementChoose_ToolStripMenuItemSelect {
            get;
        }
        
        /// <summary>
        ///   查找类似 显示全部 的本地化字符串。
        /// </summary>
        string FormGlobalFormElementChoose_ToolStripMenuItemShowAll {
            get;
        }
        
        /// <summary>
        ///   查找类似 警告树 的本地化字符串。
        /// </summary>
        string FormWarning {
            get;
        }
        
        /// <summary>
        ///   查找类似 {0} 警告 的本地化字符串。
        /// </summary>
        string FormWarning_ToolStripButtonWarning {
            get;
        }
        
        /// <summary>
        ///   查找类似 选择资源 的本地化字符串。
        /// </summary>
        string ImageResourceChooseView {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string ImageResourceChooseView_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        string ImageResourceChooseView_ButtonImport {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string ImageResourceChooseView_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 资源 的本地化字符串。
        /// </summary>
        string ImageResourceChooseView_GroupBoxResource {
            get;
        }
        
        /// <summary>
        ///   查找类似 项目资源 的本地化字符串。
        /// </summary>
        string ImageResourceChooseView_LabelProjectResource {
            get;
        }
        
        /// <summary>
        ///   查找类似 当前资源目录下已有同名文件,是否覆盖? 的本地化字符串。
        /// </summary>
        string ImageResourceChooseView_MessageResourceOverrideConfirm {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据实体 的本地化字符串。
        /// </summary>
        string LoadDataToFormDev_EditorPanel_DataEntity {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string LoadDataToFormDev_EditorPanel_General {
            get;
        }
        
        /// <summary>
        ///   查找类似 载入 的本地化字符串。
        /// </summary>
        string LoadDataToFormDev_EditorPanel_Load {
            get;
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        string LoadDataToFormDev_EditorPanel_Parameter {
            get;
        }
        
        /// <summary>
        ///   查找类似 Sql 的本地化字符串。
        /// </summary>
        string LoadDataToFormDev_EditorPanel_Sql {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string LockProgramDev_EditorPanel_General {
            get;
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        string LockProgramDev_EditorPanel_Parameter {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string NewGuidDev_EditorPanel_General {
            get;
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        string NewGuidDev_EditorPanel_Parameter {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string OpenFormDev_EditorPanel_General {
            get;
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        string OpenFormDev_EditorPanel_Parameter {
            get;
        }
        
        /// <summary>
        ///   查找类似 传入数据 的本地化字符串。
        /// </summary>
        string OpenFormDev_EditorPanel_SendData {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string OpenSystemFormDev_EditorPanel_General {
            get;
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        string OpenSystemFormDev_EditorPanel_Parameter {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string ReceiveDataDev_EditorPanel_General {
            get;
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        string ReceiveDataDev_EditorPanel_Parameter {
            get;
        }
        
        /// <summary>
        ///   查找类似 接收数据 的本地化字符串。
        /// </summary>
        string ReceiveDataDev_EditorPanel_ReceiveData {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string ReLoginDev_EditorPanel_General {
            get;
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        string ReLoginDev_EditorPanel_Parameter {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string ReturnDataToCallerFormDev_EditorPanel_General {
            get;
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        string ReturnDataToCallerFormDev_EditorPanel_Parameter {
            get;
        }
        
        /// <summary>
        ///   查找类似 返回数据 的本地化字符串。
        /// </summary>
        string ReturnDataToCallerFormDev_EditorPanel_ReturnData {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据实体 的本地化字符串。
        /// </summary>
        string SaveFormDataDev_EditorPanel_DataEntity {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string SaveFormDataDev_EditorPanel_General {
            get;
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        string SaveFormDataDev_EditorPanel_Parameter {
            get;
        }
        
        /// <summary>
        ///   查找类似 Sql 的本地化字符串。
        /// </summary>
        string SaveFormDataDev_EditorPanel_Sql {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑事件 的本地化字符串。
        /// </summary>
        string SEUndoUnitEventEdit_Name {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加事件: {0} 的本地化字符串。
        /// </summary>
        string SEUndoUnitEventEdit_Name_Add {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除事件: {0} 的本地化字符串。
        /// </summary>
        string SEUndoUnitEventEdit_Name_Delete {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑事件: {0} 的本地化字符串。
        /// </summary>
        string SEUndoUnitEventEdit_Name_Edit {
            get;
        }
        
        /// <summary>
        ///   查找类似 移动事件: {0} 的本地化字符串。
        /// </summary>
        string SEUndoUnitEventEdit_Name_Move {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除 {0} 事件 的本地化字符串。
        /// </summary>
        string SEUndoUnitEventEdit_Name_MultiDelete {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string StartProcessDev_EditorPanel_General {
            get;
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        string StartProcessDev_EditorPanel_Parameter {
            get;
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        string TrueFalseTable_False {
            get;
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        string TrueFalseTable_True {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string UpdateFormDataDev_EditorPanel_General {
            get;
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        string UpdateFormDataDev_EditorPanel_Parameter {
            get;
        }
        
        /// <summary>
        ///   查找类似 Sql 的本地化字符串。
        /// </summary>
        string UpdateFormDataDev_EditorPanel_Sql {
            get;
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        string UpdateFormDataDev_EditorPanel_Update {
            get;
        }
        
        /// <summary>
        ///   查找类似 条件 的本地化字符串。
        /// </summary>
        string UpdateFormDataDev_EditorPanel_Where {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string UserControlEvent_ColumnEventCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 事件 的本地化字符串。
        /// </summary>
        string UserControlEvent_ColumnEventEventName {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string UserControlEvent_ColumnEventName {
            get;
        }
        
        /// <summary>
        ///   查找类似 触发时机 的本地化字符串。
        /// </summary>
        string UserControlEvent_ColumnEventTimeName {
            get;
        }
        
        /// <summary>
        ///   查找类似 当前对象不支持或无可用事件 的本地化字符串。
        /// </summary>
        string UserControlEvent_EventNotSupport {
            get;
        }
        
        /// <summary>
        ///   查找类似 是否确认删除 的本地化字符串。
        /// </summary>
        string UserControlEvent_MessageConfirmDelete {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        string UserControlEvent_ToolStripButtonAddEvent {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        string UserControlEvent_ToolStripButtonDeleteEvent {
            get;
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        string UserControlEvent_ToolStripButtonDownEvent {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        string UserControlEvent_ToolStripButtonEditEvent {
            get;
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        string UserControlEvent_ToolStripButtonUpEvent {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        string UserControlEvent_ToolStripMenuItemAdd {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        string UserControlEvent_ToolStripMenuItemDelete {
            get;
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        string UserControlEvent_ToolStripMenuItemDown {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        string UserControlEvent_ToolStripMenuItemEdit {
            get;
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        string UserControlEvent_ToolStripMenuItemUp {
            get;
        }
        
        /// <summary>
        ///   查找类似 插件全名(命名空间和类型名) 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_CallAddIn_General_LabelAddInFullName {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_CallAddIn_General_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_CallAddIn_General_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_CallEntityMethod_General_ButtonBrowse {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_CallEntityMethod_General_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 对象 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_CallEntityMethod_General_LabelFormElement {
            get;
        }
        
        /// <summary>
        ///   查找类似 可用方法 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_CallEntityMethod_General_LabelMethod {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_CallEntityMethod_General_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 目标窗体 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_CallEntityMethod_General_LabelTargetForm {
            get;
        }
        
        /// <summary>
        ///   查找类似 窗体元素 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_ClearFormData_FormElement_ColumnFormElementName {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_ClearFormData_General_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 模式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_ClearFormData_General_LabelMode {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_ClearFormData_General_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_CloseForm_General_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_CloseForm_General_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据列 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DataListAddRow_Data_ColumnDataColumnName {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DataListAddRow_Data_ColumnSourceName {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据列 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DataListDeleteRow_Where_ColumnDataColumnName {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DataListDeleteRow_Where_ColumnSourceName {
            get;
        }
        
        /// <summary>
        ///   查找类似 刷新方式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DataListRefresh_General_GroupBoxRefreshMode {
            get;
        }
        
        /// <summary>
        ///   查找类似 关联数据实体方式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DataListRefresh_General_RadioButtonDataEntity {
            get;
        }
        
        /// <summary>
        ///   查找类似 执行 SQL 方式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DataListRefresh_General_RadioButtonSql {
            get;
        }
        
        /// <summary>
        ///   查找类似 获取 SQL 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DataListRefresh_SqlRegex_ButtonGetSqlRegex {
            get;
        }
        
        /// <summary>
        ///   查找类似 若非特殊需求,请选择关联数据实体方式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DataListRefresh_SqlRegex_LabelNotice {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据项 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DataListRefresh_Where_ColumnDataItemName {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DataListRefresh_Where_ColumnDataSource {
            get;
        }
        
        /// <summary>
        ///   查找类似 匹配方式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DataListRefresh_Where_ColumnMatchType {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据列 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DataListUpdateRow_Data_ColumnDataColumnName {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DataListUpdateRow_Data_ColumnSourceName {
            get;
        }
        
        /// <summary>
        ///   查找类似 条件 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DataListUpdateRow_Data_ColumnWhere {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据项 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DeleteData_DataEntity_ColumnWhereDataItemName {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DeleteData_DataEntity_ColumnWhereDataSource {
            get;
        }
        
        /// <summary>
        ///   查找类似 匹配方式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DeleteData_DataEntity_ColumnWhereMatchType {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据实体 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DeleteData_DataEntity_LabelDataEntity {
            get;
        }
        
        /// <summary>
        ///   查找类似 条件 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DeleteData_DataEntity_LabelWhere {
            get;
        }
        
        /// <summary>
        ///   查找类似 删除方式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DeleteData_General_GroupBoxDeleteMode {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DeleteData_General_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DeleteData_General_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 关联数据实体方式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DeleteData_General_RadioButtonDataEntity {
            get;
        }
        
        /// <summary>
        ///   查找类似 执行 SQL 方式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DeleteData_General_RadioButtonSql {
            get;
        }
        
        /// <summary>
        ///   查找类似 获取 SQL 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DeleteData_SqlRegex_ButtonGetSqlRegex {
            get;
        }
        
        /// <summary>
        ///   查找类似 若非特殊需求,请选择关联数据实体方式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_DeleteData_SqlRegex_LabelNotice {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_Exit_General_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_Exit_General_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据项 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_LoadDataToForm_DataEntity_ColumnWhereDataItemName {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_LoadDataToForm_DataEntity_ColumnWhereDataSource {
            get;
        }
        
        /// <summary>
        ///   查找类似 匹配方式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_LoadDataToForm_DataEntity_ColumnWhereMatchType {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据实体 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_LoadDataToForm_DataEntity_LabelDataEntity {
            get;
        }
        
        /// <summary>
        ///   查找类似 条件 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_LoadDataToForm_DataEntity_LabelWhere {
            get;
        }
        
        /// <summary>
        ///   查找类似 加载方式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_LoadDataToForm_General_GroupBoxLoadMode {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_LoadDataToForm_General_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_LoadDataToForm_General_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 注意:切换加载方式将清除当前的载入设置 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_LoadDataToForm_General_LabelNotice {
            get;
        }
        
        /// <summary>
        ///   查找类似 关联数据实体方式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_LoadDataToForm_General_RadioButtonDataEntity {
            get;
        }
        
        /// <summary>
        ///   查找类似 执行 SQL 方式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_LoadDataToForm_General_RadioButtonSql {
            get;
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_LoadDataToForm_Load_ButtonLoadAll {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据项 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_LoadDataToForm_Load_ColumnLoadDataDataItemEntityName {
            get;
        }
        
        /// <summary>
        ///   查找类似 窗体元素 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_LoadDataToForm_Load_ColumnLoadDataLoadToName {
            get;
        }
        
        /// <summary>
        ///   查找类似 加载 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_LoadDataToForm_Load_LabelLoadData {
            get;
        }
        
        /// <summary>
        ///   查找类似 使用关联数据实体方式时,请先选择数据实体 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_LoadDataToForm_Load_MessageChooseDataEntityFirst {
            get;
        }
        
        /// <summary>
        ///   查找类似 获取 SQL 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_LoadDataToForm_SqlRegex_ButtonGetSqlRegex {
            get;
        }
        
        /// <summary>
        ///   查找类似 若非特殊需求,请选择关联数据实体方式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_LoadDataToForm_SqlRegex_LabelNotice {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_LockProgram_General_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_LockProgram_General_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_NewGuid_General_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 设置到 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_NewGuid_General_LabelFormElement {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_NewGuid_General_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 以对话框模式打开 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_OpenForm_General_CheckBoxIsDiablog {
            get;
        }
        
        /// <summary>
        ///   查找类似 若已打开 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_OpenForm_General_IfOpend {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_OpenForm_General_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 窗体 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_OpenForm_General_LabelFormName {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_OpenForm_General_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据代码 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_OpenForm_SendData_ColumnCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_OpenForm_SendData_ColumnDataSource {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据名 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_OpenForm_SendData_ColumnName {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_OpenSystemForm_General_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 窗体 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_OpenSystemForm_General_LabelForm {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_OpenSystemForm_General_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_ReceiveData_General_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_ReceiveData_General_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据代码 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_ReceiveData_ReceiveData_ColumnDataCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 设置到 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_ReceiveData_ReceiveData_ColumnReceiveToName {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_ReLogin_General_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_ReLogin_General_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_ReturnDataToCallerForm_General_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_ReturnDataToCallerForm_General_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 窗体元素代码 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_ReturnDataToCallerForm_ReturnData_ColumnFormElementCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_ReturnDataToCallerForm_ReturnData_ColumnSourceName {
            get;
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_SaveFormData_DataEntity_ButtonAll {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据项 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_SaveFormData_DataEntity_ColumnDataItemName {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_SaveFormData_DataEntity_ColumnDataSource {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据实体 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_SaveFormData_DataEntity_LabelDataEntity {
            get;
        }
        
        /// <summary>
        ///   查找类似 保存数据 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_SaveFormData_DataEntity_LabelSaveData {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_SaveFormData_General_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_SaveFormData_General_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 获取 SQL 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_SaveFormData_SqlRegex_ButtonGetSqlRegex {
            get;
        }
        
        /// <summary>
        ///   查找类似 若非特殊需求,请选择关联数据实体方式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_SaveFormData_SqlRegex_LabelNotice {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_StartProcess_General_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_StartProcess_General_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 程序 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_StartProcess_General_LabelProcess {
            get;
        }
        
        /// <summary>
        ///   查找类似 更新方式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_UpdateFormData_General_GroupBoxUpdateMode {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_UpdateFormData_General_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_UpdateFormData_General_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 关联数据实体方式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_UpdateFormData_General_RadioButtonDataEntity {
            get;
        }
        
        /// <summary>
        ///   查找类似 执行 SQL 方式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_UpdateFormData_General_RadioButtonSql {
            get;
        }
        
        /// <summary>
        ///   查找类似 获取 SQL 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_UpdateFormData_SqlRegex_ButtonGetSqlRegex {
            get;
        }
        
        /// <summary>
        ///   查找类似 若非特殊需求,请选择关联数据实体方式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_UpdateFormData_SqlRegex_LabelNotice {
            get;
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_UpdateFormData_Update_ButtonUpdateAll {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据项 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_UpdateFormData_Update_ColumnUpdateDataDataItemEntityName {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_UpdateFormData_Update_ColumnUpdateDataSourceName {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据实体 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_UpdateFormData_Update_LabelDataEntity {
            get;
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_UpdateFormData_Update_LabelUpdateData {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据项 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_UpdateFormData_Where_ColumnWhereDataItemName {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_UpdateFormData_Where_ColumnWhereDataSource {
            get;
        }
        
        /// <summary>
        ///   查找类似 匹配方式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_UpdateFormData_Where_ColumnWhereMatchType {
            get;
        }
        
        /// <summary>
        ///   查找类似 窗体元素 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_ValidateFormData_FormElement_ColumnFormElementName {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_ValidateFormData_General_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 模式 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_ValidateFormData_General_LabelMode {
            get;
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        string UserControlEventEditorPanel_ValidateFormData_General_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 窗体元素 的本地化字符串。
        /// </summary>
        string ValidateFormDataDev_EditorPanel_FormElement {
            get;
        }
        
        /// <summary>
        ///   查找类似 首要 的本地化字符串。
        /// </summary>
        string ValidateFormDataDev_EditorPanel_General {
            get;
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        string ValidateFormDataDev_EditorPanel_Parameter {
            get;
        }
        
        /// <summary>
        ///  Returns true if the current language is the default language.
        /// </summary>
        bool IsDefault {
            get;
        }
    }
}
