//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Additional Info: 的本地化字符串。
        /// </summary>
        internal static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enterprise Library Exception Handling Application Block 的本地化字符串。
        /// </summary>
        internal static string BlockName {
            get {
                return ResourceManager.GetString("BlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HANDLING CHAIN EXCEPTION: 的本地化字符串。
        /// </summary>
        internal static string ChainException {
            get {
                return ResourceManager.GetString("ChainException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A configuration failure occurred while creating policy ‘{0}’. 的本地化字符串。
        /// </summary>
        internal static string ConfigurationFailureCreatingPolicy {
            get {
                return ResourceManager.GetString("ConfigurationFailureCreatingPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The error occurred while handling an exception for policy &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string ErrorHandlingExceptionMessage {
            get {
                return ResourceManager.GetString("ErrorHandlingExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exceptions Handled/sec is the rate at which exceptions were handled. 的本地化字符串。
        /// </summary>
        internal static string ExceptionHandledHelpResource {
            get {
                return ResourceManager.GetString("ExceptionHandledHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception Handlers Executed/sec is the rate at which exception handlers were executed. 的本地化字符串。
        /// </summary>
        internal static string ExceptionHandlerExecutedHelpResource {
            get {
                return ResourceManager.GetString("ExceptionHandlerExecutedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to rethrow exception: The exception to throw is null. 的本地化字符串。
        /// </summary>
        internal static string ExceptionNullException {
            get {
                return ResourceManager.GetString("ExceptionNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The policy with name &apos;{0}&apos; cannot be found. Exception handling aborted. 的本地化字符串。
        /// </summary>
        internal static string ExceptionPolicyNotFound {
            get {
                return ResourceManager.GetString("ExceptionPolicyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The requested exception policy &apos;{0}&apos; could not be found. 的本地化字符串。
        /// </summary>
        internal static string ExceptionSimpleProviderNotFound {
            get {
                return ResourceManager.GetString("ExceptionSimpleProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value can not be an empty string or null. 的本地化字符串。
        /// </summary>
        internal static string ExceptionStringNullOrEmpty {
            get {
                return ResourceManager.GetString("ExceptionStringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type must be of type Exception. 的本地化字符串。
        /// </summary>
        internal static string ExceptionTypeNotException {
            get {
                return ResourceManager.GetString("ExceptionTypeNotException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An exception of type &apos;{0}&apos; occurred and was caught. 的本地化字符串。
        /// </summary>
        internal static string ExceptionWasCaught {
            get {
                return ResourceManager.GetString("ExceptionWasCaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access failed 的本地化字符串。
        /// </summary>
        internal static string FieldAccessFailed {
            get {
                return ResourceManager.GetString("FieldAccessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help link : {0} 的本地化字符串。
        /// </summary>
        internal static string HelpLink {
            get {
                return ResourceManager.GetString("HelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inner Exception 的本地化字符串。
        /// </summary>
        internal static string InnerException {
            get {
                return ResourceManager.GetString("InnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message : {0} 的本地化字符串。
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OFFENDING EXCEPTION: 的本地化字符串。
        /// </summary>
        internal static string OffendingException {
            get {
                return ResourceManager.GetString("OffendingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ORIGINAL EXCEPTION: 的本地化字符串。
        /// </summary>
        internal static string OriginalException {
            get {
                return ResourceManager.GetString("OriginalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission Denied 的本地化字符串。
        /// </summary>
        internal static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 POLICY NAME: {0} 的本地化字符串。
        /// </summary>
        internal static string PolicyName {
            get {
                return ResourceManager.GetString("PolicyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access failed 的本地化字符串。
        /// </summary>
        internal static string PropertyAccessFailed {
            get {
                return ResourceManager.GetString("PropertyAccessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source : {0} 的本地化字符串。
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stack Trace 的本地化字符串。
        /// </summary>
        internal static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The stack trace is unavailable. 的本地化字符串。
        /// </summary>
        internal static string StackTraceUnavailable {
            get {
                return ResourceManager.GetString("StackTraceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Exceptions Handlers Executed is the total number which exception handlers were executed. 的本地化字符串。
        /// </summary>
        internal static string TotalExceptionHandlersExecutedHelpResource {
            get {
                return ResourceManager.GetString("TotalExceptionHandlersExecutedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Exceptions Handled is the total number of exceptions handled. 的本地化字符串。
        /// </summary>
        internal static string TotalExceptionsHandledHelpResource {
            get {
                return ResourceManager.GetString("TotalExceptionsHandledHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type : {0} 的本地化字符串。
        /// </summary>
        internal static string TypeString {
            get {
                return ResourceManager.GetString("TypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to handle exception: &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string UnableToHandleException {
            get {
                return ResourceManager.GetString("UnableToHandleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;undefined value&gt; 的本地化字符串。
        /// </summary>
        internal static string UndefinedValue {
            get {
                return ResourceManager.GetString("UndefinedValue", resourceCulture);
            }
        }
    }
}
