//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.Logging.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.Logging.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Avg. Trace Execution Time Base is the base for the average execution time for traced operations. 的本地化字符串。
        /// </summary>
        internal static string AverageTraceExecutionTimeBaseHelpResource {
            get {
                return ResourceManager.GetString("AverageTraceExecutionTimeBaseHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Avg. Trace Execution Time is the average execution time for traced operations. 的本地化字符串。
        /// </summary>
        internal static string AverageTraceExecutionTimeHelpResource {
            get {
                return ResourceManager.GetString("AverageTraceExecutionTimeHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enterprise Library Logging Application Block 的本地化字符串。
        /// </summary>
        internal static string BlockName {
            get {
                return ResourceManager.GetString("BlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ActivityId 的本地化字符串。
        /// </summary>
        internal static string ComPlusInfo_ActivityId {
            get {
                return ResourceManager.GetString("ComPlusInfo_ActivityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ApplicationId 的本地化字符串。
        /// </summary>
        internal static string ComPlusInfo_ApplicationId {
            get {
                return ResourceManager.GetString("ComPlusInfo_ApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DirectCallerAccountName 的本地化字符串。
        /// </summary>
        internal static string ComPlusInfo_DirectCallerAccountName {
            get {
                return ResourceManager.GetString("ComPlusInfo_DirectCallerAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OriginalCallerAccountName 的本地化字符串。
        /// </summary>
        internal static string ComPlusInfo_OriginalCallerAccountName {
            get {
                return ResourceManager.GetString("ComPlusInfo_OriginalCallerAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TransactionID 的本地化字符串。
        /// </summary>
        internal static string ComPlusInfo_TransactionID {
            get {
                return ResourceManager.GetString("ComPlusInfo_TransactionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A configuration failure occurred while logging. 的本地化字符串。
        /// </summary>
        internal static string ConfigurationFailureLogging {
            get {
                return ResourceManager.GetString("ConfigurationFailureLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The error occurred while refreshing the logging configuration. The configuration will not be updated. 的本地化字符串。
        /// </summary>
        internal static string ConfigurationFailureUpdating {
            get {
                return ResourceManager.GetString("ConfigurationFailureUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to create object -- configuration section {0} not found in configuration file. 的本地化字符串。
        /// </summary>
        internal static string ConfigurationSectionNotFound {
            get {
                return ResourceManager.GetString("ConfigurationSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LookupAccountSid was not successful 的本地化字符串。
        /// </summary>
        internal static string CouldNotLookupAccountSid {
            get {
                return ResourceManager.GetString("CouldNotLookupAccountSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 	at  的本地化字符串。
        /// </summary>
        internal static string DebugInfo_SchemaHelperAtString {
            get {
                return ResourceManager.GetString("DebugInfo_SchemaHelperAtString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 	in {0}: line {1} 的本地化字符串。
        /// </summary>
        internal static string DebugInfo_SchemaHelperLine {
            get {
                return ResourceManager.GetString("DebugInfo_SchemaHelperLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;UnknownType&gt; 的本地化字符串。
        /// </summary>
        internal static string DebugInfo_SchemaHelperUnknownType {
            get {
                return ResourceManager.GetString("DebugInfo_SchemaHelperUnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StackTrace 的本地化字符串。
        /// </summary>
        internal static string DebugInfo_StackTrace {
            get {
                return ResourceManager.GetString("DebugInfo_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to process stack trace. 的本地化字符串。
        /// </summary>
        internal static string DebugInfo_StackTraceException {
            get {
                return ResourceManager.GetString("DebugInfo_StackTraceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insufficient privilege to generate stack trace. 的本地化字符串。
        /// </summary>
        internal static string DebugInfo_StackTraceSecurityException {
            get {
                return ResourceManager.GetString("DebugInfo_StackTraceSecurityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to log message to the default log destination. 的本地化字符串。
        /// </summary>
        internal static string DefaultLogDestinationFailed {
            get {
                return ResourceManager.GetString("DefaultLogDestinationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while the Distributor was processing the message.  Please check your configuration files for errors or typos.  Verify that your sinks are reachable (queues exist, permissions are set, database exists, etc...) 的本地化字符串。
        /// </summary>
        internal static string DefaultLogDestinationMessage {
            get {
                return ResourceManager.GetString("DefaultLogDestinationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enterprise Library Backup Sink 的本地化字符串。
        /// </summary>
        internal static string DefaultLogDestinationSinkName {
            get {
                return ResourceManager.GetString("DefaultLogDestinationSinkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timestamp: {timestamp}{newline}Message: {message}{newline}Category: {category}{newline}Priority: {priority}{newline}EventId: {eventid}{newline}Severity: {severity}{newline}Title:{title}{newline}Machine: {machine}{newline}App Domain: {appDomain}{newline}ProcessId: {processId}{newline}Process Name: {processName}{newline}Thread Name: {threadName}{newline}Win32 ThreadId:{win32ThreadId}{newline}Extended Properties: {dictionary({key} - {value}{newline})} 的本地化字符串。
        /// </summary>
        internal static string DefaultTextFormat {
            get {
                return ResourceManager.GetString("DefaultTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message: 
        /// 的本地化字符串。
        /// </summary>
        internal static string DistEventLoggerMessagePrefix {
            get {
                return ResourceManager.GetString("DistEventLoggerMessagePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Summary for 的本地化字符串。
        /// </summary>
        internal static string DistEventLoggerSummary {
            get {
                return ResourceManager.GetString("DistEventLoggerSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enterprise Library Distributor Service 的本地化字符串。
        /// </summary>
        internal static string DistributorEventLoggerDefaultApplicationName {
            get {
                return ResourceManager.GetString("DistributorEventLoggerDefaultApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E-Mail Sink is missing one of these keys in the Distributor&apos;s XML file: ToAddress, FromAddress, and/or SmtpServer. 的本地化字符串。
        /// </summary>
        internal static string EmailSinkMissingParameters {
            get {
                return ResourceManager.GetString("EmailSinkMissingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The message {0} could not be written. 的本地化字符串。
        /// </summary>
        internal static string ErrorWritingData {
            get {
                return ResourceManager.GetString("ErrorWritingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access denied to the event log &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string EventLogAccessDenied {
            get {
                return ResourceManager.GetString("EventLogAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event Log Sink is missing the key -EventSourceName- in the Distributor&apos;s configuration file. 的本地化字符串。
        /// </summary>
        internal static string EventLogSinkMissingEventSource {
            get {
                return ResourceManager.GetString("EventLogSinkMissingEventSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot check for impersonation; assuming not impersonating. 的本地化字符串。
        /// </summary>
        internal static string ExceptionCannotCheckImpersonatedIdentity {
            get {
                return ResourceManager.GetString("ExceptionCannotCheckImpersonatedIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The default category &apos;{0}&apos; is not defined in Logging Distributor configuration. 的本地化字符串。
        /// </summary>
        internal static string ExceptionCannotLoadDefaultCategory {
            get {
                return ResourceManager.GetString("ExceptionCannotLoadDefaultCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The default formatter &apos;{0}&apos; is not defined in Logging Distributor configuration. 的本地化字符串。
        /// </summary>
        internal static string ExceptionCannotLoadDefaultFormatter {
            get {
                return ResourceManager.GetString("ExceptionCannotLoadDefaultFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot revert impersonation. 的本地化字符串。
        /// </summary>
        internal static string ExceptionCannotRevertImpersonatedIdentity {
            get {
                return ResourceManager.GetString("ExceptionCannotRevertImpersonatedIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name for the CategoryFilterData can not be null. 的本地化字符串。
        /// </summary>
        internal static string ExceptionCategoryFilterDataName {
            get {
                return ResourceManager.GetString("ExceptionCategoryFilterDataName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The category &apos;{0}&apos; is not defined in the Logging Distributor configuration. 的本地化字符串。
        /// </summary>
        internal static string ExceptionCategoryNotDefined {
            get {
                return ResourceManager.GetString("ExceptionCategoryNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The configuration object for type &apos;{0}&apos; with name &apos;{1}&apos; has type &apos;{2}&apos; instead of CustomTraceListenerData which is required for custom providers. 的本地化字符串。
        /// </summary>
        internal static string ExceptionConfigurationObjectIsNotCustomTraceListenerData {
            get {
                return ResourceManager.GetString("ExceptionConfigurationObjectIsNotCustomTraceListenerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{1}&apos; specified for custom trace listener named &apos;{0}&apos; does not a default constructor, which is required when no InitData is specified in the configuration. 的本地化字符串。
        /// </summary>
        internal static string ExceptionCustomListenerTypeDoesNotHaveDefaultConstructor {
            get {
                return ResourceManager.GetString("ExceptionCustomListenerTypeDoesNotHaveDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{1}&apos; specified for custom trace listener named &apos;{0}&apos; does not a constructor with the required signature {2}. 的本地化字符串。
        /// </summary>
        internal static string ExceptionCustomListenerTypeDoesNotHaveRequiredConstructorSignature {
            get {
                return ResourceManager.GetString("ExceptionCustomListenerTypeDoesNotHaveRequiredConstructorSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom TraceListener type {1} for name {0} does not have the required constructor .ctor(string). 的本地化字符串。
        /// </summary>
        internal static string ExceptionCustomTraceListenerTypeDoesNotHaveRequiredConstructor {
            get {
                return ResourceManager.GetString("ExceptionCustomTraceListenerTypeDoesNotHaveRequiredConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception Information Details: 的本地化字符串。
        /// </summary>
        internal static string ExceptionDetails {
            get {
                return ResourceManager.GetString("ExceptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error ocurred while formatting the log entry for reporting {0}. 的本地化字符串。
        /// </summary>
        internal static string ExceptionDuringFormattingOriginalEntryForReporting {
            get {
                return ResourceManager.GetString("ExceptionDuringFormattingOriginalEntryForReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log writer failed to acquire lock while updating configuration. 的本地化字符串。
        /// </summary>
        internal static string ExceptionFailedToAcquireLockToUpdate {
            get {
                return ResourceManager.GetString("ExceptionFailedToAcquireLockToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log writer failed to acquire lock while writing log entry. 的本地化字符串。
        /// </summary>
        internal static string ExceptionFailedToAcquireLockToWriteLog {
            get {
                return ResourceManager.GetString("ExceptionFailedToAcquireLockToWriteLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HEADER 的本地化字符串。
        /// </summary>
        internal static string ExceptionFormatterHeader {
            get {
                return ResourceManager.GetString("ExceptionFormatterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The formatter &apos;{0}&apos; is not defined in the Logging Distributor configuration. 的本地化字符串。
        /// </summary>
        internal static string ExceptionFormatterNotDefined {
            get {
                return ResourceManager.GetString("ExceptionFormatterNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The factory {0} was created to use {1} objects to inject data into {2} objects. The type {3} was supplied to the Create method which is not compatible. 的本地化字符串。
        /// </summary>
        internal static string ExceptionIncompatibleConfigurationType {
            get {
                return ResourceManager.GetString("ExceptionIncompatibleConfigurationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The configuration section for Logging cannot be found in the configuration source. 的本地化字符串。
        /// </summary>
        internal static string ExceptionLoggingSectionNotFound {
            get {
                return ResourceManager.GetString("ExceptionLoggingSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The requested log sink &apos;{0}&apos; is not defined in the current configuration. 的本地化字符串。
        /// </summary>
        internal static string ExceptionNoSinkDefined {
            get {
                return ResourceManager.GetString("ExceptionNoSinkDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Distributor Settings does not have any log sinks defined in configuration. 的本地化字符串。
        /// </summary>
        internal static string ExceptionNoSinksDefined {
            get {
                return ResourceManager.GetString("ExceptionNoSinksDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value can not be a null or empty string. 的本地化字符串。
        /// </summary>
        internal static string ExceptionNullOrEmptyString {
            get {
                return ResourceManager.GetString("ExceptionNullOrEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment Variables access denied. 的本地化字符串。
        /// </summary>
        internal static string ExceptionReadEnvironmentVariablesDenied {
            get {
                return ResourceManager.GetString("ExceptionReadEnvironmentVariablesDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StackTrace Information Details: 的本地化字符串。
        /// </summary>
        internal static string ExceptionStackTraceDetails {
            get {
                return ResourceManager.GetString("ExceptionStackTraceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Summary for 的本地化字符串。
        /// </summary>
        internal static string ExceptionSummary {
            get {
                return ResourceManager.GetString("ExceptionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing TraceListenerData type in configuration &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ExceptionTraceListenerConfigurationElementMissingTypeAttribute {
            get {
                return ResourceManager.GetString("ExceptionTraceListenerConfigurationElementMissingTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid TraceListenerData type in configuration &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ExceptionTraceListenerConfigurationElementTypeNotFound {
            get {
                return ResourceManager.GetString("ExceptionTraceListenerConfigurationElementTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The configuration for TraceListener named {0} is missing from configuration. 的本地化字符串。
        /// </summary>
        internal static string ExceptionTraceListenerConfigurationNotFound {
            get {
                return ResourceManager.GetString("ExceptionTraceListenerConfigurationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception Type 的本地化字符串。
        /// </summary>
        internal static string ExceptionType {
            get {
                return ResourceManager.GetString("ExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The writer argument should not be null when passing a configurationsource for instrumentation. 的本地化字符串。
        /// </summary>
        internal static string ExceptionWriterShouldNotBeNull {
            get {
                return ResourceManager.GetString("ExceptionWriterShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to read system property. Error message: {0} 的本地化字符串。
        /// </summary>
        internal static string ExtendedPropertyError {
            get {
                return ResourceManager.GetString("ExtendedPropertyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failure while checking filters for log entry. 的本地化字符串。
        /// </summary>
        internal static string FailureWhileCheckingFilters {
            get {
                return ResourceManager.GetString("FailureWhileCheckingFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failure while reporting missing log categories for log entry. 的本地化字符串。
        /// </summary>
        internal static string FailureWhileReportingMissingCategories {
            get {
                return ResourceManager.GetString("FailureWhileReportingMissingCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failure while sending log entry to the TraceListeners. 的本地化字符串。
        /// </summary>
        internal static string FailureWhileTracing {
            get {
                return ResourceManager.GetString("FailureWhileTracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flat File Sink is missing one of these keys in the Distributor&apos;s configuration file: FilePath and/or FileName 的本地化字符串。
        /// </summary>
        internal static string FileSinkMissingConfiguration {
            get {
                return ResourceManager.GetString("FileSinkMissingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Evaluation of filter &apos;{0}&apos; failed and the filter will be ignored. See summary information below for more information. Should this problem persist, stop the service and check the configuration file(s) for possible error(s) in the configuration of the categories and sinks. 的本地化字符串。
        /// </summary>
        internal static string FilterEvaluationFailed {
            get {
                return ResourceManager.GetString("FilterEvaluationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProcessQueueMessage - additional information 的本地化字符串。
        /// </summary>
        internal static string FilterEvaluationFailed2 {
            get {
                return ResourceManager.GetString("FilterEvaluationFailed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///Message: 
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string FilterEvaluationFailed3 {
            get {
                return ResourceManager.GetString("FilterEvaluationFailed3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Formatter Factory 的本地化字符串。
        /// </summary>
        internal static string FormatterFactoryName {
            get {
                return ResourceManager.GetString("FormatterFactoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to find instance  name &apos;{0}&apos; for &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string InstanceNameNotFoundForSpecifiedType {
            get {
                return ResourceManager.GetString("InstanceNameNotFoundForSpecifiedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enterprise Library Logging Service 的本地化字符串。
        /// </summary>
        internal static string InstrumentationCounterCategory {
            get {
                return ResourceManager.GetString("InstrumentationCounterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enterprise Library Logging Service application performance counters. 的本地化字符串。
        /// </summary>
        internal static string InstrumentationCounterCategoryHelp {
            get {
                return ResourceManager.GetString("InstrumentationCounterCategoryHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enterprise Library Logging Service 的本地化字符串。
        /// </summary>
        internal static string InstrumentationEventSource {
            get {
                return ResourceManager.GetString("InstrumentationEventSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to read intrinsic property.  Error message: {0} 的本地化字符串。
        /// </summary>
        internal static string IntrinsicPropertyError {
            get {
                return ResourceManager.GetString("IntrinsicPropertyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error logging with &apos;{0}&apos; sink from configuration. The default log sink will be used instead to process the message. 的本地化字符串。
        /// </summary>
        internal static string InvalidSink {
            get {
                return ResourceManager.GetString("InvalidSink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///Message: 
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string InvalidSinkMessage {
            get {
                return ResourceManager.GetString("InvalidSinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission for UnmanagedCode is not available. 的本地化字符串。
        /// </summary>
        internal static string LogEntryIntrinsicPropertyNoUnmanagedCodePermissionError {
            get {
                return ResourceManager.GetString("LogEntryIntrinsicPropertyNoUnmanagedCodePermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging Events Raised/sec is the rate at which logging events were raised. 的本地化字符串。
        /// </summary>
        internal static string LoggingEventRaisedHelpResource {
            get {
                return ResourceManager.GetString("LoggingEventRaisedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AuthenticationType 的本地化字符串。
        /// </summary>
        internal static string ManagedSecurity_AuthenticationType {
            get {
                return ResourceManager.GetString("ManagedSecurity_AuthenticationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IdentityName 的本地化字符串。
        /// </summary>
        internal static string ManagedSecurity_IdentityName {
            get {
                return ResourceManager.GetString("ManagedSecurity_IdentityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsAuthenticated 的本地化字符串。
        /// </summary>
        internal static string ManagedSecurity_IsAuthenticated {
            get {
                return ResourceManager.GetString("ManagedSecurity_IsAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The method {0}::{1} is not implemented. 的本地化字符串。
        /// </summary>
        internal static string MethodNotImplemented {
            get {
                return ResourceManager.GetString("MethodNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no explicit mapping for the categories &apos;{0}&apos;. The log entry was: 
        ///{1} 的本地化字符串。
        /// </summary>
        internal static string MissingCategories {
            get {
                return ResourceManager.GetString("MissingCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The default formatter is missing from the configuration file.  The entry will be written using a TextFormatter and an embedded template. 的本地化字符串。
        /// </summary>
        internal static string MissingDefaultFormatter {
            get {
                return ResourceManager.GetString("MissingDefaultFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Distributor: # of Logs to Default Sink/Sec 的本地化字符串。
        /// </summary>
        internal static string NumLogsDefaultSinkSec {
            get {
                return ResourceManager.GetString("NumLogsDefaultSinkSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of logs per second distributed by the Log Distributor to the Default Log Sink (EventLog). 的本地化字符串。
        /// </summary>
        internal static string NumLogsDefaultSinkSecMsg {
            get {
                return ResourceManager.GetString("NumLogsDefaultSinkSecMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Distributor: # of Logs Distributed/Sec 的本地化字符串。
        /// </summary>
        internal static string NumLogsDistributedSec {
            get {
                return ResourceManager.GetString("NumLogsDistributedSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of logs distributed per second by the Log Distributor. 的本地化字符串。
        /// </summary>
        internal static string NumLogsDistributedSecMsg {
            get {
                return ResourceManager.GetString("NumLogsDistributedSecMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client: # of Logs Written/Sec 的本地化字符串。
        /// </summary>
        internal static string NumLogsWrittenSec {
            get {
                return ResourceManager.GetString("NumLogsWrittenSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of logs per second written by client using the Enterprise Library Logging Block. 的本地化字符串。
        /// </summary>
        internal static string NumLogsWrittenSecMsg {
            get {
                return ResourceManager.GetString("NumLogsWrittenSecMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing of the message failed. See summary information below for more information. Should this problem persist, stop the service and check the configuration file(s) for possible error(s) in the configuration of the categories and sinks. 的本地化字符串。
        /// </summary>
        internal static string ProcessMessageFailed {
            get {
                return ResourceManager.GetString("ProcessMessageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProcessQueueMessage - additional information 的本地化字符串。
        /// </summary>
        internal static string ProcessMessageFailed2 {
            get {
                return ResourceManager.GetString("ProcessMessageFailed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///Message: 
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string ProcessMessageFailed3 {
            get {
                return ResourceManager.GetString("ProcessMessageFailed3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access failed 的本地化字符串。
        /// </summary>
        internal static string PropertyAccessFailed {
            get {
                return ResourceManager.GetString("PropertyAccessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Error: property {0} threw an exception&gt; 的本地化字符串。
        /// </summary>
        internal static string ReflectedPropertyTokenException {
            get {
                return ResourceManager.GetString("ReflectedPropertyTokenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Error: property {0} is indexer&gt; 的本地化字符串。
        /// </summary>
        internal static string ReflectedPropertyTokenIndexer {
            get {
                return ResourceManager.GetString("ReflectedPropertyTokenIndexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Error: property {0} not found&gt; 的本地化字符串。
        /// </summary>
        internal static string ReflectedPropertyTokenNotFound {
            get {
                return ResourceManager.GetString("ReflectedPropertyTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Error: property {0} is not readable&gt; 的本地化字符串。
        /// </summary>
        internal static string ReflectedPropertyTokenNotReadable {
            get {
                return ResourceManager.GetString("ReflectedPropertyTokenNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Sink Factory 的本地化字符串。
        /// </summary>
        internal static string SinkFactoryName {
            get {
                return ResourceManager.GetString("SinkFactoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sink failed because: {0}. 的本地化字符串。
        /// </summary>
        internal static string SinkFailure {
            get {
                return ResourceManager.GetString("SinkFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {timestamp}: {title} - {message} 的本地化字符串。
        /// </summary>
        internal static string TemplateForFailedLogEntry {
            get {
                return ResourceManager.GetString("TemplateForFailedLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Logging Events Raised is the total number of logging events raised. 的本地化字符串。
        /// </summary>
        internal static string TotalLoggingEventsRaisedHelpResource {
            get {
                return ResourceManager.GetString("TotalLoggingEventsRaisedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Trace Listener Entries Written is the total number of entries that were traced by individual trace listeners. 的本地化字符串。
        /// </summary>
        internal static string TotalTraceListenerEntriesWrittenHelpResource {
            get {
                return ResourceManager.GetString("TotalTraceListenerEntriesWrittenHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Trace Operations Started is the total number of tracing operations started. 的本地化字符串。
        /// </summary>
        internal static string TotalTraceOperationsStartedHelpResource {
            get {
                return ResourceManager.GetString("TotalTraceOperationsStartedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trace Listener Entries Written/sec is the rate at which entries were traced by individual trace listeners. 的本地化字符串。
        /// </summary>
        internal static string TraceListenerEntryWrittenHelpResource {
            get {
                return ResourceManager.GetString("TraceListenerEntryWrittenHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trace Operations Started/sec is the rate at which tracing operations were started. 的本地化字符串。
        /// </summary>
        internal static string TraceOperationStartedHelpResource {
            get {
                return ResourceManager.GetString("TraceOperationStartedHelpResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Trace: Activity &apos;{0}&apos; in method &apos;{1}&apos; at {2} ticks (elapsed time: {3} seconds) 的本地化字符串。
        /// </summary>
        internal static string Tracer_EndMessageFormat {
            get {
                return ResourceManager.GetString("Tracer_EndMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Trace: Activity &apos;{0}&apos; in method &apos;{1}&apos; at {2} ticks 的本地化字符串。
        /// </summary>
        internal static string Tracer_StartMessageFormat {
            get {
                return ResourceManager.GetString("Tracer_StartMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tracing to LogSource &apos;{0}&apos; failed. Processing for other sources will continue. See summary information below for more information. Should this problem persist, stop the service and check the configuration file(s) for possible error(s) in the configuration of the categories and sinks. 的本地化字符串。
        /// </summary>
        internal static string TraceSourceFailed {
            get {
                return ResourceManager.GetString("TraceSourceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProcessQueueMessage - additional information 的本地化字符串。
        /// </summary>
        internal static string TraceSourceFailed2 {
            get {
                return ResourceManager.GetString("TraceSourceFailed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///Message: 
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string TraceSourceFailed3 {
            get {
                return ResourceManager.GetString("TraceSourceFailed3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unknown error has occurred. 的本地化字符串。
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknwon failure. 的本地化字符串。
        /// </summary>
        internal static string UnknownFailure {
            get {
                return ResourceManager.GetString("UnknownFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentUser 的本地化字符串。
        /// </summary>
        internal static string UnmanagedSecurity_CurrentUser {
            get {
                return ResourceManager.GetString("UnmanagedSecurity_CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProcessAccountName 的本地化字符串。
        /// </summary>
        internal static string UnmanagedSecurity_ProcessAccountName {
            get {
                return ResourceManager.GetString("UnmanagedSecurity_ProcessAccountName", resourceCulture);
            }
        }
    }
}
