//===============================================================================
// Microsoft patterns & practices Enterprise Library
// Exception Handling Application Block
//===============================================================================
// Copyright © Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.Configuration.Design.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.Configuration.Design.Prop" +
                            "erties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string CategoryGeneral {
            get {
                return ResourceManager.GetString("CategoryGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization.
        /// </summary>
        internal static string CategoryLocalization {
            get {
                return ResourceManager.GetString("CategoryLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Handler.
        /// </summary>
        internal static string DefaultCustomHandlerNodeName {
            get {
                return ResourceManager.GetString("DefaultCustomHandlerNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Handling Application Block.
        /// </summary>
        internal static string DefaultExceptionHandlingSettingsNodeName {
            get {
                return ResourceManager.GetString("DefaultExceptionHandlingSettingsNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Policy.
        /// </summary>
        internal static string DefaultExceptionPolicyNodeName {
            get {
                return ResourceManager.GetString("DefaultExceptionPolicyNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Type.
        /// </summary>
        internal static string DefaultExceptionTypeNodeName {
            get {
                return ResourceManager.GetString("DefaultExceptionTypeNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Handler.
        /// </summary>
        internal static string DefaultReplaceHandlerNodeName {
            get {
                return ResourceManager.GetString("DefaultReplaceHandlerNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap Handler.
        /// </summary>
        internal static string DefaultWrapHandlerNodeName {
            get {
                return ResourceManager.GetString("DefaultWrapHandlerNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception of type {0} is already configured for this policy..
        /// </summary>
        internal static string DuplicateExceptionTypeErrorMessage {
            get {
                return ResourceManager.GetString("DuplicateExceptionTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least 1 or more Exception Handler(s) for the type..
        /// </summary>
        internal static string ErrorNoExceptionHandlers {
            get {
                return ResourceManager.GetString("ErrorNoExceptionHandlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines any number of custom properties that can be passed to a handler..
        /// </summary>
        internal static string ExceptionHandlerAdditionalPropertiesDescription {
            get {
                return ResourceManager.GetString("ExceptionHandlerAdditionalPropertiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The friendly name of the exception handler..
        /// </summary>
        internal static string ExceptionHandlerNameDescription {
            get {
                return ResourceManager.GetString("ExceptionHandlerNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified name of the type of exception handler..
        /// </summary>
        internal static string ExceptionHandlerTypeDescription {
            get {
                return ResourceManager.GetString("ExceptionHandlerTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Handling Application Block.
        /// </summary>
        internal static string ExceptionHandlingSettingsNodeMenuText {
            get {
                return ResourceManager.GetString("ExceptionHandlingSettingsNodeMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the Exception Handling Application Block to the configuration.
        /// </summary>
        internal static string ExceptionHandlingSettingsNodeStatusText {
            get {
                return ResourceManager.GetString("ExceptionHandlingSettingsNodeStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Handling Application Block.
        /// </summary>
        internal static string ExceptionHandlingUICommandLongText {
            get {
                return ResourceManager.GetString("ExceptionHandlingUICommandLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Handling Application Block.
        /// </summary>
        internal static string ExceptionHandlingUICommandText {
            get {
                return ResourceManager.GetString("ExceptionHandlingUICommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Policy.
        /// </summary>
        internal static string ExceptionPolicyNodeMenuText {
            get {
                return ResourceManager.GetString("ExceptionPolicyNodeMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Exception Type.
        /// </summary>
        internal static string ExceptionPolicyNodeStatusText {
            get {
                return ResourceManager.GetString("ExceptionPolicyNodeStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The optional message for the replace exception..
        /// </summary>
        internal static string ExceptionReplaceMessageDescription {
            get {
                return ResourceManager.GetString("ExceptionReplaceMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified name of the type of exception to use for replacing..
        /// </summary>
        internal static string ExceptionReplaceTypeNameDescription {
            get {
                return ResourceManager.GetString("ExceptionReplaceTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Type.
        /// </summary>
        internal static string ExceptionTypeNodeMenuText {
            get {
                return ResourceManager.GetString("ExceptionTypeNodeMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified name of the type of Exception to get handled.  Must inherit from System.Exception..
        /// </summary>
        internal static string ExceptionTypeNodeNameDescription {
            get {
                return ResourceManager.GetString("ExceptionTypeNodeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Exception Type.
        /// </summary>
        internal static string ExceptionTypeNodeStatusText {
            get {
                return ResourceManager.GetString("ExceptionTypeNodeStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines what action should occur after an exception is handled by the configured exception handling chain.
        ///None: Indicates that no post handling action should occur.
        ///NotifyRethrow: Notifies the caller that a Rethrow of the original exception is recommended.
        ///ThrowNewException: Throws the resulting exception from the completed exception handling chain..
        /// </summary>
        internal static string ExceptionTypePostHandlingActionDescription {
            get {
                return ResourceManager.GetString("ExceptionTypePostHandlingActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified name of the type of exception to use for wrapping..
        /// </summary>
        internal static string ExceptionWrapTypeNameDescription {
            get {
                return ResourceManager.GetString("ExceptionWrapTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new {0}.
        /// </summary>
        internal static string GenericCreateStatusText {
            get {
                return ResourceManager.GetString("GenericCreateStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Exception Type..
        /// </summary>
        internal static string SelectTypeDialogCaption {
            get {
                return ResourceManager.GetString("SelectTypeDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The optional message for the wrap exception..
        /// </summary>
        internal static string WrapHandlerNodeMessageDescription {
            get {
                return ResourceManager.GetString("WrapHandlerNodeMessageDescription", resourceCulture);
            }
        }
    }
}
