//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5448
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheng.SailingEase.Core.Localisation {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Chinese__Simplified_ : ILanguage {
        
        private global::System.Resources.ResourceManager resourceMan;
        
        private global::System.Globalization.CultureInfo resourceCulture;
        
        public Chinese__Simplified_() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sheng.SailingEase.Core.Localisation.Chinese (Simplified)", typeof(Chinese__Simplified_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.Globalization.CultureInfo Culture {
            get {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    global::System.Globalization.CultureInfo temp = new global::System.Globalization.CultureInfo("zh-CHS");
                    resourceCulture = temp;
                }
                return resourceCulture;
            }
        }
        
        /// <summary>
        ///   查找类似 允许空 的本地化字符串。
        /// </summary>
        public string DataItemEntity_AllowEmpty {
            get {
                return ResourceManager.GetString("DataItemEntity_AllowEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否允许空值 的本地化字符串。
        /// </summary>
        public string DataItemEntity_AllowEmpty_Description {
            get {
                return ResourceManager.GetString("DataItemEntity_AllowEmpty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认值 的本地化字符串。
        /// </summary>
        public string DataItemEntity_DefaultValue {
            get {
                return ResourceManager.GetString("DataItemEntity_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该数据项的默认值 的本地化字符串。
        /// </summary>
        public string DataItemEntity_DefaultValue_Description {
            get {
                return ResourceManager.GetString("DataItemEntity_DefaultValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粗体 的本地化字符串。
        /// </summary>
        public string ElementFont_Bold {
            get {
                return ResourceManager.GetString("ElementFont_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该值指示此字体是否为粗体 的本地化字符串。
        /// </summary>
        public string ElementFont_Bold_Description {
            get {
                return ResourceManager.GetString("ElementFont_Bold_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体名 的本地化字符串。
        /// </summary>
        public string ElementFont_FontFamily {
            get {
                return ResourceManager.GetString("ElementFont_FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体名称 的本地化字符串。
        /// </summary>
        public string ElementFont_FontFamily_Description {
            get {
                return ResourceManager.GetString("ElementFont_FontFamily_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 斜体 的本地化字符串。
        /// </summary>
        public string ElementFont_Italic {
            get {
                return ResourceManager.GetString("ElementFont_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该值指示此字体是否为斜体 的本地化字符串。
        /// </summary>
        public string ElementFont_Italic_Description {
            get {
                return ResourceManager.GetString("ElementFont_Italic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尺寸 的本地化字符串。
        /// </summary>
        public string ElementFont_Size {
            get {
                return ResourceManager.GetString("ElementFont_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此字体的全身大小 的本地化字符串。
        /// </summary>
        public string ElementFont_Size_Description {
            get {
                return ResourceManager.GetString("ElementFont_Size_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下划线 的本地化字符串。
        /// </summary>
        public string ElementFont_Underline {
            get {
                return ResourceManager.GetString("ElementFont_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该值指示此字体是否有下划线 的本地化字符串。
        /// </summary>
        public string ElementFont_Underline_Description {
            get {
                return ResourceManager.GetString("ElementFont_Underline_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        public string EntityBase_Code {
            get {
                return ResourceManager.GetString("EntityBase_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 唯一标识 的本地化字符串。
        /// </summary>
        public string EntityBase_Code_Description {
            get {
                return ResourceManager.GetString("EntityBase_Code_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能以数字开头,且只能是大小写字母,数字或下划线组合 的本地化字符串。
        /// </summary>
        public string EntityBase_Code_RegexMsg {
            get {
                return ResourceManager.GetString("EntityBase_Code_RegexMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public string EntityBase_Name {
            get {
                return ResourceManager.GetString("EntityBase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public string EntityBase_Remark {
            get {
                return ResourceManager.GetString("EntityBase_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入一般说明文字 的本地化字符串。
        /// </summary>
        public string EntityBase_Remark_Description {
            get {
                return ResourceManager.GetString("EntityBase_Remark_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用者窗体 的本地化字符串。
        /// </summary>
        public string EnumCallEntityMethodTargetForm_Caller {
            get {
                return ResourceManager.GetString("EnumCallEntityMethodTargetForm_Caller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗体 的本地化字符串。
        /// </summary>
        public string EnumCallEntityMethodTargetForm_Current {
            get {
                return ResourceManager.GetString("EnumCallEntityMethodTargetForm_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public string EnumClearFormDataMode_All {
            get {
                return ResourceManager.GetString("EnumClearFormDataMode_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定 的本地化字符串。
        /// </summary>
        public string EnumClearFormDataMode_Appoint {
            get {
                return ResourceManager.GetString("EnumClearFormDataMode_Appoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略数据列表 的本地化字符串。
        /// </summary>
        public string EnumClearFormDataMode_IgnoreDataList {
            get {
                return ResourceManager.GetString("EnumClearFormDataMode_IgnoreDataList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据实体 的本地化字符串。
        /// </summary>
        public string EnumComboBoxDataSourceMode_DataEntity {
            get {
                return ResourceManager.GetString("EnumComboBoxDataSourceMode_DataEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 枚举 的本地化字符串。
        /// </summary>
        public string EnumComboBoxDataSourceMode_Enum {
            get {
                return ResourceManager.GetString("EnumComboBoxDataSourceMode_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本部分可编辑 的本地化字符串。
        /// </summary>
        public string EnumComboBoxStyle_DropDown {
            get {
                return ResourceManager.GetString("EnumComboBoxStyle_DropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能编辑文本,必须单击箭头按钮显示列表 的本地化字符串。
        /// </summary>
        public string EnumComboBoxStyle_DropDownList {
            get {
                return ResourceManager.GetString("EnumComboBoxStyle_DropDownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BottomCenter 的本地化字符串。
        /// </summary>
        public string EnumContentAlignment_BottomCenter {
            get {
                return ResourceManager.GetString("EnumContentAlignment_BottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BottomLeft 的本地化字符串。
        /// </summary>
        public string EnumContentAlignment_BottomLeft {
            get {
                return ResourceManager.GetString("EnumContentAlignment_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BottomRight 的本地化字符串。
        /// </summary>
        public string EnumContentAlignment_BottomRight {
            get {
                return ResourceManager.GetString("EnumContentAlignment_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MiddleCenter 的本地化字符串。
        /// </summary>
        public string EnumContentAlignment_MiddleCenter {
            get {
                return ResourceManager.GetString("EnumContentAlignment_MiddleCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MiddleLeft 的本地化字符串。
        /// </summary>
        public string EnumContentAlignment_MiddleLeft {
            get {
                return ResourceManager.GetString("EnumContentAlignment_MiddleLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MiddleRight 的本地化字符串。
        /// </summary>
        public string EnumContentAlignment_MiddleRight {
            get {
                return ResourceManager.GetString("EnumContentAlignment_MiddleRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TopCenter 的本地化字符串。
        /// </summary>
        public string EnumContentAlignment_TopCenter {
            get {
                return ResourceManager.GetString("EnumContentAlignment_TopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TopLeft 的本地化字符串。
        /// </summary>
        public string EnumContentAlignment_TopLeft {
            get {
                return ResourceManager.GetString("EnumContentAlignment_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TopRight 的本地化字符串。
        /// </summary>
        public string EnumContentAlignment_TopRight {
            get {
                return ResourceManager.GetString("EnumContentAlignment_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft SQL Server 2005 或更高版本 的本地化字符串。
        /// </summary>
        public string EnumDataBase_SqlServer {
            get {
                return ResourceManager.GetString("EnumDataBase_SqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布尔型 的本地化字符串。
        /// </summary>
        public string EnumDataItemType_Bit {
            get {
                return ResourceManager.GetString("EnumDataItemType_Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定长字符串 的本地化字符串。
        /// </summary>
        public string EnumDataItemType_Char {
            get {
                return ResourceManager.GetString("EnumDataItemType_Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双精度浮点数 的本地化字符串。
        /// </summary>
        public string EnumDataItemType_Decimal {
            get {
                return ResourceManager.GetString("EnumDataItemType_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单精度浮点数 的本地化字符串。
        /// </summary>
        public string EnumDataItemType_Float {
            get {
                return ResourceManager.GetString("EnumDataItemType_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据流 的本地化字符串。
        /// </summary>
        public string EnumDataItemType_Image {
            get {
                return ResourceManager.GetString("EnumDataItemType_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 整数 的本地化字符串。
        /// </summary>
        public string EnumDataItemType_Int {
            get {
                return ResourceManager.GetString("EnumDataItemType_Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期时间 的本地化字符串。
        /// </summary>
        public string EnumDataItemType_SmallDatetime {
            get {
                return ResourceManager.GetString("EnumDataItemType_SmallDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长文本 的本地化字符串。
        /// </summary>
        public string EnumDataItemType_Text {
            get {
                return ResourceManager.GetString("EnumDataItemType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 唯一标识 的本地化字符串。
        /// </summary>
        public string EnumDataItemType_Uniqueidentifier {
            get {
                return ResourceManager.GetString("EnumDataItemType_Uniqueidentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 变长字符串 的本地化字符串。
        /// </summary>
        public string EnumDataItemType_Varchar {
            get {
                return ResourceManager.GetString("EnumDataItemType_Varchar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大化 的本地化字符串。
        /// </summary>
        public string EnumFormWindowState_Maximized {
            get {
                return ResourceManager.GetString("EnumFormWindowState_Maximized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小化 的本地化字符串。
        /// </summary>
        public string EnumFormWindowState_Minimized {
            get {
                return ResourceManager.GetString("EnumFormWindowState_Minimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认大小 的本地化字符串。
        /// </summary>
        public string EnumFormWindowState_Normal {
            get {
                return ResourceManager.GetString("EnumFormWindowState_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等于 的本地化字符串。
        /// </summary>
        public string EnumMatchType_Equal {
            get {
                return ResourceManager.GetString("EnumMatchType_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于 的本地化字符串。
        /// </summary>
        public string EnumMatchType_Large {
            get {
                return ResourceManager.GetString("EnumMatchType_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于等于 的本地化字符串。
        /// </summary>
        public string EnumMatchType_LargeEqual {
            get {
                return ResourceManager.GetString("EnumMatchType_LargeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于 的本地化字符串。
        /// </summary>
        public string EnumMatchType_Less {
            get {
                return ResourceManager.GetString("EnumMatchType_Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于等于 的本地化字符串。
        /// </summary>
        public string EnumMatchType_LessEqual {
            get {
                return ResourceManager.GetString("EnumMatchType_LessEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匹配 的本地化字符串。
        /// </summary>
        public string EnumMatchType_Like {
            get {
                return ResourceManager.GetString("EnumMatchType_Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不等于 的本地化字符串。
        /// </summary>
        public string EnumMatchType_NotEqual {
            get {
                return ResourceManager.GetString("EnumMatchType_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激活 的本地化字符串。
        /// </summary>
        public string EnumOpenFormIfOpend_Activate {
            get {
                return ResourceManager.GetString("EnumOpenFormIfOpend_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭并打开新的 的本地化字符串。
        /// </summary>
        public string EnumOpenFormIfOpend_CloseAndOpenNew {
            get {
                return ResourceManager.GetString("EnumOpenFormIfOpend_CloseAndOpenNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开新的 的本地化字符串。
        /// </summary>
        public string EnumOpenFormIfOpend_OpenNew {
            get {
                return ResourceManager.GetString("EnumOpenFormIfOpend_OpenNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动 的本地化字符串。
        /// </summary>
        public string EnumPictureBoxSizeMode_AutoSize {
            get {
                return ResourceManager.GetString("EnumPictureBoxSizeMode_AutoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        public string EnumPictureBoxSizeMode_Normal {
            get {
                return ResourceManager.GetString("EnumPictureBoxSizeMode_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拉伸 的本地化字符串。
        /// </summary>
        public string EnumPictureBoxSizeMode_StretchImage {
            get {
                return ResourceManager.GetString("EnumPictureBoxSizeMode_StretchImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按比例缩放 的本地化字符串。
        /// </summary>
        public string EnumPictureBoxSizeMode_Zoom {
            get {
                return ResourceManager.GetString("EnumPictureBoxSizeMode_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前日期 的本地化字符串。
        /// </summary>
        public string EnumSystemDataSource_Date {
            get {
                return ResourceManager.GetString("EnumSystemDataSource_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前日期时间 的本地化字符串。
        /// </summary>
        public string EnumSystemDataSource_DateTime {
            get {
                return ResourceManager.GetString("EnumSystemDataSource_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录用户所在组唯一标识 的本地化字符串。
        /// </summary>
        public string EnumSystemDataSource_UserGroupId {
            get {
                return ResourceManager.GetString("EnumSystemDataSource_UserGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录用户所在组名 的本地化字符串。
        /// </summary>
        public string EnumSystemDataSource_UserGroupName {
            get {
                return ResourceManager.GetString("EnumSystemDataSource_UserGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录用户唯一标识 的本地化字符串。
        /// </summary>
        public string EnumSystemDataSource_UserId {
            get {
                return ResourceManager.GetString("EnumSystemDataSource_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录用户登录名 的本地化字符串。
        /// </summary>
        public string EnumSystemDataSource_UserLoginName {
            get {
                return ResourceManager.GetString("EnumSystemDataSource_UserLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录用户名 的本地化字符串。
        /// </summary>
        public string EnumSystemDataSource_UserName {
            get {
                return ResourceManager.GetString("EnumSystemDataSource_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public string EnumSystemForm_About {
            get {
                return ResourceManager.GetString("EnumSystemForm_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        public string EnumSystemForm_User {
            get {
                return ResourceManager.GetString("EnumSystemForm_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户组管理 的本地化字符串。
        /// </summary>
        public string EnumSystemForm_UserGroup {
            get {
                return ResourceManager.GetString("EnumSystemForm_UserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用者窗体 的本地化字符串。
        /// </summary>
        public string EnumTargetForm_Caller {
            get {
                return ResourceManager.GetString("EnumTargetForm_Caller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前窗体 的本地化字符串。
        /// </summary>
        public string EnumTargetForm_Current {
            get {
                return ResourceManager.GetString("EnumTargetForm_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImageAboveText 的本地化字符串。
        /// </summary>
        public string EnumTextImageRelation_ImageAboveText {
            get {
                return ResourceManager.GetString("EnumTextImageRelation_ImageAboveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImageBeforeText 的本地化字符串。
        /// </summary>
        public string EnumTextImageRelation_ImageBeforeText {
            get {
                return ResourceManager.GetString("EnumTextImageRelation_ImageBeforeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overlay 的本地化字符串。
        /// </summary>
        public string EnumTextImageRelation_Overlay {
            get {
                return ResourceManager.GetString("EnumTextImageRelation_Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TextAboveImage 的本地化字符串。
        /// </summary>
        public string EnumTextImageRelation_TextAboveImage {
            get {
                return ResourceManager.GetString("EnumTextImageRelation_TextAboveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TextBeforeImage 的本地化字符串。
        /// </summary>
        public string EnumTextImageRelation_TextBeforeImage {
            get {
                return ResourceManager.GetString("EnumTextImageRelation_TextBeforeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左 的本地化字符串。
        /// </summary>
        public string EnumToolStripItemAlignment_Left {
            get {
                return ResourceManager.GetString("EnumToolStripItemAlignment_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右 的本地化字符串。
        /// </summary>
        public string EnumToolStripItemAlignment_Right {
            get {
                return ResourceManager.GetString("EnumToolStripItemAlignment_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只显示图像 的本地化字符串。
        /// </summary>
        public string EnumToolStripItemDisplayStyle_Image {
            get {
                return ResourceManager.GetString("EnumToolStripItemDisplayStyle_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同时显示图像和文本 的本地化字符串。
        /// </summary>
        public string EnumToolStripItemDisplayStyle_ImageAndText {
            get {
                return ResourceManager.GetString("EnumToolStripItemDisplayStyle_ImageAndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 既不显示图像，也不显示文本 的本地化字符串。
        /// </summary>
        public string EnumToolStripItemDisplayStyle_None {
            get {
                return ResourceManager.GetString("EnumToolStripItemDisplayStyle_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只显示文本 的本地化字符串。
        /// </summary>
        public string EnumToolStripItemDisplayStyle_Text {
            get {
                return ResourceManager.GetString("EnumToolStripItemDisplayStyle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public string EnumTrueFalse_False {
            get {
                return ResourceManager.GetString("EnumTrueFalse_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public string EnumTrueFalse_True {
            get {
                return ResourceManager.GetString("EnumTrueFalse_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public string EnumValidateFormDataMode_All {
            get {
                return ResourceManager.GetString("EnumValidateFormDataMode_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定 的本地化字符串。
        /// </summary>
        public string EnumValidateFormDataMode_Appoint {
            get {
                return ResourceManager.GetString("EnumValidateFormDataMode_Appoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 边缘锚定 的本地化字符串。
        /// </summary>
        public string FormElement_Anchor {
            get {
                return ResourceManager.GetString("FormElement_Anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定义此窗体元素绑定到的容器边缘 的本地化字符串。
        /// </summary>
        public string FormElement_Anchor_Description {
            get {
                return ResourceManager.GetString("FormElement_Anchor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景色 的本地化字符串。
        /// </summary>
        public string FormElement_BackColorValue {
            get {
                return ResourceManager.GetString("FormElement_BackColorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此窗体元素的背景颜色 的本地化字符串。
        /// </summary>
        public string FormElement_BackColorValue_Description {
            get {
                return ResourceManager.GetString("FormElement_BackColorValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public string FormElement_Enabled {
            get {
                return ResourceManager.GetString("FormElement_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此窗体元素是否启用 的本地化字符串。
        /// </summary>
        public string FormElement_Enabled_Description {
            get {
                return ResourceManager.GetString("FormElement_Enabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体 的本地化字符串。
        /// </summary>
        public string FormElement_Font {
            get {
                return ResourceManager.GetString("FormElement_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于显示控件中文本的字体 的本地化字符串。
        /// </summary>
        public string FormElement_Font_Description {
            get {
                return ResourceManager.GetString("FormElement_Font_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前景色 的本地化字符串。
        /// </summary>
        public string FormElement_ForeColorValue {
            get {
                return ResourceManager.GetString("FormElement_ForeColorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此窗体元素的前景颜色 的本地化字符串。
        /// </summary>
        public string FormElement_ForeColorValue_Description {
            get {
                return ResourceManager.GetString("FormElement_ForeColorValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高度 的本地化字符串。
        /// </summary>
        public string FormElement_Height {
            get {
                return ResourceManager.GetString("FormElement_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此窗体元素的高度 的本地化字符串。
        /// </summary>
        public string FormElement_Height_Description {
            get {
                return ResourceManager.GetString("FormElement_Height_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左边距 的本地化字符串。
        /// </summary>
        public string FormElement_Left {
            get {
                return ResourceManager.GetString("FormElement_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此窗体元素与其容器的左侧边距 的本地化字符串。
        /// </summary>
        public string FormElement_Left_Description {
            get {
                return ResourceManager.GetString("FormElement_Left_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本 的本地化字符串。
        /// </summary>
        public string FormElement_Text {
            get {
                return ResourceManager.GetString("FormElement_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 与此窗体元素关联的文本 的本地化字符串。
        /// </summary>
        public string FormElement_Text_Description {
            get {
                return ResourceManager.GetString("FormElement_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶边距 的本地化字符串。
        /// </summary>
        public string FormElement_Top {
            get {
                return ResourceManager.GetString("FormElement_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此窗体元素与其容器的顶部边距 的本地化字符串。
        /// </summary>
        public string FormElement_Top_Description {
            get {
                return ResourceManager.GetString("FormElement_Top_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可见 的本地化字符串。
        /// </summary>
        public string FormElement_Visible {
            get {
                return ResourceManager.GetString("FormElement_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此窗体元素是否可见 的本地化字符串。
        /// </summary>
        public string FormElement_Visible_Description {
            get {
                return ResourceManager.GetString("FormElement_Visible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽度 的本地化字符串。
        /// </summary>
        public string FormElement_Width {
            get {
                return ResourceManager.GetString("FormElement_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此窗体元素的宽度 的本地化字符串。
        /// </summary>
        public string FormElement_Width_Description {
            get {
                return ResourceManager.GetString("FormElement_Width_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮 的本地化字符串。
        /// </summary>
        public string FormElementButtonEntity {
            get {
                return ResourceManager.GetString("FormElementButtonEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复合文本框 的本地化字符串。
        /// </summary>
        public string FormElementComboBoxEntity {
            get {
                return ResourceManager.GetString("FormElementComboBoxEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许空 的本地化字符串。
        /// </summary>
        public string FormElementComboBoxEntity_AllowEmpty {
            get {
                return ResourceManager.GetString("FormElementComboBoxEntity_AllowEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证窗体数据时是否允许文本为空 的本地化字符串。
        /// </summary>
        public string FormElementComboBoxEntity_AllowEmpty_Description {
            get {
                return ResourceManager.GetString("FormElementComboBoxEntity_AllowEmpty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样式 的本地化字符串。
        /// </summary>
        public string FormElementComboBoxEntity_ComboBoxStyle {
            get {
                return ResourceManager.GetString("FormElementComboBoxEntity_ComboBoxStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定复合文本框的样式 的本地化字符串。
        /// </summary>
        public string FormElementComboBoxEntity_ComboBoxStyle_Description {
            get {
                return ResourceManager.GetString("FormElementComboBoxEntity_ComboBoxStyle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据项 的本地化字符串。
        /// </summary>
        public string FormElementComboBoxEntity_DataItemId {
            get {
                return ResourceManager.GetString("FormElementComboBoxEntity_DataItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 与此窗体元素关联的数据项 的本地化字符串。
        /// </summary>
        public string FormElementComboBoxEntity_DataItemId_Description {
            get {
                return ResourceManager.GetString("FormElementComboBoxEntity_DataItemId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水印文本 的本地化字符串。
        /// </summary>
        public string FormElementComboBoxEntity_WaterText {
            get {
                return ResourceManager.GetString("FormElementComboBoxEntity_WaterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在没有输入内容时,淡色显示的提示文本 的本地化字符串。
        /// </summary>
        public string FormElementComboBoxEntity_WaterText_Description {
            get {
                return ResourceManager.GetString("FormElementComboBoxEntity_WaterText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据列表 的本地化字符串。
        /// </summary>
        public string FormElementDataListEntity {
            get {
                return ResourceManager.GetString("FormElementDataListEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据实体 的本地化字符串。
        /// </summary>
        public string FormElementDataListEntity_DataEntityId {
            get {
                return ResourceManager.GetString("FormElementDataListEntity_DataEntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 与此数据列表关联的数据实体 的本地化字符串。
        /// </summary>
        public string FormElementDataListEntity_DataEntityId_Description {
            get {
                return ResourceManager.GetString("FormElementDataListEntity_DataEntityId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 静态文本 的本地化字符串。
        /// </summary>
        public string FormElementLabelEntity {
            get {
                return ResourceManager.GetString("FormElementLabelEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动尺寸 的本地化字符串。
        /// </summary>
        public string FormElementLabelEntity_AutoSize {
            get {
                return ResourceManager.GetString("FormElementLabelEntity_AutoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指示是否自动调整控件的大小以完整显示其内容 的本地化字符串。
        /// </summary>
        public string FormElementLabelEntity_AutoSize_Description {
            get {
                return ResourceManager.GetString("FormElementLabelEntity_AutoSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本位置 的本地化字符串。
        /// </summary>
        public string FormElementLabelEntity_TextAlign {
            get {
                return ResourceManager.GetString("FormElementLabelEntity_TextAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本的对齐方式 的本地化字符串。
        /// </summary>
        public string FormElementLabelEntity_TextAlign_Description {
            get {
                return ResourceManager.GetString("FormElementLabelEntity_TextAlign_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片框 的本地化字符串。
        /// </summary>
        public string FormElementPictureBoxEntity {
            get {
                return ResourceManager.GetString("FormElementPictureBoxEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像 的本地化字符串。
        /// </summary>
        public string FormElementPictureBoxEntity_Img {
            get {
                return ResourceManager.GetString("FormElementPictureBoxEntity_Img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示的图像 的本地化字符串。
        /// </summary>
        public string FormElementPictureBoxEntity_Img_Description {
            get {
                return ResourceManager.GetString("FormElementPictureBoxEntity_Img_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尺寸模式 的本地化字符串。
        /// </summary>
        public string FormElementPictureBoxEntity_SizeMode {
            get {
                return ResourceManager.GetString("FormElementPictureBoxEntity_SizeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制如何显示图像位置和控件大小 的本地化字符串。
        /// </summary>
        public string FormElementPictureBoxEntity_SizeMode_Description {
            get {
                return ResourceManager.GetString("FormElementPictureBoxEntity_SizeMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本框 的本地化字符串。
        /// </summary>
        public string FormElementTextBoxEntity {
            get {
                return ResourceManager.GetString("FormElementTextBoxEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许空 的本地化字符串。
        /// </summary>
        public string FormElementTextBoxEntity_AllowEmpty {
            get {
                return ResourceManager.GetString("FormElementTextBoxEntity_AllowEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证窗体数据时是否允许文本为空 的本地化字符串。
        /// </summary>
        public string FormElementTextBoxEntity_AllowEmpty_Description {
            get {
                return ResourceManager.GetString("FormElementTextBoxEntity_AllowEmpty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据项 的本地化字符串。
        /// </summary>
        public string FormElementTextBoxEntity_DataItemId {
            get {
                return ResourceManager.GetString("FormElementTextBoxEntity_DataItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 与此窗体元素关联的数据项 的本地化字符串。
        /// </summary>
        public string FormElementTextBoxEntity_DataItemId_Description {
            get {
                return ResourceManager.GetString("FormElementTextBoxEntity_DataItemId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大字符 的本地化字符串。
        /// </summary>
        public string FormElementTextBoxEntity_MaxLength {
            get {
                return ResourceManager.GetString("FormElementTextBoxEntity_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本框可输入的最大字符长度 的本地化字符串。
        /// </summary>
        public string FormElementTextBoxEntity_MaxLength_Description {
            get {
                return ResourceManager.GetString("FormElementTextBoxEntity_MaxLength_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多行 的本地化字符串。
        /// </summary>
        public string FormElementTextBoxEntity_MultiLine {
            get {
                return ResourceManager.GetString("FormElementTextBoxEntity_MultiLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本是否能跨越多行 的本地化字符串。
        /// </summary>
        public string FormElementTextBoxEntity_MultiLine_Description {
            get {
                return ResourceManager.GetString("FormElementTextBoxEntity_MultiLine_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只读 的本地化字符串。
        /// </summary>
        public string FormElementTextBoxEntity_ReadOnly {
            get {
                return ResourceManager.GetString("FormElementTextBoxEntity_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 能否更改文本 的本地化字符串。
        /// </summary>
        public string FormElementTextBoxEntity_ReadOnly_Description {
            get {
                return ResourceManager.GetString("FormElementTextBoxEntity_ReadOnly_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景色 的本地化字符串。
        /// </summary>
        public string FormEntity_BackColorValue {
            get {
                return ResourceManager.GetString("FormEntity_BackColorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景颜色 的本地化字符串。
        /// </summary>
        public string FormEntity_BackColorValue_Description {
            get {
                return ResourceManager.GetString("FormEntity_BackColorValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体 的本地化字符串。
        /// </summary>
        public string FormEntity_Font {
            get {
                return ResourceManager.GetString("FormEntity_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于显示控件中文本的字体 的本地化字符串。
        /// </summary>
        public string FormEntity_Font_Description {
            get {
                return ResourceManager.GetString("FormEntity_Font_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前景色 的本地化字符串。
        /// </summary>
        public string FormEntity_ForeColorValue {
            get {
                return ResourceManager.GetString("FormEntity_ForeColorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前景颜色 的本地化字符串。
        /// </summary>
        public string FormEntity_ForeColorValue_Description {
            get {
                return ResourceManager.GetString("FormEntity_ForeColorValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高度 的本地化字符串。
        /// </summary>
        public string FormEntity_Height {
            get {
                return ResourceManager.GetString("FormEntity_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高度 的本地化字符串。
        /// </summary>
        public string FormEntity_Height_Description {
            get {
                return ResourceManager.GetString("FormEntity_Height_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本 的本地化字符串。
        /// </summary>
        public string FormEntity_Text {
            get {
                return ResourceManager.GetString("FormEntity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 与此窗体元素关联的文本 的本地化字符串。
        /// </summary>
        public string FormEntity_Text_Description {
            get {
                return ResourceManager.GetString("FormEntity_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽度 的本地化字符串。
        /// </summary>
        public string FormEntity_Width {
            get {
                return ResourceManager.GetString("FormEntity_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽度 的本地化字符串。
        /// </summary>
        public string FormEntity_Width_Description {
            get {
                return ResourceManager.GetString("FormEntity_Width_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public string FormEntity_WindowState {
            get {
                return ResourceManager.GetString("FormEntity_WindowState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定窗体的初始可视状态 的本地化字符串。
        /// </summary>
        public string FormEntity_WindowState_Description {
            get {
                return ResourceManager.GetString("FormEntity_WindowState_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布局 的本地化字符串。
        /// </summary>
        public string PropertyCatalog_Layout {
            get {
                return ResourceManager.GetString("PropertyCatalog_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规 的本地化字符串。
        /// </summary>
        public string PropertyCatalog_Normal {
            get {
                return ResourceManager.GetString("PropertyCatalog_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其它 的本地化字符串。
        /// </summary>
        public string PropertyCatalog_Other {
            get {
                return ResourceManager.GetString("PropertyCatalog_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分页 的本地化字符串。
        /// </summary>
        public string PropertyCatalog_Pagination {
            get {
                return ResourceManager.GetString("PropertyCatalog_Pagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样式 的本地化字符串。
        /// </summary>
        public string PropertyCatalog_Style {
            get {
                return ResourceManager.GetString("PropertyCatalog_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [系统] 的本地化字符串。
        /// </summary>
        public string SystemDataSoureDisplayString {
            get {
                return ResourceManager.GetString("SystemDataSoureDisplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统 的本地化字符串。
        /// </summary>
        public string SystemDataSoureProvide {
            get {
                return ResourceManager.GetString("SystemDataSoureProvide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具栏按钮 的本地化字符串。
        /// </summary>
        public string ToolStripButtonEntity {
            get {
                return ResourceManager.GetString("ToolStripButtonEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呈现样式 的本地化字符串。
        /// </summary>
        public string ToolStripButtonEntity_DisplayStyle {
            get {
                return ResourceManager.GetString("ToolStripButtonEntity_DisplayStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示何种对像 的本地化字符串。
        /// </summary>
        public string ToolStripButtonEntity_DisplayStyle_Description {
            get {
                return ResourceManager.GetString("ToolStripButtonEntity_DisplayStyle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像 的本地化字符串。
        /// </summary>
        public string ToolStripButtonEntity_ImagePath {
            get {
                return ResourceManager.GetString("ToolStripButtonEntity_ImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将显示在项上的图像 的本地化字符串。
        /// </summary>
        public string ToolStripButtonEntity_ImagePath_Description {
            get {
                return ResourceManager.GetString("ToolStripButtonEntity_ImagePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呈现方式 的本地化字符串。
        /// </summary>
        public string ToolStripButtonEntity_TextImageRelation {
            get {
                return ResourceManager.GetString("ToolStripButtonEntity_TextImageRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定控件上图像和文本彼此之间的相对位置 的本地化字符串。
        /// </summary>
        public string ToolStripButtonEntity_TextImageRelation_Description {
            get {
                return ResourceManager.GetString("ToolStripButtonEntity_TextImageRelation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对齐方式 的本地化字符串。
        /// </summary>
        public string ToolStripItemAbstract_Aligment {
            get {
                return ResourceManager.GetString("ToolStripItemAbstract_Aligment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对齐方式 的本地化字符串。
        /// </summary>
        public string ToolStripItemAbstract_Aligment_Description {
            get {
                return ResourceManager.GetString("ToolStripItemAbstract_Aligment_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本 的本地化字符串。
        /// </summary>
        public string ToolStripItemAbstract_Text {
            get {
                return ResourceManager.GetString("ToolStripItemAbstract_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在项上显示的文本 的本地化字符串。
        /// </summary>
        public string ToolStripItemAbstract_Text_Description {
            get {
                return ResourceManager.GetString("ToolStripItemAbstract_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示文本 的本地化字符串。
        /// </summary>
        public string ToolStripItemAbstract_ToolTipText {
            get {
                return ResourceManager.GetString("ToolStripItemAbstract_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指示显示的提示文本 的本地化字符串。
        /// </summary>
        public string ToolStripItemAbstract_ToolTipText_Description {
            get {
                return ResourceManager.GetString("ToolStripItemAbstract_ToolTipText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具栏文本 的本地化字符串。
        /// </summary>
        public string ToolStripLabelEntity {
            get {
                return ResourceManager.GetString("ToolStripLabelEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分隔条 的本地化字符串。
        /// </summary>
        public string ToolStripSeparatorEntity {
            get {
                return ResourceManager.GetString("ToolStripSeparatorEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗体元素 的本地化字符串。
        /// </summary>
        public string UIElementDataSourceProvide {
            get {
                return ResourceManager.GetString("UIElementDataSourceProvide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [窗体元素] 的本地化字符串。
        /// </summary>
        public string UIElementDataSoureDisplayString {
            get {
                return ResourceManager.GetString("UIElementDataSoureDisplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///  Returns true if the current language is the default language.
        /// </summary>
        public bool IsDefault {
            get {
                return true;
            }
        }
        
        /// <summary>
        ///  Returns a System.String that represents the current System.Object.
        /// </summary>
        public override string ToString() {
            return Culture.EnglishName;
        }
    }
}
