//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5446
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheng.SailingEase.Windows.Forms.Development.Localisation {
    
    
    public interface ILanguage {
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        global::System.Resources.ResourceManager ResourceManager {
            get;
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        global::System.Globalization.CultureInfo Culture {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的数据项不存在 的本地化字符串。
        /// </summary>
        string EntityDev_FormElementDataColumnEntityDev_DataItemEntityNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的数据实体不存在 的本地化字符串。
        /// </summary>
        string EntityDev_FormElementDataListEntityDev_DataEntityNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的数据实体不存在 的本地化字符串。
        /// </summary>
        string EntityDev_FormElementEditComboBoxEntityDev_DataEntityNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的数据项不存在 的本地化字符串。
        /// </summary>
        string EntityDev_FormElementEditComboBoxEntityDev_DataItemEntityNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的枚举不存在 的本地化字符串。
        /// </summary>
        string EntityDev_FormElementEditComboBoxEntityDev_EnumNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定的数据项不存在 的本地化字符串。
        /// </summary>
        string EntityDev_FormElementEditTextBoxEntityDev_DataItemEntityNotExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据规则 的本地化字符串。
        /// </summary>
        string FormElementComboBoxEntityDev_DataRule {
            get;
        }
        
        /// <summary>
        ///   查找类似 列 的本地化字符串。
        /// </summary>
        string FormElementDataListEntityDev_Column {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据规则 的本地化字符串。
        /// </summary>
        string FormElementTextboxEntityDev_DataRule {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据规则 的本地化字符串。
        /// </summary>
        string FormSEComboBoxExDevDataRule {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string FormSEComboBoxExDevDataRule_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        string FormSEComboBoxExDevDataRule_ButtonClear {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string FormSEComboBoxExDevDataRule_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据规则 的本地化字符串。
        /// </summary>
        string FormSEComboBoxExDevDataRule_LabelTitle {
            get;
        }
        
        /// <summary>
        ///   查找类似 列 的本地化字符串。
        /// </summary>
        string FormSEPaginationDataGridViewDevColumnAdd {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string FormSEPaginationDataGridViewDevColumnAdd_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        string FormSEPaginationDataGridViewDevColumnAdd_ButtonClose {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string FormSEPaginationDataGridViewDevColumnAdd_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 可见 的本地化字符串。
        /// </summary>
        string FormSEPaginationDataGridViewDevColumnAdd_CheckBoxVisible {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据项 的本地化字符串。
        /// </summary>
        string FormSEPaginationDataGridViewDevColumnAdd_DataItem {
            get;
        }
        
        /// <summary>
        ///   查找类似 源列代码 的本地化字符串。
        /// </summary>
        string FormSEPaginationDataGridViewDevColumnAdd_DataPropertyName {
            get;
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        string FormSEPaginationDataGridViewDevColumnAdd_LabelCode {
            get;
        }
        
        /// <summary>
        ///   查找类似 列头文本 的本地化字符串。
        /// </summary>
        string FormSEPaginationDataGridViewDevColumnAdd_LabelHeaderText {
            get;
        }
        
        /// <summary>
        ///   查找类似 列名 的本地化字符串。
        /// </summary>
        string FormSEPaginationDataGridViewDevColumnAdd_LabelName {
            get;
        }
        
        /// <summary>
        ///   查找类似 指定代码的窗体元素已存在 的本地化字符串。
        /// </summary>
        string FormSEPaginationDataGridViewDevColumnAdd_MessageElementCodeExist {
            get;
        }
        
        /// <summary>
        ///   查找类似 绑定 的本地化字符串。
        /// </summary>
        string FormSEPaginationDataGridViewDevColumnAdd_RadioButtonBind {
            get;
        }
        
        /// <summary>
        ///   查找类似 不绑定 的本地化字符串。
        /// </summary>
        string FormSEPaginationDataGridViewDevColumnAdd_RadioButtonUnBind {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据规则 的本地化字符串。
        /// </summary>
        string FormSETextBoxExDevDataRule {
            get;
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        string FormSETextBoxExDevDataRule_ButtonCancel {
            get;
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        string FormSETextBoxExDevDataRule_ButtonOK {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据规则 的本地化字符串。
        /// </summary>
        string FormSETextBoxExDevDataRule_LabelTitle {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据规则 的本地化字符串。
        /// </summary>
        string SEComboBoxExDev_Verb_DataRule {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑数据列 的本地化字符串。
        /// </summary>
        string SEPaginationDataGridViewDev_EditColumns_UndoTransaction_Name {
            get;
        }
        
        /// <summary>
        ///   查找类似 添加列 的本地化字符串。
        /// </summary>
        string SEPaginationDataGridViewDev_Verb_AddColumn {
            get;
        }
        
        /// <summary>
        ///   查找类似 编辑列 的本地化字符串。
        /// </summary>
        string SEPaginationDataGridViewDev_Verb_EditColumns {
            get;
        }
        
        /// <summary>
        ///   查找类似 列 的本地化字符串。
        /// </summary>
        string SEPaginationDataGridViewDev_Verb_FormCollectionEditorTitle {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据规则 的本地化字符串。
        /// </summary>
        string SETextBoxExDev_Verb_DataRule {
            get;
        }
        
        /// <summary>
        ///   查找类似 设置:{0} 的本地化字符串。
        /// </summary>
        string SEUndoUnit_Set {
            get;
        }
        
        /// <summary>
        ///   查找类似 显示项 的本地化字符串。
        /// </summary>
        string UserControlSEComboBoxExDevDataRule_DataEntity_LabelTextDataItem {
            get;
        }
        
        /// <summary>
        ///   查找类似 值项 的本地化字符串。
        /// </summary>
        string UserControlSEComboBoxExDevDataRule_DataEntity_LabelValueDataItem {
            get;
        }
        
        /// <summary>
        ///   查找类似 数据实体 的本地化字符串。
        /// </summary>
        string UserControlSEComboBoxExDevDataRule_DataEntity_TextBoxDataEntityNameTitle {
            get;
        }
        
        /// <summary>
        ///   查找类似 枚举 的本地化字符串。
        /// </summary>
        string UserControlSEComboBoxExDevDataRule_Enum_TextBoxEnumNameTitle {
            get;
        }
        
        /// <summary>
        ///   查找类似 允许值下拉列表 的本地化字符串。
        /// </summary>
        string UserControlSEComboBoxExDevDataRule_LabelDataSourceMode {
            get;
        }
        
        /// <summary>
        ///   查找类似 正则表达式 的本地化字符串。
        /// </summary>
        string UserControlSETextBoxExDevDataRuleRegex_LabelRegex {
            get;
        }
        
        /// <summary>
        ///   查找类似 正则表达式匹配失败提示 的本地化字符串。
        /// </summary>
        string UserControlSETextBoxExDevDataRuleRegex_LabelRegexMsg {
            get;
        }
        
        /// <summary>
        ///   查找类似 预置 的本地化字符串。
        /// </summary>
        string UserControlSETextBoxExDevDataRuleRegex_RegexLib {
            get;
        }
        
        /// <summary>
        ///   查找类似 工具 的本地化字符串。
        /// </summary>
        string UserControlSETextBoxExDevDataRuleRegex_Tool {
            get;
        }
        
        /// <summary>
        ///  Returns true if the current language is the default language.
        /// </summary>
        bool IsDefault {
            get;
        }
    }
}
